import { useEffect, useState } from 'react'
import { Activity, BookOpen, Building2, CheckCircle2, Clock3, Database, Grape, NotebookPen, RefreshCw, ShieldCheck, Users, Wine } from 'lucide-react'
import { useLocale, type Locale } from './i18n'

type Overview={people:{users:number;workspaces:number;roles:Record<string,number>};catalogue:{regions:number;grapes:number;producers:number;wines:number;lessons:number};community:{cellarRecords:number;bottles:number;tastingNotes:number};workflow:{editorialDrafts:number;editorialReview:number;pendingApprovals:number;publishedEvents:number;draftEvents:number;verifiedPartners:number;pendingPartners:number;activeOffers:number};auditEntries:number}

const copy:Record<Locale,{eyebrow:string;title:string;body:string;refresh:string;unavailable:string;people:string;workspaces:string;cellars:string;bottles:string;notes:string;lessons:string;review:string;approvals:string;partners:string;events:string;catalogue:string;operations:string;roles:string;quiet:string;regions:string;varieties:string;wineries:string;wines:string;audit:string;roleNames:Record<string,string>}>={
  en:{eyebrow:'Platform overview',title:'One view of knowledge, people and publication',body:'Live totals from the database connect editorial work, professional access and the private collections growing around the atlas.',refresh:'Refresh',unavailable:'The operational overview could not be loaded.',people:'accounts',workspaces:'workspaces',cellars:'cellar records',bottles:'bottles held',notes:'tasting notes',lessons:'knowledge guides',review:'editorial reviews',approvals:'partner approvals',partners:'verified partners',events:'published events',catalogue:'Knowledge base',operations:'Current work',roles:'Role distribution',quiet:'No pending editorial or partner work.',regions:'Regions',varieties:'Varieties',wineries:'Wineries',wines:'Wines',audit:'Audit entries',roleNames:{member:'Private',host:'Host',winery:'Winery',merchant:'Merchant',admin:'Admin'}},
  de:{eyebrow:'Plattformübersicht',title:'Wissen, Menschen und Veröffentlichung in einer Ansicht',body:'Live-Daten aus der Datenbank verbinden redaktionelle Arbeit, professionelle Zugänge und die privaten Sammlungen rund um den Atlas.',refresh:'Aktualisieren',unavailable:'Die Betriebsübersicht konnte nicht geladen werden.',people:'Konten',workspaces:'Workspaces',cellars:'Kellereinträge',bottles:'gelagerte Flaschen',notes:'Verkostungsnotizen',lessons:'Wissensguides',review:'redaktionelle Prüfungen',approvals:'Partnerfreigaben',partners:'verifizierte Partner',events:'veröffentlichte Events',catalogue:'Wissensbasis',operations:'Aktuelle Aufgaben',roles:'Rollenverteilung',quiet:'Keine offenen redaktionellen oder Partner-Aufgaben.',regions:'Regionen',varieties:'Rebsorten',wineries:'Weingüter',wines:'Weine',audit:'Protokolleinträge',roleNames:{member:'Privat',host:'Host',winery:'Weingut',merchant:'Händler',admin:'Admin'}},
  fr:{eyebrow:'Vue de la plateforme',title:'Savoirs, personnes et publications réunis',body:'Les données directes relient le travail éditorial, les accès professionnels et les caves privées constituées autour de l’atlas.',refresh:'Actualiser',unavailable:'Impossible de charger la vue opérationnelle.',people:'comptes',workspaces:'espaces',cellars:'fiches de cave',bottles:'bouteilles conservées',notes:'notes de dégustation',lessons:'guides de connaissance',review:'révisions éditoriales',approvals:'validations partenaires',partners:'partenaires vérifiés',events:'événements publiés',catalogue:'Base de connaissances',operations:'Travail en cours',roles:'Répartition des rôles',quiet:'Aucune tâche éditoriale ou partenaire en attente.',regions:'Régions',varieties:'Cépages',wineries:'Domaines',wines:'Vins',audit:'Entrées du journal',roleNames:{member:'Privé',host:'Hôte',winery:'Domaine',merchant:'Marchand',admin:'Admin'}},
  es:{eyebrow:'Vista de la plataforma',title:'Conocimiento, personas y publicación en una sola vista',body:'Los datos en directo conectan el trabajo editorial, los accesos profesionales y las colecciones privadas creadas alrededor del atlas.',refresh:'Actualizar',unavailable:'No se pudo cargar la vista operativa.',people:'cuentas',workspaces:'espacios',cellars:'registros de bodega',bottles:'botellas guardadas',notes:'notas de cata',lessons:'guías de conocimiento',review:'revisiones editoriales',approvals:'aprobaciones de socios',partners:'socios verificados',events:'eventos publicados',catalogue:'Base de conocimiento',operations:'Trabajo actual',roles:'Distribución de roles',quiet:'No hay tareas editoriales ni de socios pendientes.',regions:'Regiones',varieties:'Variedades',wineries:'Bodegas',wines:'Vinos',audit:'Entradas del registro',roleNames:{member:'Privado',host:'Anfitrión',winery:'Bodega',merchant:'Comerciante',admin:'Admin'}}
}

export function AdminOperationsOverview(){
  const {locale}=useLocale(),c=copy[locale]
  const [data,setData]=useState<Overview>(),[error,setError]=useState(false),[loading,setLoading]=useState(true)
  const load=async()=>{setLoading(true);setError(false);try{const response=await fetch('/api/admin/overview',{credentials:'same-origin'});if(!response.ok)throw new Error();setData(await response.json() as Overview)}catch{setError(true)}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  return <section className="admin-operations-overview">
    <header><div><span className="eyebrow">{c.eyebrow}</span><h2>{c.title}</h2><p>{c.body}</p></div><button className="secondary-button" onClick={()=>void load()} disabled={loading}><RefreshCw/>{c.refresh}</button></header>
    {error?<div className="admin-overview-error"><Database/><p>{c.unavailable}</p></div>:data&&<>
      <div className="admin-live-metrics">
        <article><Users/><strong>{data.people.users}</strong><span>{c.people}</span></article><article><Building2/><strong>{data.people.workspaces}</strong><span>{c.workspaces}</span></article>
        <article><Wine/><strong>{data.community.bottles}</strong><span>{c.bottles}</span></article><article><NotebookPen/><strong>{data.community.tastingNotes}</strong><span>{c.notes}</span></article>
        <article><BookOpen/><strong>{data.catalogue.lessons}</strong><span>{c.lessons}</span></article><article><Activity/><strong>{data.auditEntries}</strong><span>{c.audit}</span></article>
      </div>
      <div className="admin-operational-columns">
        <article><header><Grape/><div><span>{c.catalogue}</span><strong>{data.catalogue.regions+data.catalogue.grapes+data.catalogue.producers+data.catalogue.wines}</strong></div></header><dl><div><dt>{c.regions}</dt><dd>{data.catalogue.regions}</dd></div><div><dt>{c.varieties}</dt><dd>{data.catalogue.grapes}</dd></div><div><dt>{c.wineries}</dt><dd>{data.catalogue.producers}</dd></div><div><dt>{c.wines}</dt><dd>{data.catalogue.wines}</dd></div></dl></article>
        <article><header><Clock3/><div><span>{c.operations}</span><strong>{data.workflow.editorialReview+data.workflow.pendingApprovals+data.workflow.pendingPartners}</strong></div></header><dl><div><dt>{c.review}</dt><dd>{data.workflow.editorialReview}</dd></div><div><dt>{c.approvals}</dt><dd>{data.workflow.pendingApprovals}</dd></div><div><dt>{c.partners}</dt><dd>{data.workflow.verifiedPartners}</dd></div><div><dt>{c.events}</dt><dd>{data.workflow.publishedEvents}</dd></div></dl>{data.workflow.editorialReview+data.workflow.pendingApprovals+data.workflow.pendingPartners===0&&<p><CheckCircle2/>{c.quiet}</p>}</article>
        <article><header><ShieldCheck/><div><span>{c.roles}</span><strong>{Object.values(data.people.roles).reduce((sum,value)=>sum+value,0)}</strong></div></header><div className="role-distribution">{Object.entries(data.people.roles).sort((a,b)=>b[1]-a[1]).map(([role,value])=><div key={role}><span>{c.roleNames[role]??role}</span><i style={{width:`${Math.max(8,value/Math.max(1,data.people.users)*100)}%`}}/><strong>{value}</strong></div>)}</div></article>
      </div>
    </>}
  </section>
}
