import { ExternalLink, FlaskConical, Layers3 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { grapes, regions } from './data/catalog'
import { useLocale, type Locale } from './i18n'

type Localized=Record<Locale,string>
type BlendProfile={
  id:string
  name:string
  grapeIds:string[]
  regionIds:string[]
  summary:Localized
  composition:Localized
  source:{label:string;url:string}
}

const contributions:Record<string,Localized>={
  'cabernet-sauvignon':{en:'tannic frame, black-fruit depth and long ageing potential',de:'Tanninrahmen, dunkle Frucht und langes Reifepotenzial',fr:'trame tannique, fruit noir et potentiel de garde',es:'estructura tánica, fruta negra y capacidad de guarda'},
  merlot:{en:'mid-palate volume, plum fruit and supple texture',de:'Volumen am Gaumen, Pflaumenfrucht und geschmeidige Textur',fr:'volume en bouche, prune et texture souple',es:'volumen en boca, ciruela y textura flexible'},
  'cabernet-franc':{en:'lift, red fruit, floral detail and fresh herbal tension',de:'Duft, rote Frucht, florale Details und kräutrige Spannung',fr:'élan, fruit rouge, détail floral et tension végétale fraîche',es:'elevación, fruta roja, detalle floral y tensión herbal fresca'},
  'petit-verdot':{en:'colour, firm tannin, violet and pepper in small supporting amounts',de:'Farbe, festes Tannin, Veilchen und Pfeffer in kleinen Anteilen',fr:'couleur, tanin ferme, violette et poivre en appoint',es:'color, tanino firme, violeta y pimienta en pequeñas proporciones'},
  malbec:{en:'deep colour, dark fruit and generous mid-palate weight',de:'Tiefe Farbe, dunkle Frucht und Fülle am Gaumen',fr:'couleur profonde, fruit noir et chair en milieu de bouche',es:'color profundo, fruta oscura y peso en el centro de boca'},
  carmenere:{en:'spice, dark fruit and a distinctive savoury-herbal register',de:'Würze, dunkle Frucht und eine markante kräutrig-herzhafte Note',fr:'épices, fruit noir et registre végétal-sapide distinctif',es:'especias, fruta oscura y un registro herbal sabroso'},
  'sauvignon-blanc':{en:'acid line, citrus energy and aromatic definition',de:'Säurezug, Zitrusenergie und aromatische Kontur',fr:'ligne acide, énergie citronnée et précision aromatique',es:'línea ácida, energía cítrica y definición aromática'},
  semillon:{en:'waxen texture, breadth and affinity with bottle age or noble rot',de:'wachsige Textur, Fülle und Eignung für Flaschenreife oder Edelfäule',fr:'texture cireuse, ampleur et aptitude à la garde ou à la pourriture noble',es:'textura cerosa, amplitud y afinidad con la guarda o la podredumbre noble'},
  muscadelle:{en:'a floral, grapey accent used as aromatic seasoning',de:'einen floralen, traubigen Akzent als aromatische Würze',fr:'un accent floral et muscaté utilisé comme assaisonnement aromatique',es:'un acento floral y de uva usado como condimento aromático'},
  corvina:{en:'the structural and aromatic backbone, with sour cherry and supple tannin',de:'das strukturelle und aromatische Rückgrat mit Sauerkirsche und geschmeidigem Tannin',fr:'la colonne vertébrale aromatique et structurelle, cerise acidulée et tanin souple',es:'la columna aromática y estructural, con cereza ácida y tanino flexible'},
  corvinone:{en:'spiced cherry, aromatic complexity and additional structure',de:'würzige Kirsche, aromatische Komplexität und zusätzliche Struktur',fr:'cerise épicée, complexité aromatique et structure supplémentaire',es:'cereza especiada, complejidad aromática y estructura adicional'},
  rondinella:{en:'colour, resilience in the vineyard and a savoury finishing note',de:'Farbe, Widerstandskraft im Weinberg und eine würzige Schlussnote',fr:'couleur, résistance au vignoble et finale savoureuse',es:'color, resistencia en viñedo y un final sabroso'},
  molinara:{en:'freshness and a saline, lightly coloured counterpoint',de:'Frische und einen salzigen, farblich leichten Gegenpol',fr:'fraîcheur et contrepoint salin peu coloré',es:'frescura y un contrapunto salino de poco color'},
  'grenache-garnacha':{en:'ripe red fruit, warmth and volume',de:'reife rote Frucht, Wärme und Volumen',fr:'fruit rouge mûr, chaleur et volume',es:'fruta roja madura, calidez y volumen'},
  'syrah-shiraz':{en:'pepper, violet, dark fruit and firmer structure',de:'Pfeffer, Veilchen, dunkle Frucht und festere Struktur',fr:'poivre, violette, fruit noir et structure plus ferme',es:'pimienta, violeta, fruta oscura y estructura más firme'},
  'mourvedre-monastrell':{en:'late-ripening depth, savoury spice and tannic persistence',de:'spät reifende Tiefe, herzhafte Würze und anhaltendes Tannin',fr:'profondeur tardive, épices savoureuses et persistance tannique',es:'profundidad de maduración tardía, especia sabrosa y persistencia tánica'},
  cinsault:{en:'perfume, bright red fruit and a softer contour',de:'Duft, helle rote Frucht und weichere Kontur',fr:'parfum, fruit rouge vif et contour plus souple',es:'perfume, fruta roja viva y un contorno más suave'},
  carignan:{en:'acidity, herbal-dark fruit and structural grip; called Mazuelo in Rioja',de:'Säure, kräutrig-dunkle Frucht und Griff; in Rioja Mazuelo genannt',fr:'acidité, fruit noir herbacé et accroche ; appelé Mazuelo en Rioja',es:'acidez, fruta oscura herbal y agarre; llamado Mazuelo en Rioja'},
  chardonnay:{en:'citrus-floral freshness, chalky line and ageing capacity',de:'zitrisch-florale Frische, kreidige Linie und Reifefähigkeit',fr:'fraîcheur citronnée-florale, ligne crayeuse et aptitude au vieillissement',es:'frescura cítrica y floral, línea calcárea y capacidad de guarda'},
  'pinot-noir':{en:'body, structure and red-fruit depth even when pressed as a white base wine',de:'Körper, Struktur und rote Fruchttiefe auch als weiß gekelterter Grundwein',fr:'corps, structure et profondeur de fruit rouge, même pressé en blanc',es:'cuerpo, estructura y profundidad de fruta roja incluso prensado en blanco'},
  'pinot-meunier':{en:'roundness, accessible fruit and resilience in frost-prone sites',de:'Rundung, zugängliche Frucht und Robustheit in frostgefährdeten Lagen',fr:'rondeur, fruit immédiat et résistance dans les sites gélifs',es:'redondez, fruta accesible y resistencia en zonas de heladas'},
  tempranillo:{en:'the central red-fruit, savoury and structural voice of the blend',de:'die zentrale rotfruchtige, würzige und strukturelle Stimme der Cuvée',fr:'la voix centrale, fruitée, savoureuse et structurante de l’assemblage',es:'la voz central de fruta roja, sabor y estructura del ensamblaje'},
  graciano:{en:'aromatic lift, acidity and fine-grained structure in supporting amounts',de:'aromatische Höhe, Säure und feinkörnige Struktur in ergänzenden Anteilen',fr:'relief aromatique, acidité et structure fine en appoint',es:'elevación aromática, acidez y estructura fina en proporciones de apoyo'},
  'maturana-tinta':{en:'colour, dark fruit, pepper and a compact tannic accent',de:'Farbe, dunkle Frucht, Pfeffer und einen kompakten Tanninakzent',fr:'couleur, fruit noir, poivre et accent tannique compact',es:'color, fruta oscura, pimienta y un acento tánico compacto'},
  'viura-macabeo':{en:'fresh orchard fruit, floral lift and a supple base for long lees ageing',de:'frische Kernobstfrucht, florale Höhe und eine geschmeidige Basis für langes Hefelager',fr:'fruit du verger, élan floral et base souple pour un long élevage sur lies',es:'fruta de huerto, elevación floral y una base flexible para larga crianza sobre lías'},
  'xarel-lo':{en:'structure, savoury-herbal detail and firm acidity for ageing',de:'Struktur, würzig-kräutrige Details und feste Säure für die Reife',fr:'structure, détail végétal-sapide et acidité ferme pour la garde',es:'estructura, detalle herbal sabroso y acidez firme para la guarda'},
  parellada:{en:'delicacy, freshness and a lighter floral contour',de:'Feinheit, Frische und eine leichtere florale Kontur',fr:'délicatesse, fraîcheur et contour floral plus léger',es:'delicadeza, frescura y un contorno floral más ligero'},
  marsanne:{en:'body, waxen texture and nutty-floral development with age',de:'Körper, wachsige Textur und nussig-florale Entwicklung mit Reife',fr:'corps, texture cireuse et évolution florale-noisettée',es:'cuerpo, textura cerosa y evolución floral y de frutos secos'},
  roussanne:{en:'acidity, perfume and fine texture that can lift a broader partner',de:'Säure, Duft und feine Textur als Gegengewicht zu einem breiteren Partner',fr:'acidité, parfum et texture fine qui allègent un partenaire plus ample',es:'acidez, perfume y textura fina que elevan a un socio más amplio'},
  viognier:{en:'yellow-fruit perfume, volume and a soft aromatic bridge',de:'Gelbfruchtduft, Volumen und eine weiche aromatische Brücke',fr:'parfum de fruits jaunes, volume et liaison aromatique souple',es:'perfume de fruta amarilla, volumen y un puente aromático suave'},
  'grenache-blanc':{en:'warm-climate body, aniseed freshness and gentle phenolic grip',de:'warmklimatischen Körper, Anisfrische und sanften phenolischen Griff',fr:'corps de climat chaud, fraîcheur anisée et légère accroche phénolique',es:'cuerpo de clima cálido, frescura anisada y suave agarre fenólico'},
  clairette:{en:'freshness, pale-fruit fragrance and a clean, lightly bitter finish',de:'Frische, helle Frucht und einen klaren, leicht herben Abschluss',fr:'fraîcheur, fruit pâle et finale nette légèrement amère',es:'frescura, fruta clara y un final limpio ligeramente amargo'},
  'touriga-nacional':{en:'colour, floral-black-fruit intensity and compact tannic length',de:'Farbe, floral-dunkle Intensität und kompakte Tanninlänge',fr:'couleur, intensité florale et noire, longueur tannique compacte',es:'color, intensidad floral y oscura y longitud tánica compacta'},
  'touriga-franca':{en:'fragrant dark fruit, colour and a polished structural middle',de:'duftige dunkle Frucht, Farbe und eine geschliffene strukturelle Mitte',fr:'fruit noir parfumé, couleur et milieu de bouche structuré et poli',es:'fruta oscura fragante, color y un centro estructural pulido'},
  'tinta-barroca':{en:'ripe fruit, sugar accumulation and breadth in hot, dry sites',de:'reife Frucht, Zuckerreife und Breite in heißen, trockenen Lagen',fr:'fruit mûr, richesse en sucre et ampleur dans les sites chauds et secs',es:'fruta madura, acumulación de azúcar y amplitud en lugares cálidos y secos'},
  'tinto-cao':{en:'firm acidity, floral spice and slow-ripening persistence',de:'feste Säure, florale Würze und spät reifende Ausdauer',fr:'acidité ferme, épices florales et persistance tardive',es:'acidez firme, especia floral y persistencia de maduración lenta'},
}

export const classicBlends:BlendProfile[]=[
  {id:'bordeaux-red',name:'Bordeaux red blend',grapeIds:['merlot','cabernet-sauvignon','cabernet-franc','petit-verdot','malbec','carmenere'],regionIds:['bordeaux','medoc','saint-emilion','pomerol'],summary:{en:'A family of site- and vintage-dependent blends, not a fixed recipe. Cabernet-led gravel-bank wines and Merlot/Cabernet Franc-led clay-limestone wines can sit at opposite ends of the same regional language.',de:'Eine Familie lage- und jahrgangsabhängiger Cuvées, kein festes Rezept. Cabernet-geprägte Kiesweine und Merlot/Cabernet-Franc-geprägte Ton-Kalk-Weine markieren unterschiedliche Pole derselben Regionalsprache.',fr:'Une famille d’assemblages dictés par le site et le millésime, sans recette fixe. Les vins de graves dominés par le Cabernet et ceux d’argile-calcaire dominés par Merlot/Cabernet Franc en sont deux pôles.',es:'Una familia de ensamblajes según lugar y añada, no una receta fija. Los vinos de gravas dominados por Cabernet y los de arcilla-caliza con Merlot/Cabernet Franc forman polos distintos.'},composition:{en:'Merlot, Cabernet Sauvignon and Cabernet Franc are the principal voices; Petit Verdot, Malbec and Carménère can provide accents.',de:'Merlot, Cabernet Sauvignon und Cabernet Franc sind die Hauptstimmen; Petit Verdot, Malbec und Carménère können Akzente setzen.',fr:'Merlot, Cabernet Sauvignon et Cabernet Franc dominent ; Petit Verdot, Malbec et Carménère peuvent compléter.',es:'Merlot, Cabernet Sauvignon y Cabernet Franc dominan; Petit Verdot, Malbec y Carménère pueden completar.'},source:{label:'Bordeaux Wine Council · grape varieties',url:'https://www.bordeaux.com/en/grape-varieties/'}},
  {id:'bordeaux-white',name:'Bordeaux white blend',grapeIds:['sauvignon-blanc','semillon','muscadelle'],regionIds:['bordeaux','graves-sauternes'],summary:{en:'The same palette can produce brisk dry whites or botrytised sweet wines. The balance shifts with site, harvest condition and intended texture.',de:'Dieselbe Palette kann straffe trockene Weißweine oder edelsüße Botrytisweine hervorbringen. Lage, Lesebedingung und gewünschte Textur verschieben die Balance.',fr:'La même palette produit des blancs secs vifs ou des liquoreux botrytisés. Le site, l’état de récolte et la texture recherchée déplacent l’équilibre.',es:'La misma paleta produce blancos secos vivos o dulces botritizados. Lugar, estado de vendimia y textura buscada cambian el equilibrio.'},composition:{en:'Sauvignon Blanc supplies aromatic acidity; Sémillon supplies texture and ageing potential; Muscadelle is a smaller floral component.',de:'Sauvignon Blanc liefert aromatische Säure, Sémillon Textur und Reifepotenzial, Muscadelle einen kleineren floralen Anteil.',fr:'Sauvignon Blanc apporte acidité aromatique, Sémillon texture et garde, Muscadelle une touche florale.',es:'Sauvignon Blanc aporta acidez aromática, Sémillon textura y guarda, y Muscadelle un toque floral.'},source:{label:'Bordeaux Wine Council · Bordeaux styles',url:'https://www.bordeaux.com/en/designations/bordeaux-bordeaux-superieur-and-cremant/bordeaux/'}},
  {id:'amarone-valpolicella',name:'Amarone & Valpolicella family',grapeIds:['corvina','corvinone','rondinella','molinara'],regionIds:['valpolicella'],summary:{en:'Amarone is a dry Valpolicella DOCG wine style made after appassimento, not a grape. The same indigenous blending family also underpins Valpolicella, Ripasso and sweet Recioto; process changes concentration, alcohol, texture and sweetness.',de:'Amarone ist ein trockener Valpolicella-DOCG-Weinstil aus getrockneten Trauben, keine Rebsorte. Dieselbe autochthone Cuvée-Familie trägt Valpolicella, Ripasso und süßen Recioto; das Verfahren verändert Konzentration, Alkohol, Textur und Süße.',fr:'Amarone est un style sec DOCG de Valpolicella issu de l’appassimento, pas un cépage. La même famille autochtone fonde Valpolicella, Ripasso et Recioto doux ; le procédé module concentration, alcool, texture et sucre.',es:'Amarone es un estilo seco DOCG de Valpolicella elaborado tras appassimento, no una uva. La misma familia autóctona sostiene Valpolicella, Ripasso y Recioto dulce; el proceso cambia concentración, alcohol, textura y dulzor.'},composition:{en:'The official range is 45–95% Corvina and/or Corvinone and 5–30% Rondinella; authorised supporting varieties may complete the blend. Molinara is optional, not compulsory.',de:'Offiziell sind 45–95 % Corvina und/oder Corvinone sowie 5–30 % Rondinella vorgesehen; zugelassene Ergänzungssorten können die Cuvée vervollständigen. Molinara ist optional.',fr:'La plage officielle prévoit 45–95 % de Corvina et/ou Corvinone et 5–30 % de Rondinella ; des cépages autorisés peuvent compléter. Molinara reste facultative.',es:'El rango oficial es 45–95 % Corvina y/o Corvinone y 5–30 % Rondinella; otras variedades autorizadas pueden completar. Molinara es opcional.'},source:{label:'Consorzio Valpolicella · varieties and production',url:'https://www.consorziovalpolicella.it/en/the-varieties/'}},
  {id:'southern-rhone-red',name:'Southern Rhône red blend',grapeIds:['grenache-garnacha','syrah-shiraz','mourvedre-monastrell','cinsault','carignan'],regionIds:['southern-rhone'],summary:{en:'A warm-climate blending family in which Grenache often supplies breadth and fruit while later-ripening, darker or fresher partners tune structure, perfume and longevity. Individual appellation rules differ.',de:'Eine warmklimatische Cuvée-Familie: Grenache liefert häufig Weite und Frucht, später reifende, dunklere oder frischere Partner justieren Struktur, Duft und Langlebigkeit. Die Regeln unterscheiden sich je Appellation.',fr:'Une famille d’assemblages de climat chaud où Grenache apporte souvent ampleur et fruit, tandis que des partenaires plus tardifs, sombres ou frais règlent structure, parfum et garde. Les règles varient selon l’appellation.',es:'Una familia de clima cálido donde Garnacha suele aportar amplitud y fruta, mientras socios más tardíos, oscuros o frescos ajustan estructura, perfume y longevidad. Las reglas varían por denominación.'},composition:{en:'Grenache Noir, Syrah and Mourvèdre are the three principal red varieties across the Rhône; Cinsault and Carignan are common supporting voices in the south.',de:'Grenache Noir, Syrah und Mourvèdre sind die drei roten Hauptsorten der Rhône; Cinsault und Carignan ergänzen im Süden häufig.',fr:'Grenache Noir, Syrah et Mourvèdre sont les trois rouges principaux du Rhône ; Cinsault et Carignan jouent souvent un rôle d’appoint au sud.',es:'Garnacha, Syrah y Mourvèdre son las tres tintas principales del Ródano; Cinsault y Carignan suelen apoyar en el sur.'},source:{label:'Inter Rhône · grape varieties',url:'https://www.vins-rhone.com/en/rhone-valley-vineyards/grape-varieties'}},
  {id:'champagne-assemblage',name:'Champagne assemblage',grapeIds:['chardonnay','pinot-noir','pinot-meunier'],regionIds:['champagne','montagne-de-reims','vallee-de-la-marne','cote-des-blancs'],summary:{en:'Champagne blending is broader than grape percentages: cellar masters may assemble varieties, crus, parcels and reserve wines from several years to sustain a house style. Vintage Champagne narrows the year but can still blend sites and grapes.',de:'Champagne-Assemblage umfasst mehr als Rebsortenanteile: Kellermeister verbinden Sorten, Crus, Parzellen und Reserveweine mehrerer Jahre zu einem Hausstil. Jahrgangschampagner begrenzt das Jahr, kann aber weiterhin Lagen und Sorten verbinden.',fr:'L’assemblage champenois dépasse les pourcentages de cépages : crus, parcelles et vins de réserve de plusieurs années composent un style de maison. Un millésimé limite l’année mais peut toujours unir sites et cépages.',es:'El ensamblaje de Champagne va más allá de porcentajes: variedades, crus, parcelas y vinos de reserva de varios años sostienen el estilo de la casa. Un millésime limita el año, pero aún puede unir lugares y uvas.'},composition:{en:'Chardonnay, Pinot Noir and Meunier are the three overwhelmingly used varieties, each bringing a different balance of freshness, structure, fruit and evolution.',de:'Chardonnay, Pinot Noir und Meunier sind die drei mit Abstand meistgenutzten Sorten; sie bringen unterschiedliche Balance aus Frische, Struktur, Frucht und Entwicklung.',fr:'Chardonnay, Pinot Noir et Meunier dominent très largement, avec des équilibres distincts de fraîcheur, structure, fruit et évolution.',es:'Chardonnay, Pinot Noir y Meunier dominan ampliamente, con equilibrios distintos de frescura, estructura, fruta y evolución.'},source:{label:'Comité Champagne · blending',url:'https://www.champagne.fr/en/about-champagne/how-champagne-is-made/blending-champagne'}},
  {id:'rioja-red',name:'Rioja red blend',grapeIds:['tempranillo','grenache-garnacha','graciano','carignan','maturana-tinta'],regionIds:['rioja','rioja-alta','rioja-alavesa','rioja-oriental'],summary:{en:'Rioja can be varietal or blended. Combining grapes is used to increase complexity or balance acidity, tannin and body; subzone, elevation and maturation choice are at least as important as a formula.',de:'Rioja kann sortenrein oder als Cuvée entstehen. Rebsorten werden für mehr Komplexität oder zum Ausgleich von Säure, Tannin und Körper verbunden; Subzone, Höhe und Ausbau sind mindestens ebenso wichtig wie eine Formel.',fr:'Rioja peut être monocépage ou assemblé. L’assemblage accroît la complexité ou équilibre acidité, tanin et corps ; sous-zone, altitude et élevage comptent autant qu’une formule.',es:'Rioja puede ser monovarietal o ensamblado. Mezclar aumenta complejidad o equilibra acidez, tanino y cuerpo; subzona, altitud y crianza importan tanto como una fórmula.'},composition:{en:'Tempranillo is joined by Garnacha, Graciano, Mazuelo (Carignan) and Maturana Tinta among the authorised red palette.',de:'Tempranillo wird in der zugelassenen roten Palette durch Garnacha, Graciano, Mazuelo (Carignan) und Maturana Tinta ergänzt.',fr:'Tempranillo est complété par Garnacha, Graciano, Mazuelo (Carignan) et Maturana Tinta dans la palette rouge autorisée.',es:'Tempranillo se une a Garnacha, Graciano, Mazuelo (Carignan) y Maturana Tinta dentro de la paleta tinta autorizada.'},source:{label:'Consejo Regulador DOCa Rioja · red wines',url:'https://riojawine.com/en-us/the-designation/types-of-wine/red-wines/'}},
  {id:'cava-classic',name:'Classic Cava coupage',grapeIds:['viura-macabeo','xarel-lo','parellada'],regionIds:['penedes'],summary:{en:'The traditional Cava trio is a method-ready ensemble rather than a fixed percentage recipe. Base-wine acidity, phenolic structure, tirage, lees time and dosage all shape the final balance.',de:'Das traditionelle Cava-Trio ist ein Ensemble für die traditionelle Methode, kein Rezept mit festen Anteilen. Säure des Grundweins, Phenolik, Tirage, Hefelager und Dosage formen die Balance.',fr:'Le trio traditionnel du Cava est un ensemble adapté à la méthode, non une recette de pourcentages. Acidité du vin de base, phénoliques, tirage, lies et dosage façonnent l’équilibre.',es:'El trío tradicional del Cava es un conjunto adaptado al método, no una receta de porcentajes. Acidez del vino base, fenoles, tiraje, lías y dosaje forman el equilibrio.'},composition:{en:'Macabeo, Xarel-lo and Parellada form the classic coupage; the appellation also authorises other white and red varieties.',de:'Macabeo, Xarel-lo und Parellada bilden die klassische Cuvée; die Herkunft erlaubt außerdem weitere weiße und rote Sorten.',fr:'Macabeo, Xarel-lo et Parellada forment le coupage classique ; l’appellation autorise aussi d’autres cépages blancs et noirs.',es:'Macabeo, Xarel-lo y Parellada forman el coupage clásico; la denominación también autoriza otras variedades blancas y tintas.'},source:{label:'D.O. Cava · authorised grape varieties',url:'https://www.cava.wine/en/origin-cava/authorised-grape-varieties/'}},
  {id:'rhone-white',name:'Rhône white blend',grapeIds:['marsanne','roussanne','viognier','grenache-blanc','clairette'],regionIds:['northern-rhone','southern-rhone'],summary:{en:'Rhône whites span northern Marsanne–Roussanne partnerships and the broader southern palette. Variety, site, harvest date, skin handling and vessel determine whether the result is taut, floral, waxen or broad.',de:'Weiße Rhône-Cuvées reichen vom nördlichen Marsanne–Roussanne-Duo bis zur breiteren südlichen Palette. Sorte, Lage, Lese, Schalenkontakt und Gefäß entscheiden zwischen Spannung, Duft, Wachsigkeit und Fülle.',fr:'Les blancs du Rhône vont du duo Marsanne–Roussanne au nord à la palette plus large du sud. Cépage, site, vendange, pellicules et contenant règlent tension, parfum, cire et ampleur.',es:'Los blancos del Ródano van del dúo Marsanne–Roussanne del norte a la paleta más amplia del sur. Variedad, lugar, vendimia, pieles y recipiente deciden tensión, perfume, cera y amplitud.'},composition:{en:'Marsanne and Roussanne are key partners in northern appellations; southern blends can add Grenache Blanc, Clairette and Viognier among a wider authorised palette.',de:'Marsanne und Roussanne sind wichtige Partner im Norden; südliche Cuvées können Grenache Blanc, Clairette und Viognier aus einer größeren zugelassenen Palette ergänzen.',fr:'Marsanne et Roussanne sont des partenaires majeurs au nord ; au sud, Grenache Blanc, Clairette et Viognier rejoignent une palette autorisée plus large.',es:'Marsanne y Roussanne son socios clave en el norte; al sur se suman Grenache Blanc, Clairette y Viognier dentro de una paleta más amplia.'},source:{label:'Inter Rhône · grape varieties',url:'https://www.vins-rhone.com/en/rhone-valley-vineyards/grape-varieties'}},
  {id:'douro-port',name:'Douro & Port red field blend',grapeIds:['touriga-nacional','touriga-franca','tinta-barroca','tinto-cao','tempranillo'],regionIds:['douro'],summary:{en:'Douro and Port are built from a broad indigenous palette, often co-planted in older vineyards. A blend can balance heat, altitude, schist, harvest timing and—in Port—fortification and subsequent ageing.',de:'Douro und Port beruhen auf einer breiten autochthonen Palette, in alten Weinbergen oft gemischt gepflanzt. Die Cuvée balanciert Wärme, Höhe, Schiefer, Lese und beim Port zusätzlich Aufspritung und Reife.',fr:'Douro et Porto reposent sur une vaste palette autochtone, souvent complantée dans les vieilles vignes. L’assemblage équilibre chaleur, altitude, schiste, vendange et, pour le Porto, mutage puis élevage.',es:'Douro y Oporto parten de una amplia paleta autóctona, a menudo mezclada en viñas viejas. El ensamblaje equilibra calor, altitud, esquisto, vendimia y, en Oporto, fortificación y crianza.'},composition:{en:'Touriga Franca, Tinta Roriz (Tempranillo), Touriga Nacional, Tinta Barroca and Tinto Cão are among the most prominent authorised red varieties.',de:'Touriga Franca, Tinta Roriz (Tempranillo), Touriga Nacional, Tinta Barroca und Tinto Cão gehören zu den wichtigsten zugelassenen roten Sorten.',fr:'Touriga Franca, Tinta Roriz (Tempranillo), Touriga Nacional, Tinta Barroca et Tinto Cão figurent parmi les rouges autorisés majeurs.',es:'Touriga Franca, Tinta Roriz (Tempranillo), Touriga Nacional, Tinta Barroca y Tinto Cão figuran entre las tintas autorizadas más importantes.'},source:{label:'IVDP · vine culture and varieties',url:'https://www.ivdp.pt/en/viticulture/vine-culture/'}},
]

export function validateClassicBlends(){
  const grapeIds=new Set(grapes.map(item=>item.id))
  const regionIds=new Set(regions.map(item=>item.id))
  const issues:string[]=[]
  for(const blend of classicBlends){
    if(!blend.grapeIds.length)issues.push(`Blend ${blend.id} has no grapes`)
    for(const id of blend.grapeIds){if(!grapeIds.has(id))issues.push(`Blend ${blend.id} references unknown grape ${id}`);if(!contributions[id])issues.push(`Blend ${blend.id} has no contribution text for ${id}`)}
    for(const id of blend.regionIds)if(!regionIds.has(id))issues.push(`Blend ${blend.id} references unknown region ${id}`)
    if(!/^https:\/\//.test(blend.source.url))issues.push(`Blend ${blend.id} needs an HTTPS source`)
    for(const locale of ['en','de','fr','es'] as const){if(!blend.summary[locale]||!blend.composition[locale]||!localizedBlendNames[blend.id]?.[locale])issues.push(`Blend ${blend.id} is incomplete in ${locale}`)}
  }
  return issues
}

const sectionCopy={
  en:{eyebrow:'Blending grammar',title:'Where this variety works in an ensemble',intro:'A blend is not a quality rank or a universal recipe. It is a set of complementary decisions shaped by place, vintage, regulation and the intended style.',role:'Its role here',palette:'Classic palette',places:'Connected places',source:'Official reference'},
  de:{eyebrow:'Grammatik der Cuvée',title:'Wo diese Rebsorte im Ensemble wirkt',intro:'Eine Cuvée ist weder Qualitätsstufe noch Universalrezept. Sie verbindet komplementäre Entscheidungen aus Ort, Jahrgang, Regelwerk und gewünschtem Stil.',role:'Ihre Rolle hier',palette:'Klassische Palette',places:'Verknüpfte Orte',source:'Offizielle Quelle'},
  fr:{eyebrow:'Grammaire de l’assemblage',title:'Le rôle de ce cépage dans un ensemble',intro:'Un assemblage n’est ni un rang de qualité ni une recette universelle. Il unit des décisions complémentaires selon lieu, millésime, règlement et style recherché.',role:'Son rôle ici',palette:'Palette classique',places:'Lieux reliés',source:'Référence officielle'},
  es:{eyebrow:'Gramática del ensamblaje',title:'Dónde actúa esta variedad en conjunto',intro:'Un ensamblaje no es un rango de calidad ni una receta universal. Une decisiones complementarias según lugar, añada, norma y estilo buscado.',role:'Su función aquí',palette:'Paleta clásica',places:'Lugares conectados',source:'Referencia oficial'},
} satisfies Record<Locale,Record<string,string>>

const localizedBlendNames:Record<string,Localized>={
  'bordeaux-red':{en:'Bordeaux red blend',de:'Rote Bordeaux-Cuvée',fr:'Assemblage rouge de Bordeaux',es:'Ensamblaje tinto de Burdeos'},
  'bordeaux-white':{en:'Bordeaux white blend',de:'Weiße Bordeaux-Cuvée',fr:'Assemblage blanc de Bordeaux',es:'Ensamblaje blanco de Burdeos'},
  'amarone-valpolicella':{en:'Amarone & Valpolicella family',de:'Amarone- und Valpolicella-Familie',fr:'Famille Amarone et Valpolicella',es:'Familia Amarone y Valpolicella'},
  'southern-rhone-red':{en:'Southern Rhône red blend',de:'Rote Cuvée der südlichen Rhône',fr:'Assemblage rouge du Rhône méridional',es:'Ensamblaje tinto del Ródano meridional'},
  'champagne-assemblage':{en:'Champagne assemblage',de:'Champagner-Assemblage',fr:'Assemblage champenois',es:'Ensamblaje de Champagne'},
  'rioja-red':{en:'Rioja red blend',de:'Rote Rioja-Cuvée',fr:'Assemblage rouge de Rioja',es:'Ensamblaje tinto de Rioja'},
  'cava-classic':{en:'Classic Cava coupage',de:'Klassische Cava-Cuvée',fr:'Coupage classique du Cava',es:'Coupage clásico de Cava'},
  'rhone-white':{en:'Rhône white blend',de:'Weiße Rhône-Cuvée',fr:'Assemblage blanc du Rhône',es:'Ensamblaje blanco del Ródano'},
  'douro-port':{en:'Douro & Port red field blend',de:'Rote Douro- und Port-Cuvée',fr:'Assemblage rouge du Douro et de Porto',es:'Ensamblaje tinto de Douro y Oporto'},
}

export function BlendConnections({grapeId}:{grapeId:string}){
  const {locale}=useLocale()
  const c=sectionCopy[locale]
  const matches=classicBlends.filter(blend=>blend.grapeIds.includes(grapeId))
  if(!matches.length)return null
  return <section className="blend-connections">
    <header><div><span className="eyebrow">{c.eyebrow}</span><h2>{c.title}</h2></div><p>{c.intro}</p></header>
    <div>{matches.map(blend=><article key={blend.id}>
      <div className="blend-card-heading"><span><Layers3/></span><div><small>{c.palette}</small><h3>{localizedBlendNames[blend.id]?.[locale]??blend.name}</h3></div></div>
      <p>{blend.summary[locale]}</p>
      <div className="blend-role"><FlaskConical/><div><small>{c.role}</small><strong>{contributions[grapeId]?.[locale]}</strong></div></div>
      <p className="blend-composition">{blend.composition[locale]}</p>
      <div className="blend-links"><small>{c.palette}</small><div>{blend.grapeIds.map(id=>{const grape=grapes.find(item=>item.id===id);return grape?<Link className={id===grapeId?'current':''} key={id} to={`/grapes/${id}`}>{grape.name}</Link>:null})}</div></div>
      <div className="blend-links"><small>{c.places}</small><div>{blend.regionIds.map(id=>{const region=regions.find(item=>item.id===id);return region?<Link key={id} to={`/regions/${id}`}>{region.name}</Link>:null})}</div></div>
      <a className="blend-source" href={blend.source.url} target="_blank" rel="noreferrer">{c.source} · {blend.source.label}<ExternalLink/></a>
    </article>)}</div>
  </section>
}
