import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { createPortal } from 'react-dom'
import { Link } from 'react-router-dom'
import { Archive, ArrowRight, BookOpen, Camera, Check, ChevronDown, ChevronUp, Clock3, Compass, Grape, ImagePlus, MapPin, Minus, NotebookPen, Plus, Search, SlidersHorizontal, Sparkles, Trash2, Wine, WineOff, X } from 'lucide-react'
import { aromaContent, articleContent, countryLabel, regionName } from './localizedContent'
import { aromas, articles, grapes, producers, regions, wines } from './data/catalog'
import { repository } from './data/repository'
import { deleteBottlePhoto, prepareBottlePhoto, uploadBottlePhoto } from './lib/image'
import { useLocale, type Locale } from './i18n'
import { useUiCopy } from './uiCopy'
import type { CellarItem, CellarTastingNote } from './types'

type CellarState = CellarItem['state']

const cellarCopy: Record<Locale, {
  eyebrow:string; title:string; intro:string; add:string; search:string; all:string; bottles:string; wishlist:string; noted:string; emptyTitle:string; emptyBody:string;
  owned:string; tasted:string; finished:string; details:string; closeDetails:string; remove:string; confirmRemove:string; quantity:string; location:string; vintage:string; bottleSize:string;
  purchaseDate:string; purchasePrice:string; currency:string; source:string; drinkWindow:string; drinkFrom:string; drinkUntil:string; occasion:string; saveDetails:string; saved:string;
  notes:string; addNote:string; appearance:string; aromas:string; palate:string; finish:string; reflection:string; acidity:string; tannin:string; body:string; rating:string; saveNote:string;
  noNotes:string; fromAtlas:string; ownEntry:string; wine:string; wineName:string; producer:string; region:string; collection:string; photo:string; photoBody:string; choosePhoto:string;
  changePhoto:string; removePhoto:string; preparing:string; photoError:string; saveBottle:string; nonVintage:string; bottleStudy:string; bottleStudyBody:string; latestNote:string;
  light:string; medium:string; full:string; short:string; persistent:string; clear:string; pale:string; deep:string; homeCellar:string; addSuccess:string; more?:string;
}> = {
  en:{eyebrow:'Personal collection',title:'A cellar built from memories',intro:'Keep bottles, drinking windows and purchase details together with the sensory notes that made a wine worth remembering.',add:'Add a bottle',search:'Search wine, producer, region or vintage',all:'All',bottles:'bottles',wishlist:'wish list',noted:'with notes',emptyTitle:'No bottles in this view',emptyBody:'Change the filter or add the first bottle to begin your cellar.',owned:'Owned',tasted:'Tasted',finished:'Finished',details:'Open bottle record',closeDetails:'Close bottle record',remove:'Remove',confirmRemove:'Remove permanently?',quantity:'Quantity',location:'Storage location',vintage:'Vintage',bottleSize:'Bottle size',purchaseDate:'Purchase date',purchasePrice:'Purchase price',currency:'Currency',source:'Bought from',drinkWindow:'Drinking window',drinkFrom:'From',drinkUntil:'Until',occasion:'Occasion or memory',saveDetails:'Save bottle details',saved:'Saved',notes:'Tasting notes',addNote:'Add a structured note',appearance:'Appearance',aromas:'Aromas',palate:'Palate',finish:'Finish',reflection:'Conclusion and memory',acidity:'Acidity',tannin:'Tannin',body:'Body',rating:'Rating',saveNote:'Save tasting note',noNotes:'No tasting note yet. Record the wine as it is today; the next bottle may tell a different story.',fromAtlas:'From the atlas',ownEntry:'My own entry',wine:'Wine',wineName:'Wine name',producer:'Producer',region:'Region',collection:'Collection',photo:'Bottle photo',photoBody:'Use the camera or choose an image. It is resized and saved to your cloud media library.',choosePhoto:'Choose photo',changePhoto:'Change photo',removePhoto:'Remove photo',preparing:'Preparing photo…',photoError:'This image could not be prepared or uploaded.',saveBottle:'Save to cellar',nonVintage:'NV',bottleStudy:'Why bottle shapes differ',bottleStudyBody:'Shoulders, glass weight and bottle pressure began as practical choices. Shape can suggest tradition, but it never proves quality.',latestNote:'Latest note',light:'Light',medium:'Medium',full:'Full',short:'Short',persistent:'Persistent',clear:'Clear',pale:'Pale',deep:'Deep',homeCellar:'Home cellar',addSuccess:'Bottle added to your cellar.',more:'more'},
  de:{eyebrow:'Persönliche Sammlung',title:'Ein Keller aus Erinnerungen',intro:'Bewahre Flaschen, Trinkfenster und Einkaufsdetails zusammen mit den sensorischen Notizen auf, die einen Wein erinnerungswürdig gemacht haben.',add:'Flasche hinzufügen',search:'Wein, Winzer, Region oder Jahrgang suchen',all:'Alle',bottles:'Flaschen',wishlist:'Wunschliste',noted:'mit Notizen',emptyTitle:'Keine Flaschen in dieser Ansicht',emptyBody:'Ändere den Filter oder lege die erste Flasche in deinen Keller.',owned:'Im Keller',tasted:'Verkostet',finished:'Getrunken',details:'Flaschendetails öffnen',closeDetails:'Flaschendetails schließen',remove:'Entfernen',confirmRemove:'Dauerhaft entfernen?',quantity:'Anzahl',location:'Lagerort',vintage:'Jahrgang',bottleSize:'Flaschengröße',purchaseDate:'Kaufdatum',purchasePrice:'Kaufpreis',currency:'Währung',source:'Gekauft bei',drinkWindow:'Trinkfenster',drinkFrom:'Von',drinkUntil:'Bis',occasion:'Anlass oder Erinnerung',saveDetails:'Flaschendetails speichern',saved:'Gespeichert',notes:'Verkostungsnotizen',addNote:'Strukturierte Notiz anlegen',appearance:'Aussehen',aromas:'Aromen',palate:'Gaumen',finish:'Abgang',reflection:'Fazit und Erinnerung',acidity:'Säure',tannin:'Tannin',body:'Körper',rating:'Bewertung',saveNote:'Verkostungsnotiz speichern',noNotes:'Noch keine Verkostungsnotiz. Halte den Wein so fest, wie er heute wirkt; die nächste Flasche kann eine neue Geschichte erzählen.',fromAtlas:'Aus dem Atlas',ownEntry:'Eigener Eintrag',wine:'Wein',wineName:'Weinname',producer:'Weingut',region:'Region',collection:'Sammlung',photo:'Flaschenfoto',photoBody:'Nutze die Kamera oder wähle ein Bild. Es wird verkleinert und in deiner Cloud-Mediathek gespeichert.',choosePhoto:'Foto wählen',changePhoto:'Foto ändern',removePhoto:'Foto entfernen',preparing:'Foto wird vorbereitet…',photoError:'Dieses Bild konnte nicht vorbereitet oder hochgeladen werden.',saveBottle:'Im Keller speichern',nonVintage:'NV',bottleStudy:'Warum Flaschenformen verschieden sind',bottleStudyBody:'Schultern, Glasgewicht und Druckfestigkeit entstanden aus praktischen Entscheidungen. Eine Form kann Tradition andeuten, beweist aber nie Qualität.',latestNote:'Neueste Notiz',light:'Leicht',medium:'Mittel',full:'Kräftig',short:'Kurz',persistent:'Anhaltend',clear:'Klar',pale:'Hell',deep:'Tief',homeCellar:'Hauskeller',addSuccess:'Flasche wurde deinem Keller hinzugefügt.'},
  fr:{eyebrow:'Collection personnelle',title:'Une cave faite de souvenirs',intro:'Réunissez bouteilles, fenêtres de dégustation, achats et notes sensorielles qui rendent un vin mémorable.',add:'Ajouter une bouteille',search:'Chercher vin, domaine, région ou millésime',all:'Tout',bottles:'bouteilles',wishlist:'liste de souhaits',noted:'avec notes',emptyTitle:'Aucune bouteille dans cette vue',emptyBody:'Changez le filtre ou ajoutez la première bouteille de votre cave.',owned:'En cave',tasted:'Dégusté',finished:'Bu',details:'Ouvrir la fiche bouteille',closeDetails:'Fermer la fiche bouteille',remove:'Retirer',confirmRemove:'Retirer définitivement ?',quantity:'Quantité',location:'Lieu de stockage',vintage:'Millésime',bottleSize:'Format',purchaseDate:'Date d’achat',purchasePrice:'Prix d’achat',currency:'Devise',source:'Acheté chez',drinkWindow:'Fenêtre de dégustation',drinkFrom:'De',drinkUntil:'À',occasion:'Occasion ou souvenir',saveDetails:'Enregistrer les détails',saved:'Enregistré',notes:'Notes de dégustation',addNote:'Ajouter une note structurée',appearance:'Robe',aromas:'Arômes',palate:'Bouche',finish:'Finale',reflection:'Conclusion et souvenir',acidity:'Acidité',tannin:'Tanins',body:'Corps',rating:'Note',saveNote:'Enregistrer la note',noNotes:'Aucune note pour le moment. Décrivez le vin aujourd’hui ; la prochaine bouteille racontera peut-être autre chose.',fromAtlas:'Depuis l’atlas',ownEntry:'Mon entrée',wine:'Vin',wineName:'Nom du vin',producer:'Domaine',region:'Région',collection:'Collection',photo:'Photo de la bouteille',photoBody:'Utilisez l’appareil ou choisissez une image. Elle sera réduite et enregistrée dans votre médiathèque cloud.',choosePhoto:'Choisir une photo',changePhoto:'Changer la photo',removePhoto:'Retirer la photo',preparing:'Préparation de la photo…',photoError:'Cette image n’a pas pu être préparée ou téléversée.',saveBottle:'Enregistrer en cave',nonVintage:'NM',bottleStudy:'Pourquoi les formes diffèrent',bottleStudyBody:'Épaules, poids du verre et résistance à la pression viennent de choix pratiques. La forme évoque une tradition, jamais une garantie de qualité.',latestNote:'Dernière note',light:'Léger',medium:'Moyen',full:'Plein',short:'Courte',persistent:'Persistante',clear:'Limpide',pale:'Pâle',deep:'Profonde',homeCellar:'Cave personnelle',addSuccess:'Bouteille ajoutée à votre cave.'},
  es:{eyebrow:'Colección personal',title:'Una bodega hecha de recuerdos',intro:'Guarda botellas, ventanas de consumo y detalles de compra junto a las notas sensoriales que hicieron memorable un vino.',add:'Añadir una botella',search:'Buscar vino, bodega, región o añada',all:'Todo',bottles:'botellas',wishlist:'lista de deseos',noted:'con notas',emptyTitle:'No hay botellas en esta vista',emptyBody:'Cambia el filtro o añade la primera botella a tu bodega.',owned:'En bodega',tasted:'Catado',finished:'Terminado',details:'Abrir ficha de botella',closeDetails:'Cerrar ficha botella',remove:'Eliminar',confirmRemove:'¿Eliminar definitivamente?',quantity:'Cantidad',location:'Lugar de guarda',vintage:'Añada',bottleSize:'Tamaño de botella',purchaseDate:'Fecha de compra',purchasePrice:'Precio de compra',currency:'Moneda',source:'Comprado en',drinkWindow:'Ventana de consumo',drinkFrom:'Desde',drinkUntil:'Hasta',occasion:'Ocasión o recuerdo',saveDetails:'Guardar detalles',saved:'Guardado',notes:'Notas de cata',addNote:'Añadir nota estructurada',appearance:'Aspecto',aromas:'Aromas',palate:'Boca',finish:'Final',reflection:'Conclusión y recuerdo',acidity:'Acidez',tannin:'Tanino',body:'Cuerpo',rating:'Valoración',saveNote:'Guardar nota de cata',noNotes:'Todavía no hay una nota. Describe el vino hoy; la próxima botella puede contar una historia distinta.',fromAtlas:'Desde el atlas',ownEntry:'Entrada propia',wine:'Vino',wineName:'Nombre del vino',producer:'Bodega',region:'Región',collection:'Colección',photo:'Foto de la botella',photoBody:'Usa la cámara o elige una imagen. Se reduce y se guarda en tu biblioteca multimedia en la nube.',choosePhoto:'Elegir foto',changePhoto:'Cambiar foto',removePhoto:'Quitar foto',preparing:'Preparando foto…',photoError:'No se pudo preparar o subir esta imagen.',saveBottle:'Guardar en bodega',nonVintage:'SN',bottleStudy:'Por qué cambian las formas',bottleStudyBody:'Hombros, peso del vidrio y resistencia a la presión nacieron de decisiones prácticas. La forma sugiere tradición, nunca garantiza calidad.',latestNote:'Última nota',light:'Ligero',medium:'Medio',full:'Pleno',short:'Corto',persistent:'Persistente',clear:'Limpio',pale:'Pálido',deep:'Profundo',homeCellar:'Bodega de casa',addSuccess:'Botella añadida a tu bodega.'},
}

const cellarUxCopy: Record<Locale, {
  ownedBottles:string; entries:string; notesLogged:string; sort:string; sortName:string; sortVintage:string; sortQuantity:string;
  noMatchesTitle:string; noMatchesBody:string; resetFilters:string; cancel:string; invalidWindow:string; invalidQuantity:string;
  cancelRemove:string; removeHelp:string; editPhoto:string; photoError:string; noRating:string; rate:string;
}> = {
  en:{ownedBottles:'bottles in cellar',entries:'wine entries',notesLogged:'tasting notes',sort:'Sort by',sortName:'Name',sortVintage:'Vintage',sortQuantity:'Quantity',noMatchesTitle:'No bottles match your search',noMatchesBody:'Try another wine, producer, region, vintage or storage location.',resetFilters:'Clear search and filters',cancel:'Cancel',invalidWindow:'The drinking window end year must be the same as or later than its start year.',invalidQuantity:'Enter a whole number of bottles (zero or more).',cancelRemove:'Keep this bottle',removeHelp:'Removing a bottle also removes its saved photo. This cannot be undone.',editPhoto:'Update bottle photo',photoError:'This photo could not be prepared or uploaded.',noRating:'Not rated',rate:'Rate'},
  de:{ownedBottles:'Flaschen im Keller',entries:'Weineinträge',notesLogged:'Verkostungsnotizen',sort:'Sortieren nach',sortName:'Name',sortVintage:'Jahrgang',sortQuantity:'Anzahl',noMatchesTitle:'Keine Flaschen entsprechen der Suche',noMatchesBody:'Versuche einen anderen Wein, ein Weingut, eine Region, einen Jahrgang oder Lagerort.',resetFilters:'Suche und Filter zurücksetzen',cancel:'Abbrechen',invalidWindow:'Das Endjahr des Trinkfensters muss dem Startjahr entsprechen oder später liegen.',invalidQuantity:'Gib eine ganze Flaschenzahl von null oder höher ein.',cancelRemove:'Flasche behalten',removeHelp:'Beim Entfernen wird auch das gespeicherte Foto gelöscht. Dies kann nicht rückgängig gemacht werden.',editPhoto:'Flaschenfoto ändern',photoError:'Dieses Foto konnte nicht vorbereitet oder hochgeladen werden.',noRating:'Ohne Bewertung',rate:'Bewerten'},
  fr:{ownedBottles:'bouteilles en cave',entries:'fiches de vin',notesLogged:'notes de dégustation',sort:'Trier par',sortName:'Nom',sortVintage:'Millésime',sortQuantity:'Quantité',noMatchesTitle:'Aucune bouteille ne correspond',noMatchesBody:'Essayez un autre vin, domaine, région, millésime ou lieu de stockage.',resetFilters:'Effacer la recherche et les filtres',cancel:'Annuler',invalidWindow:'La fin de la fenêtre doit être égale ou postérieure à son début.',invalidQuantity:'Indiquez un nombre entier de bouteilles, égal ou supérieur à zéro.',cancelRemove:'Garder cette bouteille',removeHelp:'Le retrait supprimera aussi la photo enregistrée. Cette action est définitive.',editPhoto:'Modifier la photo',photoError:'Cette photo n’a pas pu être préparée ou téléversée.',noRating:'Sans note',rate:'Noter'},
  es:{ownedBottles:'botellas en bodega',entries:'fichas de vino',notesLogged:'notas de cata',sort:'Ordenar por',sortName:'Nombre',sortVintage:'Añada',sortQuantity:'Cantidad',noMatchesTitle:'Ninguna botella coincide con la búsqueda',noMatchesBody:'Prueba con otro vino, bodega, región, añada o lugar de guarda.',resetFilters:'Borrar búsqueda y filtros',cancel:'Cancelar',invalidWindow:'El final de la ventana debe ser igual o posterior al año de inicio.',invalidQuantity:'Introduce un número entero de botellas igual o superior a cero.',cancelRemove:'Conservar esta botella',removeHelp:'Al eliminarla también se borrará la foto guardada. No se puede deshacer.',editPhoto:'Cambiar foto de botella',photoError:'No se pudo preparar o subir esta foto.',noRating:'Sin valoración',rate:'Valorar'}
}

const lastBottleCopy:Record<Locale,{prompt:string;confirm:string;cancel:string}>={
  en:{prompt:'This is your last bottle in the cellar. Would you like to open it and record the tasting?',confirm:'Open last bottle',cancel:'Keep it for now'},
  de:{prompt:'Das ist deine letzte Flasche im Keller. Möchtest du sie öffnen und die Verkostung festhalten?',confirm:'Letzte Flasche öffnen',cancel:'Vorerst behalten'},
  fr:{prompt:'C’est votre dernière bouteille en cave. Voulez-vous l’ouvrir et consigner la dégustation ?',confirm:'Ouvrir la dernière bouteille',cancel:'La garder pour le moment'},
  es:{prompt:'Es tu última botella en la bodega. ¿Quieres abrirla y guardar la nota de cata?',confirm:'Abrir la última botella',cancel:'Conservarla por ahora'}
}

const moreCopy:Record<Locale,string>={en:'more',de:'weitere',fr:'autres',es:'más'}

const stateOrder: CellarState[]=['owned','wishlist','tasted','finished']

const intelligenceCopy:Record<Locale,{
  eyebrow:string;title:string;body:string;drinkNow:string;drinkNowBody:string;later:string;overdue:string;ready:string;uncertain:string;
  collection:string;regions:string;varieties:string;learn:string;learnBody:string;open:string;opened:string;lastBottle:string;knowledge:string;
  wine:string;place:string;grapes:string;guide:string;empty:string;history:string;historyBody:string
}>={
  en:{eyebrow:'Cellar intelligence',title:'What should the next bottle teach you?',body:'Drinking windows are estimates, not expiry dates. Use them with storage history, bottle condition and your own notes.',drinkNow:'Drinking compass',drinkNowBody:'Bottles whose recorded window includes this year, or has just passed.',later:'Hold',overdue:'Revisit',ready:'In window',uncertain:'No window',collection:'Collection breadth',regions:'regions',varieties:'varieties',learn:'Learn from your bottles',learnBody:'These guides connect directly to places and grapes already in your cellar.',open:'Open one bottle',opened:'Bottle opening recorded',lastBottle:'The last bottle moved to your tasting history.',knowledge:'Follow this bottle',wine:'Wine record',place:'Place',grapes:'Varieties',guide:'Related guide',empty:'Add a drinking window to a bottle to build your service queue.',history:'Bottle history',historyBody:'Every opening is retained, even after the final bottle leaves the rack.'},
  de:{eyebrow:'Kellerkompass',title:'Was soll dir die nächste Flasche beibringen?',body:'Trinkfenster sind Schätzungen, keine Verfallsdaten. Verbinde sie mit Lagerung, Flaschenzustand und deinen eigenen Notizen.',drinkNow:'Trinkkompass',drinkNowBody:'Flaschen, deren erfasstes Trinkfenster dieses Jahr einschließt oder gerade überschritten wurde.',later:'Lagern',overdue:'Erneut prüfen',ready:'Im Trinkfenster',uncertain:'Ohne Trinkfenster',collection:'Breite der Sammlung',regions:'Regionen',varieties:'Rebsorten',learn:'Mit eigenen Flaschen lernen',learnBody:'Diese Guides führen direkt zu Orten und Rebsorten aus deinem Keller.',open:'Eine Flasche öffnen',opened:'Flaschenöffnung erfasst',lastBottle:'Die letzte Flasche wurde in deine Verkostungshistorie verschoben.',knowledge:'Diese Flasche erkunden',wine:'Weinprofil',place:'Herkunft',grapes:'Rebsorten',guide:'Passender Guide',empty:'Ergänze bei einer Flasche ein Trinkfenster, um deine Serviceliste aufzubauen.',history:'Flaschenhistorie',historyBody:'Jede Öffnung bleibt erhalten, auch wenn die letzte Flasche das Regal verlässt.'},
  fr:{eyebrow:'Boussole de cave',title:'Que peut vous apprendre la prochaine bouteille ?',body:'Une fenêtre de dégustation reste une estimation. Croisez-la avec la conservation, l’état de la bouteille et vos propres notes.',drinkNow:'Boussole de dégustation',drinkNowBody:'Bouteilles dont la fenêtre inclut cette année ou vient de se terminer.',later:'Attendre',overdue:'Revoir',ready:'Dans la fenêtre',uncertain:'Sans fenêtre',collection:'Diversité de la cave',regions:'régions',varieties:'cépages',learn:'Apprendre avec vos bouteilles',learnBody:'Ces guides relient directement les lieux et cépages déjà présents dans votre cave.',open:'Ouvrir une bouteille',opened:'Ouverture enregistrée',lastBottle:'La dernière bouteille a rejoint votre historique de dégustation.',knowledge:'Explorer cette bouteille',wine:'Fiche du vin',place:'Origine',grapes:'Cépages',guide:'Guide associé',empty:'Ajoutez une fenêtre de dégustation pour constituer votre liste de service.',history:'Historique des bouteilles',historyBody:'Chaque ouverture reste conservée, même après la dernière bouteille.'},
  es:{eyebrow:'Brújula de bodega',title:'¿Qué puede enseñarte la próxima botella?',body:'Las ventanas de consumo son estimaciones. Combínalas con la conservación, el estado de la botella y tus propias notas.',drinkNow:'Brújula de consumo',drinkNowBody:'Botellas cuya ventana incluye este año o acaba de terminar.',later:'Guardar',overdue:'Revisar',ready:'En su ventana',uncertain:'Sin ventana',collection:'Diversidad de la colección',regions:'regiones',varieties:'variedades',learn:'Aprender con tus botellas',learnBody:'Estas guías conectan directamente con lugares y variedades de tu bodega.',open:'Abrir una botella',opened:'Apertura registrada',lastBottle:'La última botella pasó a tu historial de cata.',knowledge:'Explorar esta botella',wine:'Ficha del vino',place:'Origen',grapes:'Variedades',guide:'Guía relacionada',empty:'Añade una ventana de consumo para crear tu lista de servicio.',history:'Historial de botellas',historyBody:'Cada apertura se conserva, incluso después de la última botella.'}
}

function BottlePortrait({item}:{item:CellarItem}){
  const wine=wines.find(entry=>entry.id===item.wineId)
  const vintage=item.vintage??wine?.vintage
  return <div className={`bottle-portrait style-${wine?.style??'red'}`}>
    {item.imageDataUrl?<img src={item.imageDataUrl} alt=""/>:<div className="bottle-object" aria-hidden="true"><i/><b>{vintage&&<span>{vintage}</span>}<em>{(item.customName||wine?.name||'Vine Atlas').slice(0,18)}</em></b></div>}
  </div>
}

export function CellarExperience(){
  const {locale}=useLocale(); const c=cellarCopy[locale]; const ui=useUiCopy()
  const ux=cellarUxCopy[locale]
  const [items,setItems]=useState<CellarItem[]>(()=>repository.cellar.all())
  const [filter,setFilter]=useState<'all'|CellarState>('all'); const [query,setQuery]=useState(''); const [sort,setSort]=useState<'name'|'vintage'|'quantity'>('name')
  const [expanded,setExpanded]=useState<string>(); const [deleting,setDeleting]=useState<string>(); const [openingLast,setOpeningLast]=useState<string>(); const [addOpen,setAddOpen]=useState(false); const [toast,setToast]=useState('')
  function persist(next:CellarItem[]){setItems(next);repository.cellar.save(next)}
  const ownedBottleCount=items.reduce((sum,item)=>sum+(item.state==='owned'?Math.max(0,item.quantity):0),0)
  const noteCount=items.reduce((sum,item)=>sum+(item.notes?.length??0),0)
  const filtered=useMemo(()=>{
    const needle=query.trim().toLocaleLowerCase(locale)
    const matches=items.filter(item=>{
      if(filter!=='all'&&item.state!==filter)return false
      const wine=wines.find(entry=>entry.id===item.wineId),producer=wine?producers.find(entry=>entry.id===wine.producerId):undefined,region=wine?regions.find(entry=>entry.id===wine.regionId):undefined
      const searchable=[item.customName,wine?.name,item.producer,producer?.name,item.region,region?.name,region?regionName(region,locale):'',item.vintage,wine?.vintage,item.location].filter(Boolean).join(' ').toLocaleLowerCase(locale)
      return !needle||searchable.includes(needle)
    })
    const collator=new Intl.Collator(locale,{sensitivity:'base',numeric:true})
    return matches.sort((a,b)=>{
      const nameA=a.customName??wines.find(wine=>wine.id===a.wineId)?.name??''
      const nameB=b.customName??wines.find(wine=>wine.id===b.wineId)?.name??''
      if(sort==='quantity')return b.quantity-a.quantity||collator.compare(nameA,nameB)
      if(sort==='vintage')return (b.vintage??wines.find(wine=>wine.id===b.wineId)?.vintage??0)-(a.vintage??wines.find(wine=>wine.id===a.wineId)?.vintage??0)||collator.compare(nameA,nameB)
      return collator.compare(nameA,nameB)
    })
  },[items,filter,query,sort,locale])
  function updateItem(id:string,patch:Partial<CellarItem>){persist(items.map(item=>item.id===id?{...item,...patch}:item))}
  function recordOpening(item:CellarItem){
    if(item.quantity<=0)return
    const openedAt=[...(item.openedAt??[]),new Date().toISOString()]
    const last=item.quantity<=1
    updateItem(item.id,{quantity:Math.max(0,item.quantity-1),state:last?'finished':item.state,lastOpenedAt:openedAt.at(-1),openedAt})
    setOpeningLast(undefined)
    setToast(`${intelligenceCopy[locale].opened}${last?` · ${intelligenceCopy[locale].lastBottle}`:''}`)
    window.setTimeout(()=>setToast(''),3600)
  }
  function openBottle(item:CellarItem){
    if(item.quantity<=0)return
    if(item.state==='owned'&&item.quantity===1){
      setOpeningLast(item.id)
      if(!filtered.some(candidate=>candidate.id===item.id)){setQuery('');setFilter('all')}
      setExpanded(item.id)
      window.requestAnimationFrame(()=>document.getElementById(`cellar-record-${item.id}`)?.scrollIntoView({behavior:'smooth',block:'center'}))
      return
    }
    recordOpening(item)
  }
  function confirmOpenBottle(item:CellarItem){if(openingLast===item.id)recordOpening(item)}
  function removeItem(id:string){if(deleting!==id){setDeleting(id);return}const item=items.find(candidate=>candidate.id===id);persist(items.filter(candidate=>candidate.id!==id));if(item?.mediaAssetId)void deleteBottlePhoto(item.mediaAssetId).catch(()=>{});setDeleting(undefined);setExpanded(undefined);setToast('')}
  return <main className="page cellar-experience">
    <header className="cellar-experience-hero">
      <div><span className="eyebrow">{c.eyebrow}</span><h1>{c.title}</h1><button className="primary-button" onClick={()=>setAddOpen(true)}><Plus/>{c.add}</button></div>
      <p>{c.intro}</p>
    </header>
    <section className="cellar-metrics">
      <article><Wine/><strong>{ownedBottleCount}</strong><span>{ux.ownedBottles}</span></article>
      <article><Archive/><strong>{items.length}</strong><span>{ux.entries}</span></article>
      <article><NotebookPen/><strong>{noteCount}</strong><span>{ux.notesLogged}</span></article>
    </section>
    <div className="cellar-commandbar">
      <label className="search-field"><Search aria-hidden="true"/><input aria-label={c.search} value={query} onChange={event=>setQuery(event.target.value)} placeholder={c.search}/></label>
      <div className="cellar-state-filters" role="group" aria-label={c.collection}><SlidersHorizontal aria-hidden="true"/>{(['all',...stateOrder] as const).map(value=><button type="button" key={value} className={filter===value?'active':''} aria-pressed={filter===value} onClick={()=>{setFilter(value);setDeleting(undefined);setOpeningLast(undefined)}}>{value==='all'?c.all:value==='wishlist'?c.wishlist:c[value]}</button>)}</div>
      <label className="cellar-sort"><span>{ux.sort}</span><select aria-label={ux.sort} value={sort} onChange={event=>setSort(event.target.value as typeof sort)}><option value="name">{ux.sortName}</option><option value="vintage">{ux.sortVintage}</option><option value="quantity">{ux.sortQuantity}</option></select></label>
    </div>
    {toast&&<div className="cellar-toast" role="status" aria-live="polite"><Check/>{toast}<button type="button" aria-label={ui.close} onClick={()=>setToast('')}><X/></button></div>}
    {items.length===0?<section className="cellar-empty"><Archive/><h2>{c.emptyTitle}</h2><p>{c.emptyBody}</p><button className="primary-button ink" onClick={()=>setAddOpen(true)}>{c.add}</button></section>:filtered.length?<section className="cellar-collection-grid">{filtered.map(item=>{
      const wine=wines.find(entry=>entry.id===item.wineId),producer=wine?producers.find(entry=>entry.id===wine.producerId):undefined,region=wine?regions.find(entry=>entry.id===wine.regionId):undefined
      const latest=item.notes?.at(-1)
      return <article className={expanded===item.id?'cellar-record expanded':'cellar-record'} key={item.id}>
        <BottlePortrait item={item}/>
        <div className="cellar-record-copy"><div className="record-kicker"><span>{item.state==='wishlist'?c.wishlist:c[item.state]}</span><em>{item.vintage??wine?.vintage??'—'}</em></div>
          <h2>{item.customName||wine?.name}</h2><p>{item.producer||producer?.name}</p>
          <div className="record-place"><MapPin/>{region?<Link to={`/regions/${region.id}`}>{regionName(region,locale)} · {countryLabel(region.country,locale)}</Link>:item.region}</div>
          {item.location&&<p className="cellar-location">{item.location}</p>}
          {latest&&<div className="latest-note"><span>{c.latestNote}</span>{latest.rating>0?<strong>{'★'.repeat(latest.rating)}{'☆'.repeat(5-latest.rating)}</strong>:<strong>{ux.noRating}</strong>}<p>{latest.reflection||latest.palate}</p></div>}
          <div className="record-actions"><div className="cellar-quantity-control"><button type="button" aria-label={`${c.quantity}: −`} disabled={item.quantity===0} onClick={()=>updateItem(item.id,{quantity:Math.max(0,item.quantity-1)})}><Minus/></button><output aria-label={c.quantity}>{item.quantity}</output><button type="button" aria-label={`${c.quantity}: +`} onClick={()=>updateItem(item.id,{quantity:item.quantity+1,...(item.state==='finished'?{state:'owned' as const}:{})})}><Plus/></button></div>
            <button type="button" className="text-button" aria-expanded={expanded===item.id} aria-controls={`cellar-record-${item.id}`} onClick={()=>{setDeleting(undefined);setOpeningLast(undefined);setExpanded(expanded===item.id?undefined:item.id)}}>{expanded===item.id?<><ChevronUp/>{c.closeDetails}</>:<><ChevronDown/>{c.details}</>}</button>
          </div>
        </div>
        {expanded===item.id&&<div id={`cellar-record-${item.id}`}><BottleRecord item={item} c={c} locale={locale} onUpdate={patch=>updateItem(item.id,patch)} onOpen={()=>openBottle(item)} onConfirmOpen={()=>confirmOpenBottle(item)} onCancelOpen={()=>setOpeningLast(undefined)} confirmOpenLast={openingLast===item.id} onRemove={()=>removeItem(item.id)} onCancelRemove={()=>setDeleting(undefined)} confirmRemove={deleting===item.id}/></div>}
      </article>})}</section>:<section className="cellar-empty no-matches"><Search/><h2>{ux.noMatchesTitle}</h2><p>{ux.noMatchesBody}</p><button type="button" className="secondary-button" onClick={()=>{setQuery('');setFilter('all')}}>{ux.resetFilters}</button></section>}
    {items.length>0&&<CellarIntelligence items={items} locale={locale} onOpen={openBottle}/>}
    {addOpen&&<AddBottleSheet c={c} locale={locale} closeLabel={ui.close} onClose={()=>setAddOpen(false)} onSave={item=>{persist([...items,item]);setAddOpen(false);setToast(c.addSuccess);window.setTimeout(()=>setToast(''),3600)}}/>}
  </main>
}

function CellarIntelligence({items,locale,onOpen}:{items:CellarItem[];locale:Locale;onOpen:(item:CellarItem)=>void}){
  const c=intelligenceCopy[locale],year=new Date().getFullYear()
  const owned=items.filter(item=>item.state==='owned'&&item.quantity>0)
  const queue=owned.filter(item=>item.drinkFrom||item.drinkUntil).sort((a,b)=>(a.drinkUntil??9999)-(b.drinkUntil??9999)).slice(0,3)
  const linked=owned.map(item=>wines.find(wine=>wine.id===item.wineId)).filter((wine):wine is NonNullable<typeof wine>=>Boolean(wine))
  const regionIds=new Set(linked.map(wine=>wine.regionId)),grapeIds=new Set(linked.flatMap(wine=>wine.grapeIds))
  const guides=articles.filter(article=>article.relatedRegionIds.some(id=>regionIds.has(id))||article.relatedGrapeIds.some(id=>grapeIds.has(id))).slice(0,3)
  const status=(item:CellarItem)=>item.drinkUntil&&item.drinkUntil<year?c.overdue:item.drinkFrom&&item.drinkFrom>year?c.later:c.ready
  return <section className="cellar-intelligence">
    <header><div><span className="eyebrow">{c.eyebrow}</span><h2>{c.title}</h2><p>{c.body}</p></div><Compass/></header>
    <div className="cellar-intelligence-grid">
      <article className="drinking-compass"><div className="intelligence-heading"><span>{c.drinkNow}</span><p>{c.drinkNowBody}</p></div>
        {queue.length?<div className="drink-queue">{queue.map(item=>{const wine=wines.find(entry=>entry.id===item.wineId);return <div key={item.id}><div><span>{status(item)}</span><strong>{wine?.name??item.customName}</strong><small>{item.vintage??wine?.vintage??'—'} · {item.drinkFrom??'—'}–{item.drinkUntil??'—'}</small></div><button type="button" onClick={()=>onOpen(item)}><WineOff/>{c.open}</button></div>})}</div>:<p className="intelligence-empty">{c.empty}</p>}
      </article>
      <article className="collection-breadth"><span>{c.collection}</span><div><strong>{regionIds.size}</strong><small>{c.regions}</small></div><div><strong>{grapeIds.size}</strong><small>{c.varieties}</small></div><p><Clock3/>{c.historyBody}</p></article>
    <article className="cellar-learning"><div className="intelligence-heading"><span>{c.learn}</span><p>{c.learnBody}</p></div><div>{guides.map(guide=><Link key={guide.id} to={`/learn/guides/${guide.id}`}><BookOpen/><span><strong>{articleContent(guide,locale).title}</strong><small>{guide.minutes} min</small></span><ArrowRight/></Link>)}</div></article>
    </div>
  </section>
}

function BottleRecord({item,c,locale,onUpdate,onOpen,onConfirmOpen,onCancelOpen,confirmOpenLast,onRemove,onCancelRemove,confirmRemove}:{item:CellarItem;c:typeof cellarCopy.en;locale:Locale;onUpdate:(patch:Partial<CellarItem>)=>void;onOpen:()=>void;onConfirmOpen:()=>void;onCancelOpen:()=>void;confirmOpenLast:boolean;onRemove:()=>void;onCancelRemove:()=>void;confirmRemove:boolean}){
  const wine=wines.find(entry=>entry.id===item.wineId)
  const producer=wine?producers.find(entry=>entry.id===wine.producerId):undefined
  const region=wine?regions.find(entry=>entry.id===wine.regionId):undefined
  const relatedGuide=wine?articles.find(article=>article.relatedRegionIds.includes(wine.regionId)||article.relatedGrapeIds.some(id=>wine.grapeIds.includes(id))):undefined
  const intelligence=intelligenceCopy[locale]
  const ux=cellarUxCopy[locale]
  const lastCopy=lastBottleCopy[locale]
  const [saved,setSaved]=useState(false); const [aromaIds,setAromaIds]=useState<string[]>([])
  const [note,setNote]=useState({appearance:c.clear,palate:'',finish:'',reflection:'',acidity:3,tannin:wine?.style==='red'?3:1,body:3,rating:0})
  const [metaError,setMetaError]=useState('');const [photoError,setPhotoError]=useState('');const [preparingPhoto,setPreparingPhoto]=useState(false)
  const availableAromas=wine?aromas.filter(aroma=>wine.aromaIds.includes(aroma.id)):aromas.slice(0,20)
  async function choosePhoto(file?:File){if(!file)return;setPreparingPhoto(true);setPhotoError('');try{const prepared=await prepareBottlePhoto(file);const uploaded=await uploadBottlePhoto(prepared);onUpdate({imageDataUrl:uploaded.url,mediaAssetId:uploaded.assetId});if(item.mediaAssetId&&item.mediaAssetId!==uploaded.assetId)void deleteBottlePhoto(item.mediaAssetId).catch(()=>{})}catch{setPhotoError(ux.photoError)}finally{setPreparingPhoto(false)}}
  function removePhoto(){const previous=item.mediaAssetId;onUpdate({imageDataUrl:undefined,mediaAssetId:undefined});if(previous)void deleteBottlePhoto(previous).catch(()=>{})}
  function saveMeta(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const quantity=Number(data.get('quantity'));const fromRaw=String(data.get('drinkFrom')||'').trim();const untilRaw=String(data.get('drinkUntil')||'').trim();const drinkFrom=fromRaw?Number(fromRaw):undefined;const drinkUntil=untilRaw?Number(untilRaw):undefined;if(!Number.isInteger(quantity)||quantity<0){setMetaError(ux.invalidQuantity);return}if(drinkFrom!==undefined&&drinkUntil!==undefined&&drinkFrom>drinkUntil){setMetaError(ux.invalidWindow);return}setMetaError('');onUpdate({customName:String(data.get('customName')||'').trim()||undefined,producer:String(data.get('producer')||'').trim()||undefined,region:String(data.get('region')||'').trim()||undefined,state:String(data.get('state')) as CellarState,quantity,vintage:Number(data.get('vintage'))||undefined,bottleSizeMl:Number(data.get('bottleSizeMl'))||750,location:String(data.get('location')||''),purchaseDate:String(data.get('purchaseDate')||''),purchasePrice:Number(data.get('purchasePrice'))||undefined,currency:String(data.get('currency')||'EUR') as CellarItem['currency'],purchaseSource:String(data.get('purchaseSource')||''),drinkFrom,drinkUntil,occasion:String(data.get('occasion')||'')});setSaved(true)}
  function saveNote(){const entry:CellarTastingNote={id:crypto.randomUUID(),...note,aromaIds,createdAt:new Date().toISOString()};onUpdate({notes:[...(item.notes??[]),entry],rating:entry.rating,state:item.state==='wishlist'?'tasted':item.state});setAromaIds([]);setNote({...note,palate:'',finish:'',reflection:''})}
  return <div className="bottle-record-panel">
    <form className="bottle-metadata-form" onSubmit={saveMeta}><div className="panel-heading"><div><span className="eyebrow">{c.details}</span><h3>{c.drinkWindow}</h3></div><Clock3/></div>
      <div className="metadata-grid"><label>{c.wineName}<input name="customName" defaultValue={item.customName??wine?.name??''} required={!wine}/></label><label>{c.producer}<input name="producer" defaultValue={item.producer??producer?.name??''}/></label><label>{c.region}<input name="region" defaultValue={item.region??region?.name??''}/></label><label>{c.collection}<select name="state" defaultValue={item.state}><option value="owned">{c.owned}</option><option value="wishlist">{c.wishlist}</option><option value="tasted">{c.tasted}</option><option value="finished">{c.finished}</option></select></label><label>{c.quantity}<input name="quantity" type="number" min="0" step="1" defaultValue={item.quantity}/></label></div>
      <div className="bottle-photo-field"><div className={item.imageDataUrl?'photo-preview has-photo':'photo-preview'}>{item.imageDataUrl?<img src={item.imageDataUrl} alt=""/>:<Camera aria-hidden="true"/>}</div><div><strong>{c.photo}</strong><p>{ux.editPhoto}</p><label className="secondary-button"><ImagePlus/>{preparingPhoto?c.preparing:item.imageDataUrl?c.changePhoto:c.choosePhoto}<input type="file" accept="image/*" capture="environment" onChange={event=>choosePhoto(event.target.files?.[0])}/></label>{item.imageDataUrl&&<button type="button" className="text-button" onClick={removePhoto}>{c.removePhoto}</button>}{photoError&&<span className="form-error" role="alert">{photoError}</span>}</div></div>
      <div className="metadata-grid"><label>{c.vintage}<input name="vintage" type="number" min="1800" max="2100" step="1" defaultValue={item.vintage??wine?.vintage??''}/></label><label>{c.bottleSize}<select name="bottleSizeMl" defaultValue={item.bottleSizeMl??750}><option value="375">375 ml</option><option value="750">750 ml</option><option value="1500">1.5 l</option><option value="3000">3 l</option></select></label><label>{c.location}<input name="location" defaultValue={item.location}/></label><label>{c.purchaseDate}<input name="purchaseDate" type="date" defaultValue={item.purchaseDate}/></label><label>{c.purchasePrice}<input name="purchasePrice" type="number" min="0" step="0.01" defaultValue={item.purchasePrice}/></label><label>{c.currency}<select name="currency" defaultValue={item.currency??'EUR'}>{['EUR','USD','GBP','CHF'].map(value=><option key={value}>{value}</option>)}</select></label><label>{c.source}<input name="purchaseSource" defaultValue={item.purchaseSource}/></label><label>{c.drinkFrom}<input name="drinkFrom" type="number" min="1900" max="2200" step="1" defaultValue={item.drinkFrom}/></label><label>{c.drinkUntil}<input name="drinkUntil" type="number" min="1900" max="2200" step="1" defaultValue={item.drinkUntil}/></label><label className="wide">{c.occasion}<textarea name="occasion" defaultValue={item.occasion}/></label></div>
      {metaError&&<span className="form-error" role="alert">{metaError}</span>}
      <button className="secondary-button">{saved?<><Check/>{c.saved}</>:c.saveDetails}</button>
    </form>
    {wine&&<section className="bottle-knowledge-trail"><div className="panel-heading"><div><span className="eyebrow">{intelligence.knowledge}</span><h3>{wine.name}</h3></div><BookOpen/></div><div>
      <Link to={`/wines/${wine.id}`}><Wine/><span><small>{intelligence.wine}</small><strong>{wine.name}</strong></span><ArrowRight/></Link>
      {region&&<Link to={`/regions/${region.id}`}><MapPin/><span><small>{intelligence.place}</small><strong>{regionName(region,locale)}</strong></span><ArrowRight/></Link>}
      {wine.grapeIds.slice(0,2).map(id=>{const grape=grapes.find(entry=>entry.id===id);return grape?<Link to={`/grapes/${grape.id}`} key={id}><Grape/><span><small>{intelligence.grapes}</small><strong>{grape.name}</strong></span><ArrowRight/></Link>:null})}
      {producer&&<Link to={`/wineries/${producer.id}`}><Archive/><span><small>{c.producer}</small><strong>{producer.name}</strong></span><ArrowRight/></Link>}
      {relatedGuide&&<Link to={`/learn/guides/${relatedGuide.id}`}><BookOpen/><span><small>{intelligence.guide}</small><strong>{articleContent(relatedGuide,locale).title}</strong></span><ArrowRight/></Link>}
    </div></section>}
    <section className="cellar-note-studio"><div className="panel-heading"><div><span className="eyebrow">{c.notes}</span><h3>{c.addNote}</h3></div><NotebookPen/></div>
      <label>{c.appearance}<select value={note.appearance} onChange={event=>setNote({...note,appearance:event.target.value})}><option>{c.clear}</option><option>{c.pale}</option><option>{c.deep}</option></select></label>
      <div><span className="field-label">{c.aromas}</span><div className="cellar-aroma-chips">{availableAromas.map(aroma=><button type="button" key={aroma.id} className={aromaIds.includes(aroma.id)?'active':''} onClick={()=>setAromaIds(values=>values.includes(aroma.id)?values.filter(id=>id!==aroma.id):[...values,aroma.id])}>{aromaContent(aroma,locale).name}</button>)}</div></div>
      <div className="note-sliders">{(['acidity','tannin','body'] as const).map(key=><label key={key}><span>{c[key]}</span><input type="range" min="1" max="5" value={note[key]} onChange={event=>setNote({...note,[key]:Number(event.target.value)})}/><b>{note[key]}/5</b></label>)}</div>
      <div className="note-text-grid"><label>{c.palate}<textarea value={note.palate} onChange={event=>setNote({...note,palate:event.target.value})}/></label><label>{c.finish}<textarea value={note.finish} onChange={event=>setNote({...note,finish:event.target.value})}/></label><label className="wide">{c.reflection}<textarea value={note.reflection} onChange={event=>setNote({...note,reflection:event.target.value})}/></label></div>
      <div className="rating-field"><span>{c.rating}</span><div role="group" aria-label={c.rating}>{[1,2,3,4,5].map(value=><button type="button" key={value} className={value<=note.rating?'active':''} aria-label={`${ux.rate} ${value} / 5`} aria-pressed={note.rating===value} onClick={()=>setNote({...note,rating:value})}>★</button>)}</div></div>
      <button type="button" className="primary-button" onClick={saveNote}><NotebookPen/>{c.saveNote}</button>
      <div className="note-history">{item.notes?.length?item.notes.slice().reverse().map(entry=><article key={entry.id}><header><time>{new Intl.DateTimeFormat(locale,{dateStyle:'medium'}).format(new Date(entry.createdAt))}</time><strong>{entry.rating>0?'★'.repeat(entry.rating)+'☆'.repeat(5-entry.rating):ux.noRating}</strong></header><div>{entry.aromaIds.map(id=>{const aroma=aromas.find(value=>value.id===id);return aroma?<span key={id}>{aromaContent(aroma,locale).name}</span>:null})}</div><p>{entry.palate}</p><small>{entry.finish}</small><blockquote>{entry.reflection}</blockquote></article>):<p>{c.noNotes}</p>}</div>
    </section>
    {item.quantity>0&&<button type="button" className="open-bottle-button" disabled={confirmOpenLast} onClick={onOpen}><WineOff/><span><strong>{intelligence.open}</strong><small>{intelligence.historyBody}</small></span></button>}
    {confirmOpenLast&&<div className="last-bottle-confirm" role="group" aria-label={lastCopy.prompt}><p role="alert">{lastCopy.prompt}</p><div><button type="button" className="primary-button" onClick={onConfirmOpen}>{lastCopy.confirm}</button><button type="button" className="secondary-button" onClick={onCancelOpen}>{lastCopy.cancel}</button></div></div>}
    {confirmRemove&&<p className="remove-confirm-help" role="alert">{ux.removeHelp}</p>}
    <div className="cellar-remove-actions"><button type="button" className={confirmRemove?'danger-button confirm':'danger-button'} onClick={onRemove}><Trash2/>{confirmRemove?c.confirmRemove:c.remove}</button>{confirmRemove&&<button type="button" className="secondary-button" onClick={onCancelRemove}>{ux.cancelRemove}</button>}</div>
  </div>
}

function AddBottleSheet({c,locale,closeLabel,onClose,onSave}:{c:typeof cellarCopy.en;locale:Locale;closeLabel:string;onClose:()=>void;onSave:(item:CellarItem)=>void}){
  const ux=cellarUxCopy[locale]
  const [catalogue,setCatalogue]=useState(true);const [wineId,setWineId]=useState(wines[0].id);const [catalogQuery,setCatalogQuery]=useState('');const [state,setState]=useState<CellarState>('owned');const [imageDataUrl,setImageDataUrl]=useState<string>();const [mediaAssetId,setMediaAssetId]=useState<string>();const [preparing,setPreparing]=useState(false);const [error,setError]=useState('');const [formError,setFormError]=useState('')
  const dialogRef=useRef<HTMLFormElement>(null);const closeRef=useRef<()=>void>(()=>{})
  const matchingWines=useMemo(()=>{const query=catalogQuery.trim().toLocaleLowerCase();if(!query)return wines;return wines.filter(wine=>{const producer=producers.find(item=>item.id===wine.producerId),region=regions.find(item=>item.id===wine.regionId),varieties=wine.grapeIds.map(id=>grapes.find(item=>item.id===id)?.name).filter(Boolean).join(' ');return `${wine.name} ${producer?.name??''} ${region?.name??''} ${varieties} ${wine.vintage??''}`.toLocaleLowerCase().includes(query)})},[catalogQuery])
  const selectedWine=wines.find(wine=>wine.id===wineId)
  async function chooseImage(file?:File){if(!file)return;setPreparing(true);setError('');try{const prepared=await prepareBottlePhoto(file);setImageDataUrl(prepared);const uploaded=await uploadBottlePhoto(prepared);if(mediaAssetId)void deleteBottlePhoto(mediaAssetId).catch(()=>{});setImageDataUrl(uploaded.url);setMediaAssetId(uploaded.assetId)}catch{setImageDataUrl(undefined);setMediaAssetId(undefined);setError(c.photoError)}finally{setPreparing(false)}}
  function removePreparedPhoto(){if(mediaAssetId)void deleteBottlePhoto(mediaAssetId).catch(()=>{});setImageDataUrl(undefined);setMediaAssetId(undefined)}
  function close(){if(mediaAssetId)void deleteBottlePhoto(mediaAssetId).catch(()=>{});onClose()}
  closeRef.current=close
  useEffect(()=>{
    const opener=document.activeElement instanceof HTMLElement?document.activeElement:null
    const dialog=dialogRef.current
    const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('a[href],button:not(:disabled),input:not(:disabled):not([type="file"]),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')??[])
    const initialTarget=dialog?.querySelector<HTMLElement>('.cellar-wine-picker input')??focusable()[0]
    initialTarget?.focus()
    const previousOverflow=document.body.style.overflow
    const appRoot=document.getElementById('root'),previousInert=appRoot?.inert??false
    document.body.style.overflow='hidden'
    if(appRoot)appRoot.inert=true
    function handleKeyDown(event:KeyboardEvent){
      if(event.key==='Escape'){event.preventDefault();closeRef.current();return}
      if(event.key!=='Tab')return
      const targets=focusable(),first=targets[0],last=targets.at(-1)
      if(!first||!last){event.preventDefault();dialog?.focus();return}
      if(!dialog?.contains(document.activeElement)){event.preventDefault();(event.shiftKey?last:first).focus()}
      else if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}
      else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}
    }
    document.addEventListener('keydown',handleKeyDown)
    return()=>{document.removeEventListener('keydown',handleKeyDown);document.body.style.overflow=previousOverflow;if(appRoot)appRoot.inert=previousInert;opener?.focus()}
  },[])
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const quantity=Number(data.get('quantity'));const fromRaw=String(data.get('drinkFrom')||'').trim();const untilRaw=String(data.get('drinkUntil')||'').trim();const drinkFrom=fromRaw?Number(fromRaw):undefined;const drinkUntil=untilRaw?Number(untilRaw):undefined;if(!Number.isInteger(quantity)||quantity<1){setFormError(ux.invalidQuantity);return}if(drinkFrom!==undefined&&drinkUntil!==undefined&&drinkFrom>drinkUntil){setFormError(ux.invalidWindow);return}setFormError('');onSave({id:crypto.randomUUID(),...(catalogue?{wineId}:{customName:String(data.get('customName')||''),producer:String(data.get('producer')||''),region:String(data.get('region')||'')}),state,quantity,location:String(data.get('location')||c.homeCellar),vintage:Number(data.get('vintage'))||undefined,bottleSizeMl:Number(data.get('bottleSizeMl'))||750,purchaseDate:String(data.get('purchaseDate')||''),purchasePrice:Number(data.get('purchasePrice'))||undefined,currency:String(data.get('currency')||'EUR') as CellarItem['currency'],purchaseSource:String(data.get('purchaseSource')||''),drinkFrom,drinkUntil,occasion:String(data.get('occasion')||''),imageDataUrl,mediaAssetId,notes:[]})}
  return createPortal(<div className="modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)close()}}><form ref={dialogRef} className="sheet cellar-add-sheet" role="dialog" aria-modal="true" aria-labelledby="cellar-add-title" tabIndex={-1} onSubmit={submit}><button type="button" className="sheet-close" onClick={close} aria-label={closeLabel}><X aria-hidden="true"/></button><span className="eyebrow">{c.eyebrow}</span><h2 id="cellar-add-title">{c.add}</h2>
    <div className="bottle-photo-field"><div className={imageDataUrl?'photo-preview has-photo':'photo-preview'}>{imageDataUrl?<img src={imageDataUrl} alt={c.photo}/>:<Camera/>}</div><div><strong>{c.photo}</strong><p>{c.photoBody}</p><label className="secondary-button"><ImagePlus/>{preparing?c.preparing:imageDataUrl?c.changePhoto:c.choosePhoto}<input type="file" accept="image/*" capture="environment" onChange={event=>chooseImage(event.target.files?.[0])}/></label>{imageDataUrl&&<button type="button" className="text-button" onClick={removePreparedPhoto}>{c.removePhoto}</button>}{error&&<span className="form-error">{error}</span>}</div></div>
    <div className="segmented"><button type="button" className={catalogue?'active':''} onClick={()=>setCatalogue(true)}>{c.fromAtlas}</button><button type="button" className={!catalogue?'active':''} onClick={()=>setCatalogue(false)}>{c.ownEntry}</button></div>
    {catalogue?<section className="cellar-wine-picker"><label className="search-field"><Search aria-hidden="true"/><input aria-label={c.search} value={catalogQuery} onChange={event=>setCatalogQuery(event.target.value)} placeholder={c.search}/></label><div className="wine-picker-summary"><span>{matchingWines.length} / {wines.length}</span>{selectedWine&&<strong>{selectedWine.name}</strong>}</div><div className="wine-picker-list" role="listbox" aria-label={c.wine}>{matchingWines.slice(0,40).map(wine=>{const producer=producers.find(item=>item.id===wine.producerId),region=regions.find(item=>item.id===wine.regionId);return <button type="button" role="option" aria-selected={wine.id===wineId} className={wine.id===wineId?'active':''} onClick={()=>setWineId(wine.id)} value={wine.id} key={wine.id}><span><strong>{wine.name}</strong><small>{producer?.name}{region?` · ${regionName(region,locale)}`:''}</small></span>{wine.vintage&&<em>{wine.vintage}</em>}{wine.id===wineId&&<Check/>}</button>})}</div>{matchingWines.length>40&&<p className="wine-picker-help">{matchingWines.length-40} {c.more??moreCopy[locale]} · {c.search}</p>}</section>:<div className="metadata-grid"><label>{c.wineName}<input required name="customName"/></label><label>{c.producer}<input name="producer"/></label><label>{c.region}<input name="region"/></label></div>}
    <div className="metadata-grid"><label>{c.collection}<select value={state} onChange={event=>setState(event.target.value as CellarState)}><option value="owned">{c.owned}</option><option value="wishlist">{c.wishlist}</option><option value="tasted">{c.tasted}</option><option value="finished">{c.finished}</option></select></label><label>{c.quantity}<input name="quantity" type="number" min="1" step="1" defaultValue="1"/></label><label>{c.vintage}<input name="vintage" type="number" min="1800" max="2100" step="1"/></label><label>{c.bottleSize}<select name="bottleSizeMl" defaultValue="750"><option value="375">375 ml</option><option value="750">750 ml</option><option value="1500">1.5 l</option><option value="3000">3 l</option></select></label><label>{c.location}<input name="location" defaultValue={c.homeCellar}/></label><label>{c.purchaseDate}<input name="purchaseDate" type="date"/></label><label>{c.purchasePrice}<input name="purchasePrice" type="number" step="0.01" min="0"/></label><label>{c.currency}<select name="currency"><option>EUR</option><option>USD</option><option>GBP</option><option>CHF</option></select></label><label>{c.source}<input name="purchaseSource"/></label><label>{c.drinkFrom}<input name="drinkFrom" type="number" min="1900" max="2200" step="1"/></label><label>{c.drinkUntil}<input name="drinkUntil" type="number" min="1900" max="2200" step="1"/></label><label className="wide">{c.occasion}<textarea name="occasion"/></label></div>
    {formError&&<span className="form-error" role="alert">{formError}</span>}
    <button className="primary-button"><Wine/>{c.saveBottle}</button>
  </form></div>,document.body)
}
