import {useEffect,useMemo,useState,type CSSProperties} from 'react'
import {ArrowLeft,ArrowRight,Bookmark,BookOpen,Check,ChevronRight,Clock,Compass,Filter,FlaskConical,Grape,Layers3,Pause,Play,RotateCcw,Search,SlidersHorizontal,Sparkles,Target,Volume2,Wine} from 'lucide-react'
import {Link,useParams} from 'react-router-dom'
import {aromas,articles,grapes,producers,regions,wines} from './data/catalog'
import {repository} from './data/repository'
import {useLocale,type Locale} from './i18n'
import {articleContent} from './localizedContent'
import {curriculumSources,learningBlockById,learningModuleById,learningModules,schoolCopy,type LearningArchetype,type LearningBlock,type LearningBlockKind,type LearningLevel,type LearningModule,type LearningSchool} from './learningCurriculum'
import type {TastingChapter,TastingJourney} from './types'

const ui={
  en:{academy:'Field academy',title:'Learn by looking, changing and tasting',intro:'Eleven deeply authored masterclasses and twenty-five reference guides connect mechanism, place and sensory evidence. Choose a question, manipulate one variable, then carry the result into a real tasting.',search:'Search questions, topics or places',allSchools:'All schools',allLevels:'All levels',allFormats:'All formats',foundation:'Foundation',intermediate:'Intermediate',advanced:'Advanced',continue:'Continue learning',saved:'Saved modules',suggested:'Suggested tasting labs',modules:'modules',results:'results',empty:'No module matches these filters.',clear:'Clear filters',previous:'Previous',next:'Next',page:'Page',progress:'Current',min:'min',open:'Open field lesson',save:'Save module',savedAction:'Saved',outcomes:'What you will be able to do',useTasting:'Use in a tasting',addedTasting:'Added to your tasting',addBlock:'Add this block',lessonMap:'Lesson map',tableExperiment:'Take this to the table',complete:'Mark complete',completed:'Completed',sources:'Sources and limits',back:'Back to academy',observe:'Observe',manipulate:'Manipulate',explain:'Explain',test:'Test in the glass',keep:'Save / use',stage:'Stage',cool:'Cooler / lower',warm:'Warmer / higher',reveal:'Reveal reasoning',reset:'Reset',country:'Country',region:'Region',subregion:'Subregion',site:'Site',scale:'Scale',confidence:'Confidence',low:'Low',high:'High',choose:'Choose one answer',retry:'Try again',correct:'Good model: one variable, evidence and uncertainty.',notQuite:'Not yet. Isolate one variable and keep uncertainty visible.',sourceNote:'Primary and technical sources are provided for verification. They support mechanisms and definitions; they do not make every sensory outcome deterministic.',hostReveal:'Evidence check',selfPaced:'Self-paced',blocks:'blocks',duration:'Duration',format:'Format',continueBody:'Resume at the next unfinished block.',savedBody:'Keep a personal shelf of questions worth revisiting.',tastingBody:'Short practical modules that work well between two wines.',all:'All',journey:'Process journey',anatomy:'Annotated anatomy',sensory:'Sensory lab',map:'Map expedition',comparison:'A/B comparison',simulator:'Simulator',diagnostic:'Diagnostic case',pairing:'Pairing lab',guided:'Guided tasting','producer-case':'Decision chain',notFound:'This field lesson could not be found.',openAcademy:'Open the academy',addWhole:'Add complete lesson',blockAdded:'Learning step added',newJourney:'Learning table'},
  de:{academy:'Feldakademie',title:'Lernen durch Beobachten, Verändern und Verkosten',intro:'Elf vertiefte Masterclasses und fünfundzwanzig Nachschlage-Guides verbinden Mechanismus, Ort und sensorische Evidenz. Wähle eine Frage, verändere eine Variable und nimm das Ergebnis mit in eine echte Verkostung.',search:'Fragen, Themen oder Orte suchen',allSchools:'Alle Schulen',allLevels:'Alle Niveaus',allFormats:'Alle Formate',foundation:'Grundlage',intermediate:'Fortgeschritten',advanced:'Vertiefung',continue:'Weiterlernen',saved:'Gespeicherte Module',suggested:'Empfohlene Verkostungslabore',modules:'Module',results:'Ergebnisse',empty:'Kein Modul passt zu diesen Filtern.',clear:'Filter löschen',previous:'Zurück',next:'Weiter',page:'Seite',progress:'Aktuell',min:'Min.',open:'Feldlektion öffnen',save:'Modul speichern',savedAction:'Gespeichert',outcomes:'Das kannst du danach',useTasting:'In einer Verkostung nutzen',addedTasting:'Zur Verkostung hinzugefügt',addBlock:'Diesen Block hinzufügen',lessonMap:'Lektionskarte',tableExperiment:'Mit an den Tisch nehmen',complete:'Als abgeschlossen markieren',completed:'Abgeschlossen',sources:'Quellen und Grenzen',back:'Zur Akademie',observe:'Beobachten',manipulate:'Verändern',explain:'Erklären',test:'Im Glas prüfen',keep:'Speichern / einsetzen',stage:'Phase',cool:'Kühler / niedriger',warm:'Wärmer / höher',reveal:'Begründung zeigen',reset:'Zurücksetzen',country:'Land',region:'Region',subregion:'Teilregion',site:'Lage',scale:'Maßstab',confidence:'Sicherheit',low:'Niedrig',high:'Hoch',choose:'Wähle eine Antwort',retry:'Noch einmal',correct:'Gutes Modell: eine Variable, Evidenz und Unsicherheit.',notQuite:'Noch nicht. Isoliere eine Variable und halte Unsicherheit sichtbar.',sourceNote:'Primär- und Fachquellen dienen der Überprüfung. Sie stützen Mechanismen und Definitionen; sie machen sensorische Ergebnisse nicht deterministisch.',hostReveal:'Evidenz prüfen',selfPaced:'Selbstgesteuert',blocks:'Blöcke',duration:'Dauer',format:'Format',continueBody:'Steige beim nächsten offenen Block wieder ein.',savedBody:'Lege dir ein persönliches Regal mit Fragen zum Wiederholen an.',tastingBody:'Kurze praktische Module, die zwischen zwei Weinen funktionieren.',all:'Alle',journey:'Prozessreise',anatomy:'Anatomietafel',sensory:'Sensoriklabor',map:'Kartenexpedition',comparison:'A/B-Vergleich',simulator:'Simulator',diagnostic:'Diagnosefall',pairing:'Pairing-Labor',guided:'Geführte Verkostung','producer-case':'Entscheidungskette',notFound:'Diese Feldlektion wurde nicht gefunden.',openAcademy:'Akademie öffnen',addWhole:'Komplette Lektion hinzufügen',blockAdded:'Lernschritt hinzugefügt',newJourney:'Lerntisch'},
  fr:{academy:'Académie de terrain',title:'Apprendre en observant, modifiant et dégustant',intro:'Onze masterclasses approfondies et vingt-cinq guides de référence relient mécanisme, lieu et indices sensoriels. Choisissez une question, modifiez une variable, puis emportez le résultat dans une vraie dégustation.',search:'Rechercher questions, thèmes ou lieux',allSchools:'Toutes les écoles',allLevels:'Tous les niveaux',allFormats:'Tous les formats',foundation:'Fondation',intermediate:'Intermédiaire',advanced:'Avancé',continue:'Continuer',saved:'Modules enregistrés',suggested:'Laboratoires conseillés',modules:'modules',results:'résultats',empty:'Aucun module ne correspond à ces filtres.',clear:'Effacer les filtres',previous:'Précédent',next:'Suivant',page:'Page',progress:'En cours',min:'min',open:'Ouvrir la leçon',save:'Enregistrer',savedAction:'Enregistré',outcomes:'Ce que vous saurez faire',useTasting:'Utiliser en dégustation',addedTasting:'Ajouté à votre dégustation',addBlock:'Ajouter ce bloc',lessonMap:'Carte de la leçon',tableExperiment:'Passer à table',complete:'Marquer comme terminé',completed:'Terminé',sources:'Sources et limites',back:'Retour à l’académie',observe:'Observer',manipulate:'Manipuler',explain:'Expliquer',test:'Tester dans le verre',keep:'Enregistrer / utiliser',stage:'Étape',cool:'Plus frais / plus bas',warm:'Plus chaud / plus haut',reveal:'Révéler le raisonnement',reset:'Réinitialiser',country:'Pays',region:'Région',subregion:'Sous-région',site:'Site',scale:'Échelle',confidence:'Confiance',low:'Faible',high:'Élevée',choose:'Choisissez une réponse',retry:'Réessayer',correct:'Bon modèle : une variable, des indices et l’incertitude.',notQuite:'Pas encore. Isolez une variable et gardez l’incertitude visible.',sourceNote:'Les sources primaires et techniques permettent la vérification. Elles étayent mécanismes et définitions sans rendre chaque résultat sensoriel déterministe.',hostReveal:'Vérifier les indices',selfPaced:'Autonome',blocks:'blocs',duration:'Durée',format:'Format',continueBody:'Reprenez au prochain bloc inachevé.',savedBody:'Conservez les questions auxquelles vous souhaitez revenir.',tastingBody:'Des modules pratiques courts entre deux vins.',all:'Tous',journey:'Parcours du procédé',anatomy:'Planche anatomique',sensory:'Laboratoire sensoriel',map:'Expédition cartographique',comparison:'Comparaison A/B',simulator:'Simulateur',diagnostic:'Cas diagnostic',pairing:'Laboratoire d’accord',guided:'Dégustation guidée','producer-case':'Chaîne de décisions',notFound:'Cette leçon de terrain est introuvable.',openAcademy:'Ouvrir l’académie',addWhole:'Ajouter la leçon complète',blockAdded:'Étape pédagogique ajoutée',newJourney:'Table pédagogique'},
  es:{academy:'Academia de campo',title:'Aprender observando, cambiando y catando',intro:'Once clases magistrales en profundidad y veinticinco guías de referencia conectan mecanismo, lugar y evidencia sensorial. Elige una pregunta, modifica una variable y lleva el resultado a una cata real.',search:'Buscar preguntas, temas o lugares',allSchools:'Todas las escuelas',allLevels:'Todos los niveles',allFormats:'Todos los formatos',foundation:'Fundamentos',intermediate:'Intermedio',advanced:'Avanzado',continue:'Continuar aprendiendo',saved:'Módulos guardados',suggested:'Laboratorios sugeridos',modules:'módulos',results:'resultados',empty:'Ningún módulo coincide con estos filtros.',clear:'Borrar filtros',previous:'Anterior',next:'Siguiente',page:'Página',progress:'Actual',min:'min',open:'Abrir lección de campo',save:'Guardar módulo',savedAction:'Guardado',outcomes:'Lo que podrás hacer',useTasting:'Usar en una cata',addedTasting:'Añadido a tu cata',addBlock:'Añadir este bloque',lessonMap:'Mapa de la lección',tableExperiment:'Llevarlo a la mesa',complete:'Marcar como completado',completed:'Completado',sources:'Fuentes y límites',back:'Volver a la academia',observe:'Observar',manipulate:'Manipular',explain:'Explicar',test:'Probar en la copa',keep:'Guardar / usar',stage:'Etapa',cool:'Más fresco / más bajo',warm:'Más cálido / más alto',reveal:'Mostrar razonamiento',reset:'Reiniciar',country:'País',region:'Región',subregion:'Subregión',site:'Sitio',scale:'Escala',confidence:'Confianza',low:'Baja',high:'Alta',choose:'Elige una respuesta',retry:'Intentar de nuevo',correct:'Buen modelo: una variable, evidencia e incertidumbre.',notQuite:'Todavía no. Aísla una variable y mantén visible la incertidumbre.',sourceNote:'Las fuentes primarias y técnicas permiten verificar. Respaldan mecanismos y definiciones, pero no hacen determinista cada resultado sensorial.',hostReveal:'Comprobar indicios',selfPaced:'Autoguiado',blocks:'bloques',duration:'Duración',format:'Formato',continueBody:'Retoma en el siguiente bloque sin terminar.',savedBody:'Guarda preguntas personales para volver a ellas.',tastingBody:'Módulos prácticos breves entre dos vinos.',all:'Todos',journey:'Viaje del proceso',anatomy:'Lámina anatómica',sensory:'Laboratorio sensorial',map:'Expedición cartográfica',comparison:'Comparación A/B',simulator:'Simulador',diagnostic:'Caso diagnóstico',pairing:'Laboratorio de maridaje',guided:'Cata guiada','producer-case':'Cadena de decisiones',notFound:'No se encontró esta lección de campo.',openAcademy:'Abrir la academia',addWhole:'Añadir lección completa',blockAdded:'Paso de aprendizaje añadido',newJourney:'Mesa de aprendizaje'},
} as const

type LearningState={saved:string[];completed:string[];blockProgress:Record<string,string[]>}
function readState():LearningState{return repository.learning.get<LearningState>({saved:[],completed:[],blockProgress:{}})}
function writeState(value:LearningState){repository.learning.save(value)}

const archetypeIcon:Record<LearningArchetype,typeof Compass>={journey:Play,anatomy:Target,sensory:Sparkles,map:Compass,comparison:SlidersHorizontal,simulator:FlaskConical,diagnostic:Search,pairing:Wine,guided:Grape,'producer-case':Layers3}
const kindSteps:LearningBlockKind[]=['annotated-plate','process-timeline','comparison-lab','map-lab','sensory-lab','simulator','decision-case']

function addLearningToJourney(module:LearningModule,locale:Locale,block?:LearningBlock){
  const journeys=repository.journeys.all()
  const target=journeys[0]??{id:crypto.randomUUID(),title:ui[locale].newJourney,description:module.question[locale],pace:'host',access:'invite',chapters:[],updatedAt:new Date().toISOString()} satisfies TastingJourney
  const chapter:TastingChapter={id:crypto.randomUUID(),type:(block?'learning-block':'article') as TastingChapter['type'],referenceId:block?.id??module.id,title:block?.title[locale]??module.title[locale],hostNote:block?.eyebrow[locale]??module.question[locale],duration:block?.duration??module.minutes}
  const updated={...target,chapters:[...target.chapters,chapter],updatedAt:new Date().toISOString()}
  repository.journeys.save([updated,...journeys.filter(item=>item.id!==updated.id)])
}

function ModuleCard({module,locale,state,onSave}:{module:LearningModule;locale:Locale;state:LearningState;onSave:(id:string)=>void}){
  const c=ui[locale],Icon=archetypeIcon[module.archetype],media=module.blocks.find(block=>block.media)?.media
  const finished=state.completed.includes(module.id),progress=state.blockProgress[module.id]?.length??0
  return <article className={`learning-module-card archetype-${module.archetype}`}>
    <Link to={`/learn/${module.id}`} className="module-visual">
      {media&&<img src={media.src} alt={media.alt[locale]} loading="lazy"/>}
      <span className="module-format"><Icon size={15}/>{c[module.archetype]}</span>
      <span className="module-progress" style={{'--progress':`${Math.round(progress/module.blocks.length*100)}%`} as CSSProperties}>{finished?<Check size={15}/>:String(Math.round(progress/module.blocks.length*100))+'%'}</span>
    </Link>
    <div className="module-card-copy"><div><span>{schoolCopy[module.school].name[locale]}</span><span>{module.minutes} {c.min}</span></div><Link to={`/learn/${module.id}`}><h3>{module.title[locale]}</h3><p>{module.question[locale]}</p></Link><footer><span>{c[module.level]}</span><button aria-label={c.save} className={state.saved.includes(module.id)?'active':''} onClick={()=>onSave(module.id)}><Bookmark size={17} fill={state.saved.includes(module.id)?'currentColor':'none'}/></button></footer></div>
  </article>
}

export function LearningHub(){
  const {locale}=useLocale(),c={...ui[locale],intro:{en:'Eleven fully authored field masterclasses connect mechanism, place and sensory evidence. Choose a question, manipulate a real variable, then carry the result into a tasting.',de:'Elf vollständig redigierte Feld-Masterclasses verbinden Mechanismus, Ort und sensorische Evidenz. Wähle eine Frage, verändere eine reale Variable und nimm das Ergebnis mit in eine Verkostung.',fr:'Onze masterclasses de terrain entièrement rédigées relient mécanisme, lieu et indices sensoriels. Choisissez une question, modifiez une variable réelle puis testez le résultat en dégustation.',es:'Once masterclasses de campo completamente redactadas conectan mecanismo, lugar y evidencia sensorial. Elige una pregunta, modifica una variable real y lleva el resultado a una cata.'}[locale]}
  const [query,setQuery]=useState(''),[school,setSchool]=useState<LearningSchool|'all'>('all'),[level,setLevel]=useState<LearningLevel|'all'>('all'),[format,setFormat]=useState<LearningArchetype|'all'>('all'),[page,setPage]=useState(1),[guidePage,setGuidePage]=useState(1),[state,setState]=useState(readState)
  const filtered=useMemo(()=>learningModules.filter(module=>{
    const hay=`${module.title[locale]} ${module.question[locale]} ${module.summary[locale]} ${schoolCopy[module.school].name[locale]}`.toLocaleLowerCase(locale)
    return (!query||hay.includes(query.toLocaleLowerCase(locale)))&&(school==='all'||module.school===school)&&(level==='all'||module.level===level)&&(format==='all'||module.archetype===format)
  }),[query,school,level,format,locale])
  const size=9,pages=Math.max(1,Math.ceil(filtered.length/size)),visible=filtered.slice((page-1)*size,page*size)
  const localizedGuides=articles.map(article=>articleContent(article,locale))
  const filteredGuides=localizedGuides.filter(article=>!query||`${article.title} ${article.summary} ${article.eyebrow}`.toLocaleLowerCase(locale).includes(query.toLocaleLowerCase(locale)))
  const guideSize=6,guidePages=Math.max(1,Math.ceil(filteredGuides.length/guideSize)),visibleGuides=filteredGuides.slice((guidePage-1)*guideSize,guidePage*guideSize)
  const guideCopy={en:{eyebrow:'Deep reference library',title:'Twenty-five illustrated guides for a precise answer',body:'Each guide adds a long-form mechanism, a table experiment, technical sources and direct links back into grapes and regions.',open:'Read guide',page:'Guide page'},de:{eyebrow:'Vertiefende Bibliothek',title:'25 illustrierte Guides für präzise Antworten',body:'Jeder Guide verbindet einen ausführlichen Mechanismus mit Tischversuch, Fachquellen und direkten Links zu Rebsorten und Regionen.',open:'Guide lesen',page:'Guide-Seite'},fr:{eyebrow:'Bibliothèque de référence',title:'25 guides illustrés pour répondre avec précision',body:'Chaque guide relie un mécanisme détaillé, une expérience à table, des sources techniques et des accès directs aux cépages et régions.',open:'Lire le guide',page:'Page des guides'},es:{eyebrow:'Biblioteca de referencia',title:'25 guías ilustradas para responder con precisión',body:'Cada guía une un mecanismo detallado, un experimento de mesa, fuentes técnicas y conexiones directas con variedades y regiones.',open:'Leer guía',page:'Página de guías'}}[locale]
  const updateFilter=(fn:()=>void)=>{fn();setPage(1);setGuidePage(1)}
  const toggleSaved=(id:string)=>{const next={...state,saved:state.saved.includes(id)?state.saved.filter(item=>item!==id):[...state.saved,id]};setState(next);writeState(next)}
  const continued=learningModules.find(module=>(state.blockProgress[module.id]?.length??0)>0&&!state.completed.includes(module.id))??learningModules[0]
  const savedModules=learningModules.filter(module=>state.saved.includes(module.id)).slice(0,3)
  const suggested=learningModules.filter(module=>['sensory','pairing','comparison'].includes(module.archetype)).slice(0,3)
  return <div className="page learning-hub">
    <header className="learning-hub-hero"><div><span className="eyebrow">{c.academy} · {new Set(learningModules.map(module=>module.school)).size} {locale==='de'?'Schulen':locale==='fr'?'écoles':locale==='es'?'escuelas':'schools'} · {learningModules.length} {c.modules}</span><h1>{c.title}</h1><p>{c.intro}</p></div><div className="learning-loop" aria-label={`${c.observe}, ${c.manipulate}, ${c.explain}, ${c.test}, ${c.keep}`}>{[c.observe,c.manipulate,c.explain,c.test,c.keep].map((step,index)=><span key={step}><b>0{index+1}</b>{step}</span>)}</div></header>
    <section className="learning-resume-strip">
      <div><span className="eyebrow">{c.continue}</span><h2>{continued.title[locale]}</h2><p>{c.continueBody}</p><Link className="primary-button ink" to={`/learn/${continued.id}`}>{c.continue}<ArrowRight size={16}/></Link></div>
      <div className="resume-meter"><strong>{state.completed.length}</strong><span>/ {learningModules.length} {c.completed.toLocaleLowerCase(locale)}</span><i style={{'--progress':`${state.completed.length/learningModules.length*100}%`} as CSSProperties}/></div>
    </section>
    <section className="learning-discovery">
      <div className="learning-toolbar"><label className="learning-search"><Search size={18}/><input value={query} onChange={event=>updateFilter(()=>setQuery(event.target.value))} placeholder={c.search}/></label><span><Filter size={16}/>{filtered.length} {c.results}</span></div>
      <div className="learning-filters"><select aria-label={c.allSchools} value={school} onChange={event=>updateFilter(()=>setSchool(event.target.value as LearningSchool|'all'))}><option value="all">{c.allSchools}</option>{Object.entries(schoolCopy).map(([id,item])=><option value={id} key={id}>{item.name[locale]}</option>)}</select><select aria-label={c.allLevels} value={level} onChange={event=>updateFilter(()=>setLevel(event.target.value as LearningLevel|'all'))}><option value="all">{c.allLevels}</option>{(['foundation','intermediate','advanced'] as const).map(item=><option key={item} value={item}>{c[item]}</option>)}</select><select aria-label={c.allFormats} value={format} onChange={event=>updateFilter(()=>setFormat(event.target.value as LearningArchetype|'all'))}><option value="all">{c.allFormats}</option>{Object.keys(archetypeIcon).map(item=><option key={item} value={item}>{c[item as LearningArchetype]}</option>)}</select></div>
      {visible.length?<div className="learning-module-grid">{visible.map(module=><ModuleCard key={module.id} module={module} locale={locale} state={state} onSave={toggleSaved}/>)}</div>:<div className="learning-empty"><BookOpen/><h2>{c.empty}</h2><button className="secondary-button" onClick={()=>{setQuery('');setSchool('all');setLevel('all');setFormat('all')}}>{c.clear}</button></div>}
      <nav className="learning-pagination" aria-label={c.page}><button disabled={page===1} onClick={()=>setPage(value=>value-1)}><ArrowLeft/>{c.previous}</button><span>{c.page} {page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)}>{c.next}<ArrowRight/></button></nav>
    </section>
    <section className="reference-library"><header><div><span className="eyebrow">{guideCopy.eyebrow}</span><h2>{guideCopy.title}</h2><p>{guideCopy.body}</p></div><strong>{filteredGuides.length}</strong></header><div className="reference-guide-grid">{visibleGuides.map((guide,index)=><Link to={`/learn/${guide.id}`} className={`reference-guide category-${guide.eyebrow.toLowerCase().replace(/[^a-z]+/g,'-')}`} key={guide.id}><div className="guide-illustration" aria-hidden="true"><i/><i/><i/><span>{String((guidePage-1)*guideSize+index+1).padStart(2,'0')}</span></div><small>{guide.eyebrow} · {guide.minutes} {c.min}</small><h3>{guide.title}</h3><p>{guide.summary}</p><b>{guideCopy.open}<ArrowRight/></b></Link>)}</div><nav className="learning-pagination" aria-label={guideCopy.page}><button disabled={guidePage===1} onClick={()=>setGuidePage(value=>value-1)}><ArrowLeft/>{c.previous}</button><span>{c.page} {guidePage} / {guidePages}</span><button disabled={guidePage===guidePages} onClick={()=>setGuidePage(value=>value+1)}>{c.next}<ArrowRight/></button></nav></section>
    <section className="learning-shelves"><div><span className="eyebrow">{c.saved}</span><h2>{c.savedBody}</h2>{(savedModules.length?savedModules:learningModules.slice(0,3)).map(module=><Link to={`/learn/${module.id}`} key={module.id}><Bookmark size={15}/><span>{module.title[locale]}</span><ChevronRight/></Link>)}</div><div><span className="eyebrow">{c.suggested}</span><h2>{c.tastingBody}</h2>{suggested.map(module=><Link to={`/learn/${module.id}`} key={module.id}><FlaskConical size={15}/><span>{module.title[locale]}</span><ChevronRight/></Link>)}</div></section>
  </div>
}

function entityLink(id:string){if(regions.some(item=>item.id===id))return `/regions/${id}`;if(grapes.some(item=>item.id===id))return `/grapes/${id}`;if(producers.some(item=>item.id===id))return `/wineries/${id}`;if(wines.some(item=>item.id===id))return `/wines/${id}`;if(aromas.some(item=>item.id===id))return `/aromas?selected=${id}`;return '/atlas'}
function entityName(id:string){return [...regions,...grapes,...producers,...wines,...aromas].find(item=>item.id===id)?.name??id.replaceAll('-',' ')}

function InteractiveVisual({block,locale}:{block:LearningBlock;locale:Locale}){
  const c=ui[locale],[value,setValue]=useState(45),[step,setStep]=useState(0),[answer,setAnswer]=useState<number|null>(null),[revealed,setRevealed]=useState(false)
  const stages=block.stages?.[locale]??[c.observe,c.manipulate,c.explain,c.test,c.keep],scales=block.stages?.[locale].slice(0,4)??[c.country,c.region,c.subregion,c.site]
  if(block.kind==='knowledge-check')return <div className="knowledge-check"><p>{c.choose}</p><div>{block.options?.[locale].map((option,index)=><button key={option} className={answer===index?(index===block.answer?'correct':'wrong'):''} onClick={()=>setAnswer(index)}><span>{String.fromCharCode(65+index)}</span>{option}</button>)}</div>{answer!==null&&<p className={answer===block.answer?'feedback-correct':'feedback-wrong'}>{answer===block.answer?c.correct:c.notQuite}</p>}{answer!==null&&answer!==block.answer&&<button className="text-action" onClick={()=>setAnswer(null)}><RotateCcw size={15}/>{c.retry}</button>}</div>
  if(block.kind==='process-timeline')return <div className="process-controller"><div>{stages.map((label,index)=><button key={label} aria-current={step===index?'step':undefined} className={step===index?'active':index<step?'done':''} onClick={()=>setStep(index)}><span>{index<step?<Check/>:String(index+1).padStart(2,'0')}</span>{label}</button>)}</div><article><span>{c.stage} {step+1}</span><strong>{stages[step]}</strong><p>{block.body[locale][step%block.body[locale].length]}</p><button className="text-action" onClick={()=>setStep(value=>(value+1)%stages.length)}>{step===stages.length-1?<RotateCcw/>:<Play/>}{step===stages.length-1?c.reset:c.next}</button></article></div>
  if(block.kind==='annotated-plate')return <div className="plate-hotspots"><div className="hotspot-list">{[c.observe,c.manipulate,c.explain].map((label,index)=><button key={label} aria-current={step===index?'step':undefined} className={step===index?'active':''} onClick={()=>setStep(index)}><span>{String(index+1).padStart(2,'0')}</span>{label}</button>)}</div><p>{block.body[locale][step]}</p></div>
  if(block.kind==='map-lab')return <div className="map-scale-lab"><span>{c.scale}</span>{block.id.startsWith('germany-origin')?<div className="germany-learning-map" role="img" aria-label={block.media?.alt[locale]}><svg viewBox="0 0 440 270" aria-hidden="true"><path className="country-shape" d="M185 18l45 12 17 32 38 18-7 43 28 27-32 31-7 55-58 22-41-30-48-7-7-45 23-31-10-40 36-31z"/><path className="river-line" d="M252 39c-18 32-10 55-34 79-19 19-13 42-47 78"/><path className="mosel-line" d="M218 119c-31 3-29 24-57 17-24-6-24 19-45 15"/><circle cx="148" cy="143" r="7"/><circle cx="230" cy="92" r="7"/></svg><span className="map-label mosel">Mosel</span><span className="map-label rheingau">Rheingau</span></div>:<div className="learning-locator" role="img" aria-label={block.media?.alt[locale]}>{scales.map((label,index)=><span key={label} style={{'--locator-index':index} as CSSProperties}><i>{index+1}</i><b>{label}</b></span>)}</div>}<div>{scales.map((label,index)=><button key={label} className={step===index?'active':''} onClick={()=>setStep(index)}><i/>{label}</button>)}</div><p aria-live="polite">{block.body[locale][step%block.body[locale].length]}</p></div>
  if(block.kind==='decision-case')return <div className="decision-reveal"><div className="evidence-vials">{[0,1,2,3].map(index=><button key={index} className={step===index?'active':''} onClick={()=>setStep(index)} aria-label={`${c.stage} ${index+1}`}><i/></button>)}</div><p>{revealed?block.body[locale][step%block.body[locale].length]:block.body[locale][0]}</p><button className="secondary-button" onClick={()=>setRevealed(value=>!value)}>{revealed?<Pause/>:<Play/>}{revealed?c.reset:c.reveal}</button></div>
  if(['comparison-lab','sensory-lab','simulator'].includes(block.kind)){const control=block.control,band=value<34?0:value<68?1:2;return <div className={`learning-dial ${block.kind}`}><strong className="dial-variable">{control?.label[locale]??block.title[locale]}</strong><div><span>{control?.low[locale]??c.cool}</span><b>{value}</b><span>{control?.high[locale]??c.warm}</span></div><input aria-label={control?.label[locale]??block.title[locale]} aria-valuetext={control?.states[locale][band]??String(value)} type="range" min="0" max="100" value={value} onChange={event=>setValue(Number(event.target.value))}/><div className="dial-result" aria-live="polite"><i style={{'--value':`${value}%`} as CSSProperties}/><p>{control?.states[locale][band]??block.body[locale][band]}</p></div></div>}
  return null
}

export function PortableLearningBlock({module,block,compact=false}:{module:LearningModule;block:LearningBlock;compact?:boolean}){
  const {locale}=useLocale(),c=ui[locale],[added,setAdded]=useState(false)
  return <section id={block.id} className={`portable-learning-block block-${block.kind} ${compact?'compact':''}`}>
    <header><div><span className="eyebrow">{block.eyebrow[locale]} · {block.duration} {c.min}</span><h2>{block.title[locale]}</h2></div><span className="behavior-chip">{block.behavior==='host-reveal'?c.hostReveal:c.selfPaced}</span></header>
    {block.media&&<figure className={`learning-plate focus-${block.media.focus??'center'}`}><img src={block.media.src} alt={block.media.alt[locale]} loading="lazy"/><span className="plate-index">{block.kind==='annotated-plate'?'01 · 02 · 03':block.kind==='map-lab'?`${c.country} → ${c.site}`:`${c.observe} → ${c.test}`}</span></figure>}
    {kindSteps.includes(block.kind)&&<InteractiveVisual block={block} locale={locale}/>} 
    {!kindSteps.includes(block.kind)&&block.kind!=='knowledge-check'&&block.kind!=='sources'&&<div className="learning-prose">{block.body[locale].map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div>}
    {block.kind==='knowledge-check'&&<InteractiveVisual block={block} locale={locale}/>} 
    {block.kind==='glossary'&&<dl className="inline-glossary"><div><dt>{module.title[locale]}</dt><dd>{module.summary[locale]}</dd></div><div><dt>{c.confidence}</dt><dd>{block.body[locale][1]}</dd></div></dl>}
    {block.kind==='entity-connections'&&<div className="block-entity-links">{(module.entityIds.length?module.entityIds:['riesling','mosel','chardonnay']).map(id=><Link to={entityLink(id)} key={id}>{entityName(id)}<ChevronRight/></Link>)}</div>}
    {block.kind==='sources'&&<div className="block-sources">{block.body[locale].map(paragraph=><p key={paragraph}>{paragraph}</p>)}<p>{c.sourceNote}</p>{(block.sources??curriculumSources[module.school].map(item=>({...item,supports:{en:'',de:'',fr:'',es:''}}))).map(source=><a href={source.url} target="_blank" rel="noreferrer" key={source.url}><span><strong>{source.label}</strong><small>{source.supports[locale]}</small></span><ArrowRight/></a>)}</div>}
    {!compact&&block.kind!=='sources'&&<button className={`add-learning-block ${added?'added':''}`} onClick={()=>{addLearningToJourney(module,locale,block);setAdded(true)}}>{added?<Check/>:<Layers3/>}{added?c.blockAdded:c.addBlock}</button>}
  </section>
}

export function LearningLesson(){
  const {slug}=useParams(),{locale}=useLocale(),c=ui[locale],module=learningModuleById(slug??'')
  const [state,setState]=useState(readState),[added,setAdded]=useState(false),[currentBlock,setCurrentBlock]=useState('')
  useEffect(()=>{
    if(!module)return
    const done=state.blockProgress[module.id]??[]
    setCurrentBlock(current=>current&&module.blocks.some(block=>block.id===current)?current:module.blocks.find(block=>!done.includes(block.id))?.id??module.blocks[0]?.id??'')
    const observer=new IntersectionObserver(entries=>{
      const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>Math.abs(a.boundingClientRect.top)-Math.abs(b.boundingClientRect.top))[0]
      if(visible)setCurrentBlock((visible.target as HTMLElement).id)
    },{rootMargin:'-18% 0px -66% 0px',threshold:[0,.2,.6]})
    module.blocks.forEach(block=>{const element=document.getElementById(block.id);if(element)observer.observe(element)})
    return ()=>observer.disconnect()
  },[module?.id,state.blockProgress])
  if(!module)return <div className="page learning-not-found"><BookOpen/><h1>{c.notFound}</h1><Link className="primary-button ink" to="/learn">{c.openAcademy}</Link></div>
  const done=state.blockProgress[module.id]??[],saved=state.saved.includes(module.id),completed=state.completed.includes(module.id)
  const update=(next:LearningState)=>{setState(next);writeState(next)}
  const toggleSaved=()=>update({...state,saved:saved?state.saved.filter(id=>id!==module.id):[...state.saved,module.id]})
  const markBlock=(id:string)=>{if(done.includes(id))return;update({...state,blockProgress:{...state.blockProgress,[module.id]:[...done,id]}})}
  const finish=()=>update({...state,completed:completed?state.completed.filter(id=>id!==module.id):[...state.completed,module.id],blockProgress:{...state.blockProgress,[module.id]:module.blocks.map(block=>block.id)}})
  const Icon=archetypeIcon[module.archetype],next=learningModules[(learningModules.indexOf(module)+1)%learningModules.length]
  return <article className={`page learning-lesson lesson-${module.archetype}`}>
    <Link className="back-link" to="/learn"><ArrowLeft/>{c.back}</Link>
    <header className="lesson-opening"><div><span className="eyebrow">{schoolCopy[module.school].name[locale]} · {c[module.level]}</span><h1>{module.title[locale]}</h1><p>{module.question[locale]}</p><div className="lesson-meta"><span><Clock/>{module.minutes} {c.min}</span><span><Icon/>{c[module.archetype]}</span><span><Layers3/>{module.blocks.length} {c.blocks}</span></div><div className="lesson-actions"><button className="primary-button ink" onClick={()=>{addLearningToJourney(module,locale);setAdded(true)}}>{added?<Check/>:<Layers3/>}{added?c.addedTasting:c.addWhole}</button><button className={`secondary-button ${saved?'active':''}`} onClick={toggleSaved}><Bookmark fill={saved?'currentColor':'none'}/>{saved?c.savedAction:c.save}</button></div></div><div className="opening-question"><span>{c.observe} → {c.manipulate} → {c.test}</span><strong>{String(learningModules.indexOf(module)+1).padStart(2,'0')}</strong><p>{module.summary[locale]}</p></div></header>
    <section className="lesson-outcomes"><span className="eyebrow">{c.outcomes}</span><ol>{module.outcomes[locale].map((outcome,index)=><li key={outcome}><span>0{index+1}</span>{outcome}</li>)}</ol></section>
    <div className="lesson-field-layout"><aside className="lesson-rail" aria-label={c.lessonMap}><span className="eyebrow">{c.lessonMap}</span><i className="lesson-total-progress" style={{'--progress':`${done.length/module.blocks.length*100}%`} as CSSProperties}/>{module.blocks.map((block,index)=>{const isDone=done.includes(block.id),isCurrent=currentBlock===block.id;return <a href={`#${block.id}`} aria-current={isCurrent?'step':undefined} aria-label={`${index+1}. ${block.title[locale]} · ${isCurrent?c.progress:isDone?c.completed:c.next}`} className={`${isDone?'done':''} ${isCurrent?'current':''}`.trim()} key={block.id} onClick={()=>setCurrentBlock(block.id)}><span>{isCurrent?String(index+1).padStart(2,'0'):isDone?<Check/>:String(index+1).padStart(2,'0')}</span><div><small>{block.eyebrow[locale]}</small><strong>{block.title[locale]}</strong></div></a>})}</aside><main className="lesson-blocks">{module.blocks.map(block=>{const isDone=done.includes(block.id);return <div className="lesson-block-wrap" key={block.id}><PortableLearningBlock module={module} block={block}/><button type="button" className={`block-completion-action ${isDone?'completed':''}`} disabled={isDone} onClick={()=>markBlock(block.id)}>{<Check/>}{isDone?c.completed:c.complete}</button></div>})}</main></div>
    <section className="table-experiment"><div><span className="eyebrow">{c.tableExperiment}</span><h2>{module.title[locale]}</h2><p>{module.experiment[locale]}</p></div><Wine/></section>
    <section className="lesson-finish"><button className={`primary-button ${completed?'completed':''}`} onClick={finish}>{completed?<Check/>:<Target/>}{completed?c.completed:c.complete}</button><Link to={`/learn/${next.id}`}><span>{c.next}</span><strong>{next.title[locale]}</strong><ArrowRight/></Link></section>
  </article>
}

export function InlineLearningChapter({referenceId}:{referenceId:string}){
  const pair=learningBlockById(referenceId),module=learningModuleById(referenceId)
  if(pair)return <PortableLearningBlock module={pair.module} block={pair.block} compact/>
  if(module)return <PortableLearningBlock module={module} block={module.blocks.find(block=>kindSteps.includes(block.kind))??module.blocks[0]} compact/>
  return null
}

export {ui as learningUi}
