import { CircleMarker, MapContainer, TileLayer } from 'react-leaflet'
import { useState } from 'react'
import { ArrowRight, Compass, Droplets, FlaskConical, Grape as GrapeIcon, Layers3, Mountain, Route, SunMedium, Wine as WineIcon } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Article, Grape, Producer, Region, Wine } from './types'
import type { Locale } from './i18n'
import { evidencedRegionProfileIds, grapes, producers, regions } from './data/catalog'
import { countryLabel, geographicName, grapeContent, grapeEvidenceContent, producerContent, regionContent, regionName, wineContent } from './localizedContent'
import ampelographyMedia from './data/ampelographyMedia.generated.json'
import soilAtlas from './assets/vineyard-soil-atlas.jpg'
import bottleFormsPlate from './assets/wine-bottle-forms.jpg'
import redGrapeBotanyPlate from './assets/knowledge-grape-botany.jpg'
import whiteGrapeBotanyPlate from './assets/knowledge-grape-botany-white.jpg'
import { RegionPortrait } from './RegionPortrait'
import './interaction-audit.css'

const depthCopy={
  en:{mapEyebrow:'Geographic orientation',mapTitle:'Locate the region before reading its style',mapBody:'The marker uses the atlas coordinate for this region. Zoom level is contextual; appellation boundaries can be much smaller or more complex than the point shown.',soilEyebrow:'Soil field guide',soilTitle:'Read structure, water and roots—not a list of flavours',soilBody:'Geology affects drainage, heat, rooting and vine stress. It does not season wine like an ingredient; the grower’s response remains part of the chain.',water:'Water behaviour',root:'Rooting clue',heat:'Heat and season',compare:'Compare in the atlas',grapeEyebrow:'Variety laboratory',grapeTitle:'One grape, three moving targets',cool:'In a cooler expression',warm:'In a warmer expression',grower:'The grower watches',maker:'The cellar changes',structure:'Structural compass',producerEyebrow:'Estate decision map',producerTitle:'Follow the choices from parcel to bottle',site:'Site and material',harvest:'Harvest threshold',cellar:'Cellar translation',verify:'Primary source',wineEyebrow:'Bottle and evolution',wineTitle:'Read the wine as a sequence, not a snapshot',open:'At opening',air:'With air',table:'At the table',cellarTime:'Across the drinking window',shape:'Bottle shape is history, not a score',shapeBody:'Bordeaux shoulders, Burgundy slopes, slender Rhine forms and pressure-resistant sparkling bottles grew from handling and production needs. None guarantees quality.',lessonEyebrow:'Masterclass extension',lessonTitle:'Turn the lesson into a repeatable skill',myth:'Common shortcut to avoid',mechanism:'Mechanism to explain',comparison:'Comparison to set up',practice:'Practice at the table',question:'A useful next question',connections:'Continue through connected examples'},
  de:{mapEyebrow:'Geografische Orientierung',mapTitle:'Erst die Region verorten, dann ihren Stil lesen',mapBody:'Der Marker nutzt die Atlas-Koordinate dieser Region. Der Zoom dient der Orientierung; Appellationsgrenzen können deutlich kleiner oder komplexer sein als der gezeigte Punkt.',soilEyebrow:'Boden-Feldführer',soilTitle:'Struktur, Wasser und Wurzeln lesen – keine Aromaliste',soilBody:'Geologie beeinflusst Drainage, Wärme, Durchwurzelung und Stress der Rebe. Sie würzt Wein nicht wie eine Zutat; die Reaktion des Winzers bleibt Teil der Kette.',water:'Wasserverhalten',root:'Hinweis zur Durchwurzelung',heat:'Wärme und Saison',compare:'Im Atlas vergleichen',grapeEyebrow:'Rebsortenlabor',grapeTitle:'Eine Rebsorte, drei bewegliche Ziele',cool:'In einer kühleren Ausprägung',warm:'In einer wärmeren Ausprägung',grower:'Darauf achtet der Winzer',maker:'Das verändert der Keller',structure:'Struktureller Kompass',producerEyebrow:'Entscheidungskarte des Weinguts',producerTitle:'Die Entscheidungen von der Parzelle bis zur Flasche verfolgen',site:'Standort und Material',harvest:'Schwelle für die Lese',cellar:'Übersetzung im Keller',verify:'Primärquelle',wineEyebrow:'Flasche und Entwicklung',wineTitle:'Den Wein als Verlauf lesen, nicht als Momentaufnahme',open:'Beim Öffnen',air:'Mit Luft',table:'Am Tisch',cellarTime:'Im Trinkfenster',shape:'Flaschenform ist Geschichte, keine Bewertung',shapeBody:'Bordeaux-Schultern, Burgunderform, schlanke Rheinflaschen und druckfeste Schaumweinflaschen entstanden aus Handhabung und Produktion. Keine Form garantiert Qualität.',lessonEyebrow:'Masterclass-Erweiterung',lessonTitle:'Aus Wissen eine wiederholbare Fähigkeit machen',myth:'Verkürzung, die du vermeiden solltest',mechanism:'Mechanismus, den du erklären kannst',comparison:'Vergleich, den du aufbauen kannst',practice:'Übung am Tisch',question:'Eine sinnvolle nächste Frage',connections:'Mit verbundenen Beispielen fortfahren'},
  fr:{mapEyebrow:'Orientation géographique',mapTitle:'Situer la région avant de lire son style',mapBody:'Le repère utilise la coordonnée de l’atlas. Le niveau de zoom donne un contexte ; les limites d’une appellation peuvent être bien plus petites ou complexes que ce point.',soilEyebrow:'Guide de terrain des sols',soilTitle:'Lire structure, eau et racines — pas une liste de saveurs',soilBody:'La géologie agit sur drainage, chaleur, enracinement et stress. Elle n’assaisonne pas le vin ; la réponse du vigneron reste un maillon essentiel.',water:'Comportement de l’eau',root:'Indice d’enracinement',heat:'Chaleur et saison',compare:'Comparer dans l’atlas',grapeEyebrow:'Laboratoire du cépage',grapeTitle:'Un cépage, trois cibles mobiles',cool:'Dans une expression plus fraîche',warm:'Dans une expression plus chaude',grower:'Ce que surveille le vigneron',maker:'Ce que change la cave',structure:'Boussole structurelle',producerEyebrow:'Carte des décisions du domaine',producerTitle:'Suivre les choix de la parcelle à la bouteille',site:'Site et matière',harvest:'Seuil de vendange',cellar:'Traduction en cave',verify:'Source primaire',wineEyebrow:'Bouteille et évolution',wineTitle:'Lire le vin comme une séquence, non un instant',open:'À l’ouverture',air:'Avec l’air',table:'À table',cellarTime:'Dans sa fenêtre',shape:'La forme raconte une histoire, pas une note',shapeBody:'Épaules bordelaises, pente bourguignonne, flûte rhénane et verre résistant des effervescents viennent de besoins pratiques. Aucune forme ne garantit la qualité.',lessonEyebrow:'Extension masterclass',lessonTitle:'Transformer la leçon en savoir-faire répétable',myth:'Raccourci à éviter',mechanism:'Mécanisme à expliquer',comparison:'Comparaison à préparer',practice:'Exercice à table',question:'Prochaine question utile',connections:'Continuer avec des exemples reliés'},
  es:{mapEyebrow:'Orientación geográfica',mapTitle:'Sitúa la región antes de interpretar su estilo',mapBody:'El marcador usa la coordenada del atlas. El zoom aporta contexto; los límites de una denominación pueden ser mucho menores o más complejos que el punto.',soilEyebrow:'Guía de campo de suelos',soilTitle:'Lee estructura, agua y raíces, no una lista de sabores',soilBody:'La geología influye en drenaje, calor, raíces y estrés. No sazona el vino como un ingrediente; la respuesta del viticultor sigue siendo parte de la cadena.',water:'Comportamiento del agua',root:'Pista de enraizamiento',heat:'Calor y temporada',compare:'Comparar en el atlas',grapeEyebrow:'Laboratorio de variedades',grapeTitle:'Una variedad, tres objetivos móviles',cool:'En una expresión más fresca',warm:'En una expresión más cálida',grower:'Lo que vigila el viticultor',maker:'Lo que cambia la bodega',structure:'Brújula estructural',producerEyebrow:'Mapa de decisiones de la bodega',producerTitle:'Sigue las decisiones de la parcela a la botella',site:'Lugar y material',harvest:'Umbral de vendimia',cellar:'Traducción en bodega',verify:'Fuente primaria',wineEyebrow:'Botella y evolución',wineTitle:'Lee el vino como secuencia, no como instante',open:'Al abrir',air:'Con aire',table:'En la mesa',cellarTime:'En su ventana',shape:'La forma es historia, no puntuación',shapeBody:'Hombros bordeleses, pendiente borgoñona, botella renana y vidrio resistente para espumosos nacieron de necesidades prácticas. Ninguna forma garantiza calidad.',lessonEyebrow:'Extensión masterclass',lessonTitle:'Convierte la lección en una habilidad repetible',myth:'Atajo que conviene evitar',mechanism:'Mecanismo que debes explicar',comparison:'Comparación que puedes preparar',practice:'Práctica en la mesa',question:'Una siguiente pregunta útil',connections:'Continuar con ejemplos conectados'},
} as const

const soilLibrary={
  limestone:{pattern:/limestone|chalk|calcareous|marl|kalk|craie|calcaire/i,title:{en:'Limestone & chalk',de:'Kalkstein & Kreide',fr:'Calcaire & craie',es:'Caliza & tiza'},water:{en:'Fractures and fine pores can combine drainage with useful reserves.',de:'Klüfte und feine Poren können Drainage mit nutzbaren Reserven verbinden.',fr:'Fissures et pores fins peuvent unir drainage et réserve utile.',es:'Fisuras y poros finos pueden unir drenaje y reserva útil.'},root:{en:'Roots exploit cracks, softer marl bands and biological channels.',de:'Wurzeln nutzen Risse, weichere Mergelbänder und biologische Kanäle.',fr:'Les racines suivent fissures, marnes tendres et canaux biologiques.',es:'Las raíces siguen fisuras, margas blandas y canales biológicos.'}},
  slate:{pattern:/slate|schist|schiefer|ardoise|pizarra/i,title:{en:'Slate & schist',de:'Schiefer',fr:'Schiste & ardoise',es:'Pizarra & esquisto'},water:{en:'Thin fractured layers shed water quickly but can hold it deep in fissures.',de:'Dünne Bruchschichten leiten Wasser rasch ab, halten es aber tief in Klüften.',fr:'Les feuillets drainent vite mais gardent parfois l’eau en profondeur.',es:'Las láminas drenan rápido, aunque guardan agua en fisuras profundas.'},root:{en:'Roots search vertically and laterally through fractured planes.',de:'Wurzeln suchen vertikal und seitlich entlang der Bruchflächen.',fr:'Les racines explorent verticalement et latéralement les fractures.',es:'Las raíces exploran en vertical y lateral las fracturas.'}},
  clay:{pattern:/clay|loam|loess|ton|argile|arcilla/i,title:{en:'Clay & loam',de:'Ton & Lehm',fr:'Argile & limon',es:'Arcilla & limo'},water:{en:'Fine particles hold water and nutrients; compaction and timing matter.',de:'Feine Partikel halten Wasser und Nährstoffe; Verdichtung und Timing zählen.',fr:'Les particules fines retiennent eau et nutriments ; le tassement compte.',es:'Las partículas finas guardan agua y nutrientes; importa la compactación.'},root:{en:'Roots favour cracks, aggregate edges and biologically active zones.',de:'Wurzeln bevorzugen Risse, Aggregatränder und biologisch aktive Zonen.',fr:'Les racines préfèrent fissures, agrégats et zones biologiquement actives.',es:'Las raíces prefieren grietas, agregados y zonas biológicamente activas.'}},
  granite:{pattern:/granite|granitic|granit/i,title:{en:'Granite',de:'Granit',fr:'Granit',es:'Granito'},water:{en:'Weathered granite often drains freely; depth determines reserve.',de:'Verwitterter Granit drainiert oft frei; die Tiefe bestimmt die Reserve.',fr:'Le granit altéré draine librement ; la profondeur règle la réserve.',es:'El granito meteorizado drena bien; la profundidad marca la reserva.'},root:{en:'Roots use decomposed pockets and joints between harder blocks.',de:'Wurzeln nutzen Zersatzzonen und Fugen zwischen härteren Blöcken.',fr:'Les racines utilisent arènes et joints entre blocs plus durs.',es:'Las raíces aprovechan arenas y juntas entre bloques duros.'}},
  volcanic:{pattern:/volcanic|basalt|lava|vulkan|volcanique|volcán/i,title:{en:'Volcanic material',de:'Vulkangestein',fr:'Roche volcanique',es:'Roca volcánica'},water:{en:'Porosity varies strongly between ash, tuff, lava and basalt.',de:'Die Porosität variiert stark zwischen Asche, Tuff, Lava und Basalt.',fr:'La porosité varie fortement entre cendres, tuf, lave et basalte.',es:'La porosidad cambia mucho entre ceniza, toba, lava y basalto.'},root:{en:'Roots exploit vesicles, ash layers and boundaries between flows.',de:'Wurzeln nutzen Blasenräume, Aschelagen und Grenzen zwischen Strömen.',fr:'Les racines suivent vacuoles, cendres et limites entre coulées.',es:'Las raíces siguen vesículas, cenizas y límites entre coladas.'}},
  gravel:{pattern:/gravel|sand|alluvial|kies|sand|gravier|sable|grava|arena/i,title:{en:'Gravel, sand & alluvium',de:'Kies, Sand & Schwemmland',fr:'Graviers, sable & alluvions',es:'Grava, arena y aluvión'},water:{en:'Coarse material drains rapidly; fine layers and water table set reserves.',de:'Grobes Material drainiert rasch; Feinlagen und Grundwasser setzen Reserven.',fr:'Les éléments grossiers drainent vite ; fines et nappe fixent la réserve.',es:'El material grueso drena rápido; finos y nivel freático fijan la reserva.'},root:{en:'Roots travel through interstices and follow buried finer horizons.',de:'Wurzeln wachsen durch Zwischenräume und folgen feineren Horizonten.',fr:'Les racines traversent les interstices et suivent les horizons fins.',es:'Las raíces pasan por intersticios y siguen horizontes más finos.'}},
} as const

type SoilGuide={title:Record<Locale,string>;water:Record<Locale,string>;root:Record<Locale,string>}
const soilScopeNote:Record<Locale,string>={
  en:'These are general properties of the material names in this region profile, not measurements from a specific vineyard parcel or predictions of wine flavour.',
  de:'Die Karten beschreiben allgemeine Eigenschaften der im Regionsprofil genannten Materialien. Sie sind keine Messungen einer bestimmten Parzelle und sagen keinen Weingeschmack voraus.',
  fr:'Ces fiches décrivent des propriétés générales des matériaux cités dans le profil régional, pas des mesures d’une parcelle précise ni une prévision du goût du vin.',
  es:'Estas fichas describen propiedades generales de los materiales citados en el perfil regional; no son mediciones de una parcela concreta ni predicciones del sabor del vino.',
}
const sandstoneGuide:SoilGuide={
  title:{en:'Sandstone',de:'Sandstein',fr:'Grès',es:'Arenisca'},
  water:{en:'Cement and fracture pattern decide whether sandstone sheds water or keeps reserves.',de:'Bindemittel und Klüfte entscheiden, ob Sandstein Wasser ableitet oder speichert.',fr:'Le ciment et les fractures décident si le grès draine ou garde une réserve.',es:'El cemento y las fracturas deciden si la arenisca drena o conserva reservas.'},
  root:{en:'Roots follow bedding planes and weathered seams rather than the rock name alone.',de:'Wurzeln folgen Schichtflächen und verwitterten Nähten, nicht nur dem Gesteinsnamen.',fr:'Les racines suivent les plans de stratification et les joints altérés.',es:'Las raíces siguen planos de estratificación y juntas meteorizadas.'},
}
const sandGuide:SoilGuide={
  title:{en:'Sand',de:'Sand',fr:'Sable',es:'Arena'},
  water:{en:'Loose sand drains quickly; depth and finer layers determine the reserve.',de:'Lockerer Sand drainiert rasch; Tiefe und Feinlagen bestimmen die Reserve.',fr:'Le sable meuble draine vite ; profondeur et couches fines fixent la réserve.',es:'La arena suelta drena rápido; profundidad y capas finas fijan la reserva.'},
  root:{en:'Roots use pore spaces and any finer or wetter layer below.',de:'Wurzeln nutzen Porenräume und darunterliegende feinere oder feuchtere Lagen.',fr:'Les racines utilisent les pores et les couches plus fines ou humides en profondeur.',es:'Las raíces aprovechan poros y capas más finas o húmedas.'},
}

/** Soil cards are keyed only from the canonical English region.soil field. */
function canonicalSoilGuides(soil:string):SoilGuide[]{
  const guides:SoilGuide[]=[]
  if(/\b(limestone|chalk|calcareous|marl)\b/i.test(soil))guides.push(soilLibrary.limestone)
  if(/\b(slate|schist)\b/i.test(soil))guides.push(soilLibrary.slate)
  if(/\b(clay|loam|loess)\b/i.test(soil))guides.push(soilLibrary.clay)
  if(/\b(granite|granitic)\b/i.test(soil))guides.push(soilLibrary.granite)
  if(/\b(volcanic|basalt|lava)\b/i.test(soil))guides.push(soilLibrary.volcanic)
  if(/\bsandstone\b/i.test(soil))guides.push(sandstoneGuide)
  if(/\b(gravel|alluvial)\b/i.test(soil))guides.push(soilLibrary.gravel)
  if(/(?<!\w)sand(?!stone)\b/i.test(soil))guides.push(sandGuide)
  return guides
}

function mapZoom(country:string){return ['United States','Canada','Argentina','Chile','Australia','China','South Africa','India'].includes(country)?3:['France','Italy','Spain','Germany','Portugal','New Zealand','Japan'].includes(country)?5:4}

function regionGeographyCopy(region:Region,locale:Locale){
  const content=regionContent(region,locale),country=countryLabel(region.country,locale),name=regionName(region,locale)
  const latitude=`${Math.abs(region.lat).toFixed(1)}° ${region.lat>=0?'N':'S'}`
  const coordinates=`${latitude} · ${Math.abs(region.lng).toFixed(1)}° ${region.lng>=0?'E':'W'}`
  const zones=region.subregions.slice(0,3).map(zone=>geographicName(zone,locale)).join(', ')
  if(!region.hasRegionalTerroirEvidence)return {
    eyebrow:{en:'Place in context',de:'Ort im Zusammenhang',fr:'Le lieu en contexte',es:'El lugar en contexto'}[locale],
    title:`${name} · ${country}`,
    body:content.summary,
    caption:coordinates,
  }
  const placeCopy={
    en:{eyebrow:'Place in context',zones:'Named subregions: '},
    de:{eyebrow:'Ort im Zusammenhang',zones:'Benannte Teilregionen: '},
    fr:{eyebrow:'Le lieu en contexte',zones:'Sous-régions nommées : '},
    es:{eyebrow:'El lugar en contexto',zones:'Subregiones con nombre: '},
  }[locale]
  return {eyebrow:placeCopy.eyebrow,title:`${name} · ${country}`,body:[content.climate.trim(),zones?`${placeCopy.zones}${zones}.`:'' ].filter(Boolean).join(' ')||content.summary,caption:content.soil.trim()?`${name}: ${content.soil}`:coordinates}
}

export function RegionFieldGuide({region,locale}:{region:Region;locale:Locale}){
  const c=depthCopy[locale],content=regionContent(region,locale),geography=regionGeographyCopy(region,locale),matches=canonicalSoilGuides(region.soil)
  return <section className="region-field-guide">
    <RegionPortrait region={region} locale={locale}/>
    <div className="locator-card"><div className="depth-heading"><span className="eyebrow">{geography.eyebrow}</span><h2>{geography.title}</h2>{geography.body&&<p>{geography.body}</p>}</div><div className="mini-region-map" aria-label={`${regionName(region,locale)} · ${countryLabel(region.country,locale)}`}><MapContainer key={region.id} center={[region.lat,region.lng]} zoom={mapZoom(region.country)} scrollWheelZoom={false} dragging={false} doubleClickZoom={false} zoomControl={false}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><CircleMarker center={[region.lat,region.lng]} radius={9} pathOptions={{color:'#f7efe3',fillColor:'#7d2638',fillOpacity:1,weight:3}}/></MapContainer><span><Compass/>{geography.caption}</span></div></div>
    {evidencedRegionProfileIds.has(region.id)&&matches.length>0&&<div className="soil-atlas-card"><img src={soilAtlas} alt=""/><div className="depth-heading"><span className="eyebrow">{c.soilEyebrow}</span><h2>{c.soilTitle}</h2><p>{c.soilBody}</p><p>{soilScopeNote[locale]}</p></div><div className="soil-guide-grid">{matches.map(guide=><article key={guide.title.en}><Layers3/><h3>{guide.title[locale]}</h3><dl><div><dt>{c.water}</dt><dd>{guide.water[locale]}</dd></div><div><dt>{c.root}</dt><dd>{guide.root[locale]}</dd></div></dl></article>)}</div></div>}
  </section>
}

export function GrapeDeepDive({grape,locale}:{grape:Grape;locale:Locale}){
  const c=depthCopy[locale]
  const evidenceFields=grapeEvidenceContent(grape.id,locale)
  const fieldCopy={
    en:{field:'Vine and fruit observations',empty:'Compare mature leaves, bunches and berries together; one feature alone cannot identify a grape variety.',structureTitle:'Read structure in the glass',structureBody:'Taste two wines side by side at the same serving temperature. Record acidity, tannin texture, body and finish; site, vintage and winemaking can shift each one.'},
    de:{field:'Beobachtungen an Rebe und Frucht',empty:'Vergleiche ausgewachsene Blätter, Trauben und Beeren gemeinsam; ein einzelnes Merkmal bestimmt keine Rebsorte.',structureTitle:'Struktur im Glas lesen',structureBody:'Verkoste zwei Weine bei gleicher Serviertemperatur nebeneinander. Notiere Säure, Tannintextur, Körper und Nachhall; Lage, Jahrgang und Ausbau können jeden Eindruck verändern.'},
    fr:{field:'Observations sur la vigne et le fruit',empty:'Comparez ensemble feuilles adultes, grappes et baies ; un seul caractère ne suffit pas à identifier un cépage.',structureTitle:'Lire la structure dans le verre',structureBody:'Goûtez deux vins côte à côte, à la même température de service. Notez acidité, texture des tanins, corps et finale ; site, millésime et élaboration peuvent modifier chacun de ces aspects.'},
    es:{field:'Observaciones de la vid y el fruto',empty:'Compara hojas adultas, racimos y bayas en conjunto; un solo rasgo no basta para identificar una variedad.',structureTitle:'Leer la estructura en la copa',structureBody:'Prueba dos vinos en paralelo y a la misma temperatura de servicio. Anota acidez, textura del tanino, cuerpo y final; lugar, añada y elaboración pueden cambiar cada aspecto.'},
  }[locale]
  const fieldNote=evidenceFields?`${evidenceFields.growth} ${evidenceFields.risk}`:fieldCopy.empty
  return <section className="grape-deep-dive"><div className="depth-heading"><span className="eyebrow">{c.grapeEyebrow}</span><h2>{c.grapeTitle}</h2></div><div className="climate-comparison"><article><GrapeIcon/><span>{fieldCopy.field}</span><p>{fieldNote}</p></article></div><aside className="structure-compass"><h3>{fieldCopy.structureTitle}</h3><p>{fieldCopy.structureBody}</p></aside></section>
}

const ampelographyProfiles:Record<string,{leaf:string;cluster:string;berry:string;growth:string;risk:string}>={
  riesling:{leaf:'small-to-medium, round and often five-lobed, with a distinctly coarse, blistered surface and overlapping petiolar sinus','cluster':'small, compact and usually cylindrical, sometimes with a short wing','berry':'small, round, yellow-green and dotted at full maturity; the skin remains relatively firm','growth':'upright growth, comparatively hard wood and early budbreak followed by late ripening','risk':'early buds are frost-exposed; compact bunches can invite botrytis, although healthy noble rot is valuable for sweet styles'},
  chardonnay:{leaf:'medium, broadly orbicular and only lightly lobed; the open petiolar sinus is often bordered by nearly naked veins','cluster':'small-to-medium, cylindrical and moderately compact, frequently shouldered','berry':'small, round and thin-skinned, changing from green to golden amber in exposed sites','growth':'early budbreak and early ripening with vigorous shoot growth when water and nitrogen are abundant','risk':'spring frost, coulure or millerandage around flowering, powdery mildew and botrytis in tight bunches'},
  'cabernet-sauvignon':{leaf:'medium, deeply five-lobed, with characteristic overlapping lobes that make the blade look almost perforated','cluster':'small-to-medium, conical, loose-to-moderately compact and often winged','berry':'small, spherical, blue-black and thick-skinned, with a high skin-to-juice ratio','growth':'upright and vigorous, late budding and late ripening; lignification and exposure matter in cool seasons','risk':'late maturity can leave pyrazine-led green character; drought, trunk disease and poor fruit set require site-specific management'},
  'pinot-noir':{leaf:'small-to-medium, thick and round with three to five shallow lobes and a slightly bullate surface','cluster':'small, compact and pine-cone shaped—the source of the Pinot name','berry':'small, spherical, thin-skinned and blue-black, packed closely within the bunch','growth':'early budding and early ripening, with compact architecture and modest natural fertility','risk':'spring frost, millerandage, botrytis and bunch rot; thin skins make handling and extraction especially consequential'},
  'sauvignon-blanc':{leaf:'small-to-medium, round and markedly lobed, with a blistered upper surface and wavy margins','cluster':'small-to-medium, cylindrical, compact and often winged','berry':'small, green-yellow and thick enough to retain aromatic precursors, becoming spotted with sun exposure','growth':'vigorous and often sprawling, early-to-mid budding and mid-season ripening','risk':'vigour can shade fruit and preserve overt green notes; compact bunches are vulnerable to botrytis and powdery mildew'},
  syrah:{leaf:'medium, three-to-five lobed with a distinctly open petiolar sinus and fine down on the underside','cluster':'small-to-medium, elongated, cylindrical-conical and moderately compact','berry':'small, oval, blue-black and relatively thick-skinned','growth':'long, fragile shoot tips and semi-erect growth; mid budding and mid-to-late ripening','risk':'wind damage, drought stress, poor flowering in cold conditions and Syrah decline; exposed berries can shrivel in extreme heat'},
  nebbiolo:{leaf:'medium-to-large, pentagonal and deeply lobed, with a strongly blistered surface and downy underside','cluster':'medium-to-large, elongated, winged and moderately compact','berry':'medium, round-to-ellipsoid, blue-violet with abundant bloom and comparatively thin skin','growth':'vigorous, early budding and very late ripening; the long season makes aspect decisive','risk':'spring frost, rain or fog near harvest, uneven set and delayed lignification on poorly exposed sites'},
  sangiovese:{leaf:'medium, three-to-five lobed and longer than wide, with pronounced upper lateral sinuses','cluster':'medium-to-large, cylindrical-conical, winged and moderately compact','berry':'medium, oval, blue-violet with a moderately thick skin','growth':'vigorous and productive with mid budding and late ripening; clonal diversity changes bunch architecture','risk':'uneven ripening, botrytis in compact material, drought stress and dilution when crop load exceeds site capacity'},
  'grenache-garnacha':{leaf:'medium, wedge-shaped and five-lobed, with a smooth surface and noticeably hairless underside','cluster':'medium-to-large, conical, winged and moderately compact','berry':'medium, round, blue-black and relatively thin-skinned despite its warm-climate adaptation','growth':'upright, very vigorous and wind-resistant, with early budding and late ripening','risk':'coulure, downy mildew, trunk disease and rapid sugar accumulation in hot conditions; old bush vines limit vigour naturally'},
  tempranillo:{leaf:'large, pentagonal and five-lobed, with a blistered surface and a woolly underside','cluster':'medium-to-large, cylindrical-conical, winged and compact','berry':'medium, round, blue-black and moderately thick-skinned','growth':'upright-to-semi-erect, early ripening as its name suggests, with relatively short seasonal cycle','risk':'drought can stop ripening, while compact bunches raise botrytis risk; fertility and yields need active control'},
  'chenin-blanc':{leaf:'medium, round and three-to-five lobed, with a blistered surface and reddish veins near the petiole','cluster':'medium, conical, winged and compact','berry':'small-to-medium, oval, yellow-green and thin-skinned, often taking amber freckles','growth':'early budding and late ripening, naturally vigorous and capable of high acidity across a long season','risk':'spring frost, uneven maturity within the bunch, sunburn and botrytis—the last can be either fault or asset depending on style'},
  malbec:{leaf:'medium, round to pentagonal and usually three-lobed, with a broad open petiolar sinus','cluster':'medium, loose-to-moderately compact and broadly conical','berry':'medium, round, blue-black and comparatively thin-skinned','growth':'upright but brittle, early budding and mid-season ripening with sensitivity around flowering','risk':'spring frost, coulure, downy mildew and trunk disease; altitude and sunlight can thicken skins and deepen colour'},
}

function ampelographyText(grape:Grape,locale:Locale){
  const sourced=grapeEvidenceContent(grape.id,locale)
  if(sourced)return sourced
  const exact=ampelographyProfiles[grape.id]
  const fallback={
    leaf:`A mature ${grape.name} leaf should be read through blade shape, lobe depth, petiolar sinus, teeth, surface blistering and the density of hairs beneath. Compare several healthy mid-shoot leaves; one leaf is never enough for identification.`,
    cluster:`Record bunch size, winging and compactness at full maturity. ${grape.ripening} changes the field date on which that comparison is meaningful.`,
    berry:`Observe berry size and shape, skin colour, bloom, skin toughness, seed maturity and how tightly berries touch. ${grape.color==='red'?'Dark skin alone does not distinguish cultivars.':'Sun exposure can shift green fruit toward gold or amber without changing the cultivar.'}`,
    growth:`${grape.viticulture} Shoot posture, internode length, tendrils, vigour and timing of budbreak add evidence beyond the fruit.`,
    risk:`Use the plate as an observation protocol, not a positive cultivar diagnosis. Virus status, clone, rootstock, water and canopy can alter appearance; confirm uncertain material with certified records or DNA.`
  }
  const source=exact??fallback
  if(locale==='en') return source
  const timing=grapeContent(grape,locale).ripening.replace(/[.!?]+$/,'').toLowerCase()
  return {
    de:{leaf:`Ein reifes Blatt von ${grape.name} wird über Form, Lappung, Stielbucht, Zähne, Blasigkeit und Behaarung der Unterseite gelesen. Mehrere gesunde Blätter aus der mittleren Triebzone vergleichen – ein Einzelblatt genügt nie.`,cluster:`Größe, Schulterung und Kompaktheit der Traube bei voller Reife erfassen. Der Reifezeitpunkt „${timing}“ bestimmt, wann der Vergleich im Feld sinnvoll ist.`,berry:`Beerengröße und -form, Schalenfarbe, Bereifung, Festigkeit, Kernreife und den Kontakt zwischen den Beeren prüfen. ${grape.color==='red'?'Eine dunkle Schale allein identifiziert keine Rebsorte.':'Sonne kann grüne Beeren goldgelb färben, ohne die Sortenidentität zu ändern.'}`,growth:`Triebhaltung, Internodien, Ranken, Wuchskraft und Austriebszeit liefern neben der Frucht weitere Indizien. Im Weinberg zählen außerdem Laubwand, Ertrag und gleichmäßige Reife.`,risk:'Die Tafel ist ein Beobachtungsprotokoll, keine sichere Sortendiagnose. Klon, Unterlage, Wasser, Virusstatus und Laubwand verändern das Bild; unklare Reben über Pflanzunterlagen oder DNA bestätigen.'},
    fr:{leaf:`Une feuille adulte de ${grape.name} se lit par la forme, les lobes, le sinus pétiolaire, les dents, la gaufrure et le duvet inférieur. Comparez plusieurs feuilles saines : une seule ne suffit jamais.`,cluster:`Notez taille, ailes et compacité à pleine maturité. Le rythme « ${timing} » détermine le bon moment d’observation.`,berry:`Observez taille, forme, couleur, pruine, résistance de la peau, pépins et contact entre baies. ${grape.color==='red'?'La pellicule foncée seule n’identifie pas un cépage.':'Le soleil peut faire passer le vert à l’or sans changer l’identité du cépage.'}`,growth:'Port des rameaux, entre-nœuds, vrilles, vigueur et date de débourrement ajoutent des indices au fruit. Feuillage, charge et homogénéité de maturité complètent la lecture.',risk:'Cette planche est un protocole d’observation, non un diagnostic. Clone, porte-greffe, eau, viroses et feuillage changent l’aspect ; confirmez par les registres ou l’ADN.'},
    es:{leaf:`Una hoja adulta de ${grape.name} se lee por forma, lóbulos, seno peciolar, dientes, abullonado y vello inferior. Compara varias hojas sanas: una sola nunca basta.`,cluster:`Registra tamaño, alas y compacidad en madurez plena. El ritmo «${timing}» determina el momento útil de comparación.`,berry:`Observa tamaño, forma, color, pruina, dureza de piel, semillas y contacto entre bayas. ${grape.color==='red'?'La piel oscura por sí sola no identifica la variedad.':'El sol puede llevar el verde al dorado sin cambiar la identidad varietal.'}`,growth:'Porte, entrenudos, zarcillos, vigor y fecha de brotación aportan evidencia además del fruto. Vegetación, carga y uniformidad de madurez completan la lectura.',risk:'La lámina es un protocolo de observación, no un diagnóstico. Clon, portainjerto, agua, virus y vegetación cambian el aspecto; confirma con registros o ADN.'}
  }[locale]
}

export function GrapeAmpelography({grape,locale}:{grape:Grape;locale:Locale}){
  const copy={en:{eyebrow:'Ampelography field plate',title:'Read the vine before the label',leaf:'Mature leaf',cluster:'Cluster architecture',berry:'Berry & skin',growth:'Growth habit',risk:'Field risks',note:'Reliable identification compares the shoot tip, mature leaf, cluster and berry together. Season, rootstock and vine health can alter any single feature, so ampelographers confirm the pattern across several organs.'},de:{eyebrow:'Ampelografische Feldtafel',title:'Die Rebe vor dem Etikett lesen',leaf:'Ausgewachsenes Blatt',cluster:'Traubenarchitektur',berry:'Beere & Schale',growth:'Wuchsverhalten',risk:'Risiken im Feld',note:'Eine belastbare Bestimmung vergleicht Triebspitze, ausgewachsenes Blatt, Traube und Beere gemeinsam. Saison, Unterlage und Rebengesundheit können einzelne Merkmale verändern; Ampelografen bestätigen deshalb das Muster über mehrere Organe.'},fr:{eyebrow:'Planche ampélographique',title:'Lire la vigne avant l’étiquette',leaf:'Feuille adulte',cluster:'Architecture de grappe',berry:'Baie et pellicule',growth:'Port végétatif',risk:'Risques au vignoble',note:'Une identification fiable compare ensemble l’apex, la feuille adulte, la grappe et la baie. La saison, le porte-greffe et la santé de la vigne peuvent modifier un caractère isolé ; l’ampélographe confirme donc le faisceau d’indices sur plusieurs organes.'},es:{eyebrow:'Lámina ampelográfica',title:'Lee la vid antes de la etiqueta',leaf:'Hoja adulta',cluster:'Arquitectura del racimo',berry:'Baya y piel',growth:'Porte vegetativo',risk:'Riesgos de campo',note:'Una identificación fiable compara a la vez el ápice, la hoja adulta, el racimo y la baya. La temporada, el portainjerto y la salud de la vid pueden alterar un rasgo aislado; por eso la ampelografía confirma el patrón en varios órganos.'}}[locale]
  const profile=ampelographyText(grape,locale)
  const media=ampelographyMedia.find(item=>item.grapeId===grape.id)
  if(!media)return null
  const mediaCopy={en:{leaf:'Mature leaf',cluster:'Cluster at maturity',comparison:'Leaf · shoot · cluster · berry'},de:{leaf:'Ausgewachsenes Blatt',cluster:'Reife Traube',comparison:'Blatt · Trieb · Traube · Beere'},fr:{leaf:'Feuille adulte',cluster:'Grappe à maturité',comparison:'Feuille · rameau · grappe · baie'},es:{leaf:'Hoja adulta',cluster:'Racimo maduro',comparison:'Hoja · brote · racimo · baya'}}[locale]
  const items=[['leaf',copy.leaf],['cluster',copy.cluster],['berry',copy.berry],['growth',copy.growth],['risk',copy.risk]] as const
  return <section className="ampelography-plate"><figure><div className="ampelography-photo-pair"><figure><img src={media.leafUrl} alt={`${grape.name} · ${mediaCopy.leaf}`} loading="lazy" referrerPolicy="no-referrer"/><figcaption>01 · {mediaCopy.leaf}</figcaption></figure><figure><img src={media.clusterUrl} alt={`${grape.name} · ${mediaCopy.cluster}`} loading="lazy" referrerPolicy="no-referrer"/><figcaption>02 · {mediaCopy.cluster}</figcaption></figure></div><figcaption>{copy.note}</figcaption></figure><div><div className="depth-heading"><span className="eyebrow">{copy.eyebrow}</span><h2>{copy.title}</h2></div><dl>{items.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{profile[key]}</dd></div>)}</dl></div></section>
}

export function ProducerDecisionMap({producer,region,locale}:{producer:Producer;region:Region;locale:Locale}){
  const c=depthCopy[locale],p=producerContent(producer,region,locale),r=regionContent(region,locale)
  const decisions=[
    {title:c.site,icon:Mountain,text:[p.vineyard,r.soil].filter(value=>value.trim()).join(' ')},
    {title:c.harvest,icon:SunMedium,text:r.growingSeason},
    {title:c.cellar,icon:FlaskConical,text:p.cellar},
  ].filter(item=>item.text.trim())
  if(!decisions.length)return null
  return <section className="producer-decision-map"><div className="depth-heading"><span className="eyebrow">{c.producerEyebrow}</span><h2>{c.producerTitle}</h2></div><ol>{decisions.map((decision,index)=>{const DecisionIcon=decision.icon;return <li key={decision.title}><span>{String(index+1).padStart(2,'0')}</span><DecisionIcon/><div><h3>{decision.title}</h3><p>{decision.text}</p></div></li>})}</ol></section>
}

export function WineEvolutionLesson({wine,locale}:{wine:Wine;locale:Locale}){
  const [active,setActive]=useState(0)
  const c=depthCopy[locale],producer=producers.find(entry=>entry.id===wine.producerId)!,region=regions.find(entry=>entry.id===wine.regionId)!,content=wineContent(wine,producer,region,locale)
  const service=content.serving.replace(/[.!?]+$/,'')
  const sequences={en:[['At opening',`${service}. Note fruit, reduction or oak before deciding whether the wine needs air.`],['With air',`Watch whether aroma separates, tannin relaxes and acidity becomes clearer. Air reveals structure; it cannot repair imbalance.`],['At the table',content.pairings.join(' · ')],['Across the drinking window',content.drinkWindow]],de:[['Beim Öffnen',`${service}. Notiere Frucht, Reduktion oder Holz, bevor du über mehr Luft entscheidest.`],['Mit Luft','Beobachte, ob sich Aromen trennen, Tannin entspannt und Säure klarer wird. Luft zeigt Struktur; sie repariert kein Ungleichgewicht.'],['Am Tisch',content.pairings.join(' · ')],['Im Trinkfenster',content.drinkWindow]],fr:[['À l’ouverture',`${service}. Notez fruit, réduction ou bois avant de décider de l’aération.`],['Avec l’air','Observez si les arômes se séparent, les tanins se détendent et l’acidité se précise. L’air révèle ; il ne répare pas.'],['À table',content.pairings.join(' · ')],['Dans sa fenêtre',content.drinkWindow]],es:[['Al abrir',`${service}. Anota fruta, reducción o roble antes de decidir si necesita aire.`],['Con aire','Observa si los aromas se separan, el tanino se relaja y la acidez gana claridad. El aire revela; no corrige.'],['En la mesa',content.pairings.join(' · ')],['En su ventana',content.drinkWindow]]}[locale]
  const bottleFormsCaption={en:'Examples of common wine-bottle forms',de:'Beispiele gängiger Weinflaschenformen',fr:'Exemples de formes courantes de bouteilles',es:'Ejemplos de formas habituales de botella'}[locale]
  const bottleFormsAlt={en:'Illustrated comparison of Bordeaux, Burgundy, Rhine and sparkling wine bottles',de:'Illustrierter Vergleich von Bordeaux-, Burgunder-, Rhein- und Schaumweinflaschen',fr:'Comparaison illustrée de bouteilles bordelaises, bourguignonnes, rhénanes et effervescentes',es:'Comparación ilustrada de botellas bordelesas, borgoñonas, renanas y espumosas'}[locale]
  return <section className="wine-evolution-lesson is-interactive"><figure><img className="wine-bottle-forms" src={bottleFormsPlate} alt={bottleFormsAlt}/><figcaption><strong>{c.shape}</strong><span>{c.shapeBody}</span><small>{bottleFormsCaption}</small></figcaption></figure><div><div className="depth-heading"><span className="eyebrow">{c.wineEyebrow}</span><h2>{c.wineTitle}</h2></div><div className="evolution-tabs" role="group" aria-label={c.wineTitle}>{sequences.map(([title],index)=><button type="button" aria-pressed={active===index} className={active===index?'active':''} key={title} onClick={()=>setActive(index)}><span>0{index+1}</span>{title}</button>)}</div><article className="evolution-reading" aria-live="polite"><small>{sequences[active][0]}</small><p>{sequences[active][1]}</p></article></div></section>
}

export function AcademyMasterclass({article,locale}:{article:Article;locale:Locale}){
  const c=depthCopy[locale],region=regions.find(entry=>article.relatedRegionIds.includes(entry.id)),grape=grapes.find(entry=>article.relatedGrapeIds.includes(entry.id))
  const heading={en:{eyebrow:'Five lenses for practice',title:'Test the idea at the table'},de:{eyebrow:'Fünf Blickwinkel für die Praxis',title:'Die Idee am Tisch prüfen'},fr:{eyebrow:'Cinq angles de pratique',title:'Mettre l’idée à l’épreuve à table'},es:{eyebrow:'Cinco enfoques para practicar',title:'Pon la idea a prueba en la mesa'}}[locale]
  const text={en:{myth:'A single rule explains every wine. In practice, vintage, site, material and intention interact.',mechanism:`Explain ${article.title.toLowerCase()} as a chain of choices, then name the sensory evidence each step could leave.`,comparison:`Keep one variable steady: compare two wines from ${region?.name??'one region'} or two expressions of ${grape?.name??'one grape'}.`,practice:'Describe first, interpret second. Write three observations before naming cause or quality.',question:'What observation would prove your first explanation wrong?'},de:{myth:'Eine einzelne Regel erklärt jeden Wein. Tatsächlich wirken Jahrgang, Standort, Material und Absicht zusammen.',mechanism:`Erkläre „${article.title}“ als Kette von Entscheidungen und nenne für jeden Schritt mögliche sensorische Spuren.`,comparison:`Halte eine Variable konstant: Vergleiche zwei Weine aus ${region?.name??'einer Region'} oder zwei Ausprägungen von ${grape?.name??'einer Rebsorte'}.`,practice:'Erst beschreiben, dann deuten. Notiere drei Beobachtungen, bevor du Ursache oder Qualität benennst.',question:'Welche Beobachtung würde deine erste Erklärung widerlegen?'},fr:{myth:'Une règle unique n’explique jamais tous les vins. Millésime, lieu, matière et intention interagissent.',mechanism:`Expliquez « ${article.title} » comme une chaîne de choix et reliez chaque étape à une trace sensorielle possible.`,comparison:`Gardez une variable constante : deux vins de ${region?.name??'la même région'} ou deux expressions de ${grape?.name??'un même cépage'}.`,practice:'Décrire avant d’interpréter. Notez trois observations avant de nommer cause ou qualité.',question:'Quelle observation réfuterait votre première explication ?'},es:{myth:'Una sola regla no explica todos los vinos. Añada, lugar, material e intención interactúan.',mechanism:`Explica «${article.title}» como cadena de decisiones y relaciona cada paso con una huella sensorial.`,comparison:`Mantén una variable: dos vinos de ${region?.name??'la misma región'} o dos expresiones de ${grape?.name??'una variedad'}.`,practice:'Describe antes de interpretar. Anota tres observaciones antes de nombrar causa o calidad.',question:'¿Qué observación demostraría que tu primera explicación es incorrecta?'}}[locale]
  const rows=[['myth',c.myth],['mechanism',c.mechanism],['comparison',c.comparison],['practice',c.practice],['question',c.question]] as const
  return <section className="academy-masterclass"><div className="depth-heading"><span className="eyebrow">{heading.eyebrow}</span><h2>{heading.title}</h2></div><div>{rows.map(([key,label],index)=><article key={key}><span>0{index+1}</span><h3>{label}</h3><p>{text[key]}</p></article>)}</div><aside><Route/><strong>{c.connections}</strong>{region&&<Link to={`/regions/${region.id}`}>{regionName(region,locale)}<ArrowRight/></Link>}{grape&&<Link to={`/grapes/${grape.id}`}>{grape.name}<ArrowRight/></Link>}</aside></section>
}
