import { useState } from 'react'
import { CircleGauge, Droplets, Focus, GlassWater, ShieldCheck, Wine } from 'lucide-react'
import type { Locale } from './i18n'

type LabId='glassware-anatomy'|'bottle-closures'|'bottle-anatomy'

const copy={
  en:{lab:'Practical object lab',compare:'Change one object. Keep the wine constant.',pour:'Measured pour',headspace:'Aroma headspace',focus:'Rim focus',temperature:'Temperature stability',why:'What changes',watch:'What to observe',use:'Typical use',notScore:'This is a functional comparison, not a quality ranking.',glass:{universal:['Universal tulip','Balanced headspace and a narrowing rim make this the most useful starting point.','Aroma definition, swirl control and temperature over ten minutes.'],burgundy:['Broad bowl','More surface and headspace can expand aroma, while the open shape may disperse it sooner.','Compare aromatic breadth with alcohol lift at the same pour.'],sparkling:['Sparkling tulip','A narrower bowl supports a visible bead while leaving more aroma room than a flute.','Mousse, bead, aroma release and warming rate.'],fortified:['Small tulip','A smaller chamber and pour suit stronger or sweeter wines without requiring a tiny closed rim.','Alcohol delivery, sweetness, intensity and portion size.']},closure:{natural:['Natural cork','Compressed cellular bark; individual pieces can vary.','Seal condition, fill level, extraction, bottle variation.','Still wines intended for short or long development.'],technical:['Technical cork','Engineered cork components aim for more consistent physical performance.','Product specification, seal integrity and bottle evolution.','Still wines where cork extraction and consistency are desired.'],screw:['Screw cap','An aluminium shell and liner form the seal; liner specification matters.','Liner, thread damage, reduction, fill level and storage.','Still wines across many styles and ageing ambitions.'],sparkling:['Sparkling cork','A pressure closure restrained by a wire cage and compressed in the neck.','Temperature, cage, cork movement and safe opening.','Bottle-fermented and other pressurised wines.'],glass:['Glass stopper','A rigid glass closure uses a separate sealing ring.','Ring condition, intact neck and clean resealing.','Still wines designed for this matched neck system.']},bottle:{bordeaux:['Bordeaux shoulders','Pronounced shoulders can help retain sediment during a controlled pour.','Stand mature bottles upright and watch the sediment line.'],burgundy:['Burgundy slope','Sloping shoulders reflect regional handling traditions rather than a quality tier.','Pour slowly; do not expect the shape to trap sediment.'],rhine:['Rhine flute','A tall, slender form historically associated with Rhine and neighbouring wine routes.','Stability, storage height and fill level—not presumed sweetness.'],sparkling:['Pressure bottle','Thicker walls, a pressure closure and a strong base manage internal pressure.','Chill fully, inspect damage and keep control of the closure.']}},
  de:{lab:'Praxislabor',compare:'Ändere ein Objekt. Der Wein bleibt gleich.',pour:'Abgemessene Füllmenge',headspace:'Aromatischer Kopfraum',focus:'Bündelung am Rand',temperature:'Temperaturstabilität',why:'Was sich verändert',watch:'Was du beobachtest',use:'Typischer Einsatz',notScore:'Das ist ein Funktionsvergleich, keine Qualitätsrangliste.',glass:{universal:['Universal-Tulpe','Ausgewogener Kopfraum und ein engerer Rand machen sie zum sinnvollsten Ausgangspunkt.','Aromenkontur, sichere Kreisbewegung und Temperatur über zehn Minuten.'],burgundy:['Breiter Kelch','Mehr Oberfläche und Kopfraum können Aromen öffnen; die breite Form kann sie auch schneller verteilen.','Aromatische Breite und Alkoholwirkung bei identischer Füllmenge.'],sparkling:['Schaumwein-Tulpe','Der engere Kelch zeigt die Perlage und lässt mehr Aromaraum als eine schmale Flöte.','Mousse, Perlage, Duftfreisetzung und Erwärmung.'],fortified:['Kleine Tulpe','Kleiner Raum und kleinere Portion passen zu stärkeren oder süßeren Weinen.','Alkoholwirkung, Süße, Intensität und Portionsgröße.']},closure:{natural:['Naturkork','Komprimierte Zellstruktur aus Rinde; einzelne Stücke können variieren.','Dichtsitz, Füllstand, Auszug und Flaschenvariation.','Stillweine mit kurzer oder langer Entwicklungsabsicht.'],technical:['Technischer Kork','Technisch verarbeitete Korkbestandteile zielen auf gleichmäßigere Eigenschaften.','Produktspezifikation, Dichtsitz und Flaschenentwicklung.','Stillweine, bei denen Korkgefühl und Konsistenz gewünscht sind.'],screw:['Schraubverschluss','Aluminiumkapsel und Einlage bilden die Dichtung; die Einlage ist entscheidend.','Einlage, Gewinde, Reduktion, Füllstand und Lagerung.','Stillweine vieler Stile und Reifeziele.'],sparkling:['Schaumweinkork','Druckverschluss, der im Flaschenhals komprimiert und durch eine Agraffe gesichert wird.','Temperatur, Agraffe, Korkbewegung und sicheres Öffnen.','Flaschenvergorene und andere druckhaltige Weine.'],glass:['Glasverschluss','Ein starrer Glasstopfen dichtet über einen separaten Ring.','Ring, unbeschädigter Hals und sauberes Wiederverschließen.','Stillweine mit passendem Flaschenhalssystem.']},bottle:{bordeaux:['Bordeaux-Schulter','Ausgeprägte Schultern können Depot beim kontrollierten Einschenken zurückhalten.','Gereifte Flaschen aufstellen und die Depotlinie beobachten.'],burgundy:['Burgunderform','Schräge Schultern erzählen regionale Handhabungsgeschichte, keine Qualitätsstufe.','Langsam gießen; die Form hält Depot kaum zurück.'],rhine:['Rheinflöte','Hohe, schlanke Form mit historischer Verbindung zu Rhein und benachbarten Handelswegen.','Standfestigkeit, Lagerhöhe und Füllstand – nicht vermutete Süße.'],sparkling:['Druckflasche','Stärkere Wand, Druckverschluss und stabiler Boden beherrschen den Innendruck.','Vollständig kühlen, Schäden prüfen und den Verschluss sichern.']}},
  fr:{lab:'Laboratoire pratique',compare:'Changez un objet. Gardez le même vin.',pour:'Volume mesuré',headspace:'Espace aromatique',focus:'Concentration au buvant',temperature:'Stabilité thermique',why:'Ce qui change',watch:'À observer',use:'Usage courant',notScore:'Comparaison fonctionnelle, pas classement de qualité.',glass:{universal:['Tulipe universelle','Espace équilibré et buvant resserré en font le meilleur point de départ.','Définition aromatique, rotation et température sur dix minutes.'],burgundy:['Calice large','Plus de surface et d’espace peuvent ouvrir le nez, mais aussi le disperser plus vite.','Largeur aromatique et chaleur alcoolique à volume égal.'],sparkling:['Tulipe effervescente','Le calice étroit montre la bulle tout en offrant plus d’espace qu’une flûte.','Mousse, bulle, arôme et réchauffement.'],fortified:['Petite tulipe','Petit volume et petite dose conviennent aux vins plus forts ou doux.','Alcool, douceur, intensité et portion.']},closure:{natural:['Liège naturel','Écorce cellulaire comprimée; chaque pièce peut varier.','Étanchéité, niveau, extraction et variation entre bouteilles.','Vins tranquilles destinés à évoluer.'],technical:['Liège technique','Composants de liège conçus pour une performance plus régulière.','Spécification, étanchéité et évolution.','Vins tranquilles recherchant geste du liège et constance.'],screw:['Capsule à vis','Coque aluminium et joint forment l’étanchéité; le joint compte.','Joint, filetage, réduction, niveau et stockage.','Nombreux styles et ambitions de garde.'],sparkling:['Bouchon d’effervescent','Bouchon sous pression comprimé et retenu par un muselet.','Température, muselet, mouvement et ouverture sûre.','Vins en bouteille sous pression.'],glass:['Bouchon de verre','Verre rigide et bague d’étanchéité séparée.','Bague, col intact et refermeture propre.','Vins tranquilles avec col adapté.']},bottle:{bordeaux:['Épaules bordelaises','Les épaules marquées peuvent retenir le dépôt pendant un service contrôlé.','Redresser la bouteille et suivre la ligne de dépôt.'],burgundy:['Pente bourguignonne','Les épaules inclinées relèvent d’une histoire pratique, pas d’un rang.','Verser lentement sans attendre que la forme retienne le dépôt.'],rhine:['Flûte rhénane','Forme haute liée historiquement au Rhin et aux routes voisines.','Stabilité, hauteur de stockage et niveau – pas douceur supposée.'],sparkling:['Bouteille de pression','Parois fortes, bouchage et base résistent à la pression interne.','Refroidir, vérifier le verre et garder le bouchon maîtrisé.']}},
  es:{lab:'Laboratorio práctico',compare:'Cambia un objeto. Mantén el mismo vino.',pour:'Volumen medido',headspace:'Espacio aromático',focus:'Concentración en el borde',temperature:'Estabilidad térmica',why:'Qué cambia',watch:'Qué observar',use:'Uso habitual',notScore:'Comparación funcional, no clasificación de calidad.',glass:{universal:['Tulipa universal','Espacio equilibrado y borde estrecho: el punto de partida más útil.','Definición aromática, giro y temperatura durante diez minutos.'],burgundy:['Cáliz amplio','Más superficie y espacio pueden abrir el aroma y también dispersarlo antes.','Amplitud aromática y calor del alcohol con igual volumen.'],sparkling:['Tulipa espumosa','El cáliz estrecho muestra la burbuja con más espacio que una flauta.','Espuma, burbuja, aroma y calentamiento.'],fortified:['Tulipa pequeña','Cámara y porción menores sirven a vinos más fuertes o dulces.','Alcohol, dulzor, intensidad y porción.']},closure:{natural:['Corcho natural','Corteza celular comprimida; cada pieza puede variar.','Sellado, nivel, extracción y variación de botella.','Vinos tranquilos con intención de desarrollo.'],technical:['Corcho técnico','Componentes de corcho diseñados para mayor regularidad.','Especificación, sellado y evolución.','Vinos tranquilos que buscan gesto de corcho y consistencia.'],screw:['Rosca','Carcasa de aluminio y junta forman el sello; importa la junta.','Junta, rosca, reducción, nivel y guarda.','Muchos estilos y objetivos de crianza.'],sparkling:['Tapón de espumoso','Cierre a presión comprimido y sujeto por bozal.','Temperatura, bozal, movimiento y apertura segura.','Vinos embotellados bajo presión.'],glass:['Cierre de vidrio','Vidrio rígido con un anillo de sellado separado.','Anillo, cuello intacto y cierre limpio.','Vinos tranquilos con cuello compatible.']},bottle:{bordeaux:['Hombros bordeleses','Los hombros marcados ayudan a retener sedimento durante un vertido controlado.','Poner de pie la botella y vigilar la línea de sedimento.'],burgundy:['Pendiente borgoñona','Los hombros inclinados reflejan historia de uso, no una categoría.','Servir despacio sin esperar que la forma atrape sedimento.'],rhine:['Flauta renana','Forma alta vinculada históricamente al Rin y rutas vecinas.','Estabilidad, altura de guarda y nivel, no dulzor supuesto.'],sparkling:['Botella de presión','Paredes fuertes, cierre y base resisten la presión interna.','Enfriar, revisar daños y controlar el cierre.']}},
} as const

type GlassShape='universal'|'burgundy'|'sparkling'|'fortified'
type GlassQuality={size:string;headspace:string;pour:readonly [string,string,string]}

const pourLevels:Record<Locale,readonly [string,string,string]>={
  en:['Small pour','Standard pour','Generous pour'],
  de:['Kleine Portion','Standardportion','Große Portion'],
  fr:['Petit service','Service standard','Service généreux'],
  es:['Servicio pequeño','Servicio estándar','Servicio generoso'],
}

const qualityLabels:Record<Locale,{size:string;headspace:string;pour:string}>={
  en:{size:'Bowl size',headspace:'Headspace',pour:'Pour relationship'},
  de:{size:'Kelchgröße',headspace:'Kopfraum',pour:'Verhältnis zur Portion'},
  fr:{size:'Taille du calice',headspace:'Espace au-dessus du vin',pour:'Effet du service'},
  es:{size:'Tamaño del cáliz',headspace:'Espacio sobre el vino',pour:'Efecto del servicio'},
}

const glassQualities:Record<Locale,Record<GlassShape,GlassQuality>>={
  en:{
    universal:{size:'Middle-width bowl in this set',headspace:'Balanced at a standard pour',pour:['A small pour leaves the bowl open','A standard pour is the baseline','A generous pour brings the wine closer to the rim']},
    burgundy:{size:'Widest bowl in this set',headspace:'Most open space at a small pour',pour:['A small pour leaves the most room above the wine','A standard pour keeps a broad aromatic surface','A generous pour reduces the open space']},
    sparkling:{size:'Narrow tulip bowl',headspace:'More open space than a flute',pour:['A small pour leaves room for mousse and aroma','A standard pour keeps the bead visible','A generous pour leaves less room above the wine']},
    fortified:{size:'Smallest bowl in this set',headspace:'Less open space by design',pour:['A small pour keeps alcohol and sweetness measured','A standard pour balances aroma and intensity','A generous pour brings alcohol and sweetness forward']},
  },
  de:{
    universal:{size:'Mittlere Kelchbreite in diesem Set',headspace:'Ausgewogener Kopfraum bei Standardportion',pour:['Eine kleine Portion lässt den Kelch offen','Die Standardportion dient als Vergleich','Eine große Portion bringt den Wein näher an den Rand']},
    burgundy:{size:'Breitester Kelch in diesem Set',headspace:'Bei kleiner Portion am meisten freier Raum',pour:['Eine kleine Portion lässt den meisten Raum über dem Wein','Die Standardportion bewahrt eine breite Aromafläche','Eine große Portion verkleinert den freien Raum']},
    sparkling:{size:'Schmaler Tulpenkelch',headspace:'Mehr freier Raum als in einer Flöte',pour:['Eine kleine Portion lässt Raum für Mousse und Duft','Die Standardportion hält die Perlage sichtbar','Eine große Portion lässt weniger Raum über dem Wein']},
    fortified:{size:'Kleinster Kelch in diesem Set',headspace:'Absichtlich weniger freier Raum',pour:['Eine kleine Portion hält Alkohol und Süße im Maß','Die Standardportion balanciert Duft und Intensität','Eine große Portion bringt Alkohol und Süße nach vorn']},
  },
  fr:{
    universal:{size:'Calice de largeur intermédiaire ici',headspace:'Espace équilibré avec un service standard',pour:['Un petit service laisse le calice ouvert','Le service standard sert de repère','Un service généreux rapproche le vin du bord']},
    burgundy:{size:'Calice le plus large ici',headspace:'Espace maximal avec un petit service',pour:['Un petit service laisse le plus d’espace au-dessus du vin','Le service standard garde une large surface aromatique','Un service généreux réduit l’espace libre']},
    sparkling:{size:'Calice tulipe étroit',headspace:'Plus d’espace qu’une flûte',pour:['Un petit service laisse place à la mousse et aux arômes','Le service standard garde la bulle visible','Un service généreux laisse moins d’espace au-dessus du vin']},
    fortified:{size:'Plus petit calice ici',headspace:'Espace volontairement réduit',pour:['Un petit service mesure alcool et douceur','Le service standard équilibre arôme et intensité','Un service généreux accentue alcool et douceur']},
  },
  es:{
    universal:{size:'Cáliz de anchura intermedia del conjunto',headspace:'Espacio equilibrado con servicio estándar',pour:['Un servicio pequeño deja el cáliz abierto','El servicio estándar sirve de referencia','Un servicio generoso acerca el vino al borde']},
    burgundy:{size:'Cáliz más ancho del conjunto',headspace:'Más espacio libre con servicio pequeño',pour:['Un servicio pequeño deja más espacio sobre el vino','El servicio estándar mantiene una superficie aromática amplia','Un servicio generoso reduce el espacio libre']},
    sparkling:{size:'Cáliz tulipa estrecho',headspace:'Más espacio que una flauta',pour:['Un servicio pequeño deja sitio para espuma y aroma','El servicio estándar mantiene visible la burbuja','Un servicio generoso deja menos espacio sobre el vino']},
    fortified:{size:'Cáliz más pequeño del conjunto',headspace:'Menos espacio libre por diseño',pour:['Un servicio pequeño mantiene medidos alcohol y dulzor','El servicio estándar equilibra aroma e intensidad','Un servicio generoso lleva alcohol y dulzor al frente']},
  },
}
const labTitles={
  en:{glass:'Change glass shape and pour volume',closure:'Compare the seal around the wine',bottle:'Read bottle form through function'},
  de:{glass:'Glasform und Füllmenge vergleichen',closure:'Den Verschluss rund um den Wein vergleichen',bottle:'Flaschenform über ihre Funktion lesen'},
  fr:{glass:'Comparer la forme du verre et le volume servi',closure:'Comparer le système qui scelle le vin',bottle:'Lire la bouteille par sa fonction'},
  es:{glass:'Compara la forma de la copa y el volumen',closure:'Compara el sistema que sella el vino',bottle:'Lee la botella a través de su función'},
} as const

export function ServiceKnowledgeLab({articleId,locale}:{articleId:string;locale:Locale}){
  if(!(['glassware-anatomy','bottle-closures','bottle-anatomy'] as string[]).includes(articleId))return null
  const c=copy[locale]
  if(articleId==='glassware-anatomy')return <GlassLab locale={locale}/>
  const group=articleId==='bottle-closures'?c.closure:c.bottle
  const keys=Object.keys(group) as Array<keyof typeof group>
  return <ObjectLab articleId={articleId as LabId} locale={locale} keys={keys as string[]}/>
}

function GlassLab({locale}:{locale:Locale}){
  const c={...copy[locale],compare:labTitles[locale].glass},keys=Object.keys(c.glass) as Array<keyof typeof c.glass>
  const [shape,setShape]=useState<GlassShape>('universal'),[pour,setPour]=useState(1)
  const item=c.glass[shape],quality=glassQualities[locale][shape],labels=qualityLabels[locale]
  const metricRows=[{label:labels.size,value:quality.size,Icon:GlassWater},{label:labels.headspace,value:quality.headspace,Icon:Droplets},{label:labels.pour,value:quality.pour[pour],Icon:Focus}]
  return <section className="service-object-lab glassware-lab"><header><span className="eyebrow"><GlassWater/>{c.lab}</span><h2>{c.compare}</h2><p>{c.notScore}</p></header><div className="object-lab-layout"><nav>{keys.map(key=><button className={shape===key?'active':''} aria-pressed={shape===key} onClick={()=>setShape(key as GlassShape)} key={key}><span className={`glass-icon glass-${key}`}/><strong>{c.glass[key][0]}</strong></button>)}</nav><article><span className="eyebrow">{c.pour}</span><div className="pour-control" role="group" aria-label={c.pour}><div className="knowledge-choice pour-options"><div>{pourLevels[locale].map((label,index)=><button type="button" key={label} aria-pressed={pour===index} onClick={()=>setPour(index)}>{label}</button>)}</div></div><strong>{pourLevels[locale][pour]}</strong></div><h3>{item[0]}</h3><p>{item[1]}</p><div className="object-metrics">{metricRows.map(({label,value,Icon})=><div key={label}><span><Icon/>{label}</span><strong>{value}</strong></div>)}</div><aside><strong>{c.watch}</strong><p>{item[2]}</p></aside></article></div></section>
}

function ObjectLab({articleId,locale,keys}:{articleId:LabId;locale:Locale;keys:string[]}){
  const isClosure=articleId==='bottle-closures',c={...copy[locale],compare:isClosure?labTitles[locale].closure:labTitles[locale].bottle},group=isClosure?c.closure:c.bottle
  const [selected,setSelected]=useState(keys[0])
  const item=(group as Record<string,readonly string[]>)[selected]
  return <section className={`service-object-lab ${isClosure?'closure-lab':'bottle-lab'}`}><header><span className="eyebrow">{isClosure?<ShieldCheck/>:<Wine/>}{c.lab}</span><h2>{c.compare}</h2><p>{c.notScore}</p></header><div className="object-lab-layout"><nav>{keys.map(key=><button className={selected===key?'active':''} aria-pressed={selected===key} onClick={()=>setSelected(key)} key={key}><span className={`${isClosure?'closure-icon':'bottle-form'} form-${key}`}/><strong>{(group as Record<string,readonly string[]>)[key][0]}</strong></button>)}</nav><article><span className="eyebrow">{c.why}</span><h3>{item[0]}</h3><p>{item[1]}</p><div className="object-reading"><CircleGauge/><div><strong>{c.watch}</strong><p>{item[2]}</p></div></div>{item[3]&&<div className="object-reading"><ShieldCheck/><div><strong>{c.use}</strong><p>{item[3]}</p></div></div>}</article></div></section>
}
