import { MessageCircleMore, Pause, Play, RotateCcw, Sparkles, TimerReset, Users } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useLocale, type Locale } from './i18n'
import type { TastingChapter, TastingJourney } from './types'

const copy={
  en:{eyebrow:'Host console',title:'Shape the room, not just the slides',frame:'Frame',predict:'Predict',reveal:'Reveal',discuss:'Discuss',prompt:'Question for the table',promptFallback:'What do you notice before anyone names the wine?',revealFallback:'Return to the evidence: name one observation, one possible cause and one uncertainty.',timer:'Chapter timer',start:'Start',pause:'Pause',reset:'Reset',pulse:'Table pulse',low:'Unsure',medium:'Leaning',high:'Confident',observation:'Capture a table observation',placeholder:'One precise observation…',add:'Add',notes:'Shared observations on this device',clear:'Clear pulse'},
  de:{eyebrow:'Host-Konsole',title:'Gestalte den Raum, nicht nur die Folien',frame:'Rahmen',predict:'Vermuten',reveal:'Auflösen',discuss:'Diskutieren',prompt:'Frage an den Tisch',promptFallback:'Was fällt euch auf, bevor jemand den Wein benennt?',revealFallback:'Zurück zur Evidenz: Nennt eine Beobachtung, eine mögliche Ursache und eine Unsicherheit.',timer:'Kapitel-Timer',start:'Start',pause:'Pause',reset:'Zurücksetzen',pulse:'Tisch-Puls',low:'Unsicher',medium:'Tendenz',high:'Sicher',observation:'Tischbeobachtung festhalten',placeholder:'Eine präzise Beobachtung …',add:'Hinzufügen',notes:'Gemeinsame Beobachtungen auf diesem Gerät',clear:'Puls leeren'},
  fr:{eyebrow:'Console hôte',title:'Façonner la salle, pas seulement les écrans',frame:'Cadrer',predict:'Prédire',reveal:'Révéler',discuss:'Discuter',prompt:'Question à la table',promptFallback:'Que remarquez-vous avant que quelqu’un nomme le vin ?',revealFallback:'Revenez aux indices : une observation, une cause possible et une incertitude.',timer:'Minuteur du chapitre',start:'Démarrer',pause:'Pause',reset:'Réinitialiser',pulse:'Pouls de la table',low:'Incertain',medium:'Tendance',high:'Sûr',observation:'Noter une observation',placeholder:'Une observation précise…',add:'Ajouter',notes:'Observations partagées sur cet appareil',clear:'Effacer le pouls'},
  es:{eyebrow:'Consola del anfitrión',title:'Diseña la sala, no solo las pantallas',frame:'Enmarcar',predict:'Predecir',reveal:'Revelar',discuss:'Conversar',prompt:'Pregunta para la mesa',promptFallback:'¿Qué notas antes de que alguien nombre el vino?',revealFallback:'Vuelve a la evidencia: una observación, una causa posible y una incertidumbre.',timer:'Temporizador',start:'Iniciar',pause:'Pausa',reset:'Reiniciar',pulse:'Pulso de la mesa',low:'Inseguro',medium:'Tendencia',high:'Seguro',observation:'Guardar una observación',placeholder:'Una observación precisa…',add:'Añadir',notes:'Observaciones compartidas en este dispositivo',clear:'Borrar pulso'},
} satisfies Record<Locale,Record<string,string>>

type HostState={phase:number;seconds:number;running:boolean;votes:[number,number,number];notes:string[]}
const initial=(chapter:TastingChapter):HostState=>({phase:chapter.interaction==='predict'?1:0,seconds:chapter.duration*60,running:false,votes:[0,0,0],notes:[]})
export function TastingHostConsole({journey,chapter}:{journey:TastingJourney;chapter:TastingChapter}){
  const {locale}=useLocale(),c=copy[locale],key=`vine-atlas-host:${journey.id}:${chapter.id}`
  const [state,setState]=useState<HostState>(()=>{try{return JSON.parse(localStorage.getItem(key)??'null')??initial(chapter)}catch{return initial(chapter)}}),[note,setNote]=useState('')
  useEffect(()=>{localStorage.setItem(key,JSON.stringify(state))},[key,state])
  useEffect(()=>{if(!state.running||state.seconds<=0)return;const id=window.setInterval(()=>setState(value=>({...value,seconds:Math.max(0,value.seconds-1),running:value.seconds>1})),1000);return()=>window.clearInterval(id)},[state.running,state.seconds])
  const time=useMemo(()=>`${String(Math.floor(state.seconds/60)).padStart(2,'0')}:${String(state.seconds%60).padStart(2,'0')}`,[state.seconds])
  const phases=[c.frame,c.predict,c.reveal,c.discuss]
  const prompt=chapter.prompt||c.promptFallback,reveal=chapter.reveal||c.revealFallback
  const addNote=()=>{const value=note.trim();if(!value)return;setState(current=>({...current,notes:[...current.notes,value]}));setNote('')}
  return <section className="tasting-host-console"><header><div><span className="eyebrow"><Users/>{c.eyebrow}</span><h2>{c.title}</h2></div><div className="host-timer"><TimerReset/><strong>{time}</strong><button onClick={()=>setState(value=>({...value,running:!value.running}))}>{state.running?<Pause/>:<Play/>}<span>{state.running?c.pause:c.start}</span></button><button onClick={()=>setState(value=>({...value,seconds:chapter.duration*60,running:false}))}><RotateCcw/><span>{c.reset}</span></button></div></header><nav aria-label={c.eyebrow}>{phases.map((phase,index)=><button className={state.phase===index?'active':state.phase>index?'done':''} aria-current={state.phase===index?'step':undefined} onClick={()=>setState(value=>({...value,phase:index}))} key={phase}><span>{String(index+1).padStart(2,'0')}</span>{phase}</button>)}</nav><div className="host-stage"><article><span>{state.phase<2?c.prompt:c.reveal}</span><p>{state.phase<2?prompt:reveal}</p></article><aside><span><Sparkles/>{c.pulse}</span><div>{([c.low,c.medium,c.high] as string[]).map((label,index)=><button onClick={()=>setState(value=>({...value,votes:value.votes.map((count,i)=>i===index?count+1:count) as HostState['votes']}))} key={label}><strong>{state.votes[index]}</strong>{label}</button>)}</div><button className="text-action" onClick={()=>setState(value=>({...value,votes:[0,0,0]}))}>{c.clear}</button></aside></div><div className="host-observations"><label><span><MessageCircleMore/>{c.observation}</span><div><input value={note} onChange={event=>setNote(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')addNote()}} placeholder={c.placeholder}/><button onClick={addNote}>{c.add}</button></div></label>{state.notes.length>0&&<div><span>{c.notes}</span><ol>{state.notes.map((item,index)=><li key={`${item}-${index}`}>{item}</li>)}</ol></div>}</div></section>
}
