import { useEffect, useMemo, useState } from 'react'
import { Check, Grape, LockKeyhole, NotebookPen, Plus, Sparkles } from 'lucide-react'
import { aromas } from './data/catalog'
import { repository } from './data/repository'
import { aromaContent } from './localizedContent'
import type { Locale } from './i18n'
import type { TastingChapter, TastingJourney, TastingNote, Wine } from './types'

const copy={
  en:{eyebrow:'Your place at the table',title:'Notice first. Compare after.',private:'Private on your account',prompt:'Your answer before the reveal',placeholder:'Write one observation or prediction…',confidence:'How certain are you?',low:'Unsure',medium:'Leaning',high:'Confident',save:'Save response',saved:'Response saved',wine:'Capture this wine',aromas:'Aromas you can defend',structure:'Structure in your glass',acid:'Acidity',tannin:'Tannin',body:'Body',reflection:'What will you remember?',reflectionHint:'One precise sentence is enough.',cellar:'Add wine and note to cellar',inCellar:'Saved to cellar',complete:'Mark chapter complete',completed:'Chapter complete'},
  de:{eyebrow:'Dein Platz am Tisch',title:'Erst wahrnehmen. Danach vergleichen.',private:'Privat in deinem Account',prompt:'Deine Antwort vor der Auflösung',placeholder:'Eine Beobachtung oder Vermutung …',confidence:'Wie sicher bist du?',low:'Unsicher',medium:'Tendenz',high:'Sicher',save:'Antwort speichern',saved:'Antwort gespeichert',wine:'Diesen Wein festhalten',aromas:'Aromen, die du begründen kannst',structure:'Struktur in deinem Glas',acid:'Säure',tannin:'Tannin',body:'Körper',reflection:'Was wirst du erinnern?',reflectionHint:'Ein präziser Satz genügt.',cellar:'Wein und Notiz im Keller speichern',inCellar:'Im Keller gespeichert',complete:'Kapitel abschließen',completed:'Kapitel abgeschlossen'},
  fr:{eyebrow:'Votre place à table',title:'Observer d’abord. Comparer ensuite.',private:'Privé dans votre compte',prompt:'Votre réponse avant la révélation',placeholder:'Une observation ou une hypothèse…',confidence:'Quel est votre degré de certitude ?',low:'Incertain',medium:'Tendance',high:'Sûr',save:'Enregistrer la réponse',saved:'Réponse enregistrée',wine:'Garder ce vin',aromas:'Arômes que vous pouvez défendre',structure:'Structure dans votre verre',acid:'Acidité',tannin:'Tanins',body:'Corps',reflection:'Que retiendrez-vous ?',reflectionHint:'Une phrase précise suffit.',cellar:'Ajouter vin et note à la cave',inCellar:'Enregistré dans la cave',complete:'Terminer le chapitre',completed:'Chapitre terminé'},
  es:{eyebrow:'Tu lugar en la mesa',title:'Primero observa. Después compara.',private:'Privado en tu cuenta',prompt:'Tu respuesta antes de revelar',placeholder:'Una observación o predicción…',confidence:'¿Qué seguridad tienes?',low:'Inseguro',medium:'Me inclino',high:'Seguro',save:'Guardar respuesta',saved:'Respuesta guardada',wine:'Guardar este vino',aromas:'Aromas que puedes justificar',structure:'Estructura en tu copa',acid:'Acidez',tannin:'Tanino',body:'Cuerpo',reflection:'¿Qué recordarás?',reflectionHint:'Una frase precisa basta.',cellar:'Añadir vino y nota a la bodega',inCellar:'Guardado en la bodega',complete:'Completar capítulo',completed:'Capítulo completado'},
} as const

type ResponseState={text:string;confidence:number;saved:boolean;aromaIds:string[];acid:number;tannin:number;body:number;reflection:string}
const blank:ResponseState={text:'',confidence:1,saved:false,aromaIds:[],acid:3,tannin:3,body:3,reflection:''}

export function TastingParticipantTools({journey,chapter,wine,locale,complete,onComplete}:{journey:TastingJourney;chapter:TastingChapter;wine?:Wine;locale:Locale;complete:boolean;onComplete:()=>void}){
  const c=copy[locale],key=`vine-atlas-participant:${journey.id}:${chapter.id}`
  const [state,setState]=useState<ResponseState>(()=>{try{return {...blank,...JSON.parse(localStorage.getItem(key)??'null')}}catch{return blank}})
  const wineAromas=useMemo(()=>wine?aromas.filter(aroma=>wine.aromaIds.includes(aroma.id)):[],[wine])
  const inCellar=wine?repository.cellar.all().some(item=>item.wineId===wine.id):false
  useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{/* browser storage may be unavailable */}},[key,state])
  function saveResponse(){setState(value=>({...value,saved:true}));try{const channel=new BroadcastChannel(`vine-atlas-tasting:${journey.id}`);channel.postMessage({type:'pulse',chapterId:chapter.id,confidence:state.confidence,observation:state.text.trim()});channel.close()}catch{/* optional same-origin live enhancement */}}
  function saveWine(){if(!wine)return;const now=new Date().toISOString();const note:TastingNote={id:crypto.randomUUID(),tastingId:journey.id,wineId:wine.id,appearance:'',aromaIds:state.aromaIds,palate:`${c.acid} ${state.acid}/5 · ${c.tannin} ${state.tannin}/5 · ${c.body} ${state.body}/5`,reflection:state.reflection,rating:0,visibility:'private',createdAt:now};repository.notes.save([...repository.notes.all(),note]);const cellar=repository.cellar.all(),existing=cellar.find(item=>item.wineId===wine.id);if(existing){existing.quantity=Math.max(1,existing.quantity);existing.state='tasted';existing.notes=[...(existing.notes??[]),{id:note.id,appearance:'',aromaIds:note.aromaIds,palate:note.palate,finish:'',reflection:note.reflection,acidity:state.acid,tannin:state.tannin,body:state.body,rating:0,createdAt:now}]}else cellar.push({id:crypto.randomUUID(),wineId:wine.id,state:'tasted',quantity:1,location:'Home cellar',vintage:wine.vintage??undefined,bottleSizeMl:750,notes:[{id:note.id,appearance:'',aromaIds:note.aromaIds,palate:note.palate,finish:'',reflection:note.reflection,acidity:state.acid,tannin:state.tannin,body:state.body,rating:0,createdAt:now}]});repository.cellar.save(cellar);setState(value=>({...value,saved:true}))}
  const confidenceLabels=[c.low,c.medium,c.high]
  return <section className="participant-table-tools"><header><div><span className="eyebrow"><Sparkles/>{c.eyebrow}</span><h2>{c.title}</h2></div><small><LockKeyhole/>{c.private}</small></header>{chapter.interaction!=='observe'&&<div className="participant-prompt"><label><span>{c.prompt}</span><textarea value={state.text} onChange={event=>setState({...state,text:event.target.value,saved:false})} placeholder={chapter.prompt||c.placeholder}/></label><fieldset><legend>{c.confidence}</legend>{confidenceLabels.map((label,index)=><button type="button" className={state.confidence===index?'active':''} aria-pressed={state.confidence===index} onClick={()=>setState({...state,confidence:index,saved:false})} key={label}><b>{index+1}</b>{label}</button>)}</fieldset><button className="secondary-button" onClick={saveResponse}>{state.saved?<Check/>:<NotebookPen/>}{state.saved?c.saved:c.save}</button></div>}{wine&&<div className="participant-wine-note"><div><span className="eyebrow"><Grape/>{c.wine}</span><h3>{c.aromas}</h3><div className="participant-aromas">{wineAromas.map(aroma=><button aria-pressed={state.aromaIds.includes(aroma.id)} className={state.aromaIds.includes(aroma.id)?'active':''} onClick={()=>setState({...state,aromaIds:state.aromaIds.includes(aroma.id)?state.aromaIds.filter(id=>id!==aroma.id):[...state.aromaIds,aroma.id]})} key={aroma.id}>{state.aromaIds.includes(aroma.id)&&<Check/>}{aromaContent(aroma,locale).name}</button>)}</div></div><div className="participant-structure"><h3>{c.structure}</h3>{([['acid',c.acid],['tannin',c.tannin],['body',c.body]] as const).map(([field,label])=><label key={field}><span>{label}</span><input type="range" min="1" max="5" value={state[field]} onChange={event=>setState({...state,[field]:Number(event.target.value)})}/><b>{state[field]}</b></label>)}<label className="participant-reflection"><span>{c.reflection}</span><textarea value={state.reflection} onChange={event=>setState({...state,reflection:event.target.value})} placeholder={c.reflectionHint}/></label><button className="primary-button" onClick={saveWine}>{inCellar?<Check/>:<Plus/>}{inCellar?c.inCellar:c.cellar}</button></div></div>}<button className={`participant-complete ${complete?'done':''}`} onClick={onComplete}>{complete?<Check/>:<span/>}{complete?c.completed:c.complete}</button></section>
}
