import { useState } from 'react'
import { ArrowRight, Beaker, Clock3, Droplets, Eye, Grape, Sparkles, ThermometerSun } from 'lucide-react'
import processPlate from './assets/learning-vine-to-glass-process-v2.jpg'
import transformationPlate from './assets/learning-fermentation-transformation.jpg'
import pathwaysPlate from './assets/learning-five-wine-pathways.jpg'
import type { Locale } from './i18n'

type L = Record<Locale,string>
const l=(en:string,de:string,fr:string,es:string):L=>({en,de,fr,es})

const ui={
  en:{eyebrow:'From vine to glass',title:'Seven moments that shape a wine',material:'Material changes',decision:'Cellar decision',trace:'Possible trace in the glass',evidence:'Useful evidence',transformEyebrow:'Fermentation under the lens',transformTitle:'Berry, must, young wine',pathEyebrow:'Five winemaking pathways',pathTitle:'The same fruit can lead to very different structures',process:'Sequence',structure:'Structural consequence',glass:'Look for',experiment:'Two-glass experiment',experimentTitle:'Separate grape character from winemaking',stepOne:'Choose two wines from the same grape but made with different extraction or maturation choices.',stepTwo:'Taste for acidity, tannin, texture and aroma family before naming a preference.',stepThree:'Connect each sensory difference to a plausible process—then check the producer’s technical notes.',processAlt:'Illustrated sequence from vineyard fruit through cellar work to wine in the glass',transformAlt:'Illustrated transformation from berry anatomy through fermentation to young wine',pathAlt:'Five illustrated winemaking pathways for white, red, rosé, sparkling and skin-contact wine'},
  de:{eyebrow:'Von der Rebe ins Glas',title:'Sieben Momente, die einen Wein prägen',material:'Was sich im Material ändert',decision:'Entscheidung im Keller',trace:'Mögliche Spur im Glas',evidence:'Hilfreiche Beobachtung',transformEyebrow:'Gärung unter der Lupe',transformTitle:'Beere, Most, Jungwein',pathEyebrow:'Fünf Wege der Weinbereitung',pathTitle:'Dieselbe Frucht kann zu sehr unterschiedlichen Strukturen führen',process:'Ablauf',structure:'Strukturelle Folge',glass:'Im Glas beachten',experiment:'Zwei-Gläser-Versuch',experimentTitle:'Rebsortencharakter und Ausbau voneinander trennen',stepOne:'Wähle zwei Weine derselben Rebsorte, die mit unterschiedlicher Extraktion oder Reifung erzeugt wurden.',stepTwo:'Vergleiche Säure, Tannin, Textur und Aromafamilie, bevor du eine Vorliebe formulierst.',stepThree:'Verbinde jeden sensorischen Unterschied mit einem plausiblen Prozess und prüfe anschließend die technischen Angaben des Erzeugers.',processAlt:'Illustrierter Weg von der Traube über die Kellerarbeit bis zum Wein im Glas',transformAlt:'Illustrierte Veränderung von der Beerenanatomie über die Gärung zum Jungwein',pathAlt:'Fünf illustrierte Wege für Weißwein, Rotwein, Rosé, Schaumwein und maischevergorenen Weißwein'},
  fr:{eyebrow:'De la vigne au verre',title:'Sept moments qui façonnent un vin',material:'Transformation de la matière',decision:'Décision de cave',trace:'Trace possible dans le verre',evidence:'Indice utile',transformEyebrow:'La fermentation à la loupe',transformTitle:'Baie, moût, vin jeune',pathEyebrow:'Cinq voies de vinification',pathTitle:'Un même fruit peut donner des structures très différentes',process:'Séquence',structure:'Conséquence structurelle',glass:'À chercher dans le verre',experiment:'Expérience à deux verres',experimentTitle:'Distinguer le cépage des choix de vinification',stepOne:'Choisissez deux vins du même cépage issus de choix différents d’extraction ou d’élevage.',stepTwo:'Comparez acidité, tanins, texture et famille aromatique avant d’exprimer une préférence.',stepThree:'Reliez chaque différence sensorielle à un processus plausible, puis vérifiez la fiche technique du producteur.',processAlt:'Séquence illustrée du raisin à la cave puis au vin dans le verre',transformAlt:'Transformation illustrée de l’anatomie de la baie à la fermentation et au vin jeune',pathAlt:'Cinq voies illustrées pour vin blanc, rouge, rosé, effervescent et blanc de macération'},
  es:{eyebrow:'De la vid a la copa',title:'Siete momentos que dan forma a un vino',material:'Cambio de la materia',decision:'Decisión de bodega',trace:'Posible huella en la copa',evidence:'Evidencia útil',transformEyebrow:'La fermentación bajo la lupa',transformTitle:'Baya, mosto, vino joven',pathEyebrow:'Cinco vías de elaboración',pathTitle:'Una misma fruta puede producir estructuras muy diferentes',process:'Secuencia',structure:'Consecuencia estructural',glass:'Qué buscar en la copa',experiment:'Experimento de dos copas',experimentTitle:'Separar el carácter de la variedad de la elaboración',stepOne:'Elige dos vinos de la misma variedad elaborados con distinta extracción o crianza.',stepTwo:'Compara acidez, tanino, textura y familia aromática antes de expresar una preferencia.',stepThree:'Relaciona cada diferencia sensorial con un proceso plausible y comprueba después la ficha técnica del productor.',processAlt:'Secuencia ilustrada desde la uva y la bodega hasta el vino en la copa',transformAlt:'Transformación ilustrada desde la anatomía de la baya hasta la fermentación y el vino joven',pathAlt:'Cinco vías ilustradas para vino blanco, tinto, rosado, espumoso y blanco con maceración'},
} satisfies Record<Locale,Record<string,string>>

const stages=[
  {title:l('Harvest','Lese','Vendange','Vendimia'),material:l('Berries arrive with a particular balance of sugar, acids, phenolic maturity, aroma precursors and microbial load. Damaged or sunburnt fruit is a different raw material from intact, cool fruit.','Die Beeren kommen mit einem bestimmten Verhältnis von Zucker, Säuren, phenolischer Reife, Aromavorstufen und Mikroflora an. Beschädigte oder sonnenverbrannte Trauben sind ein anderes Ausgangsmaterial als intakte, kühle Frucht.','Les baies arrivent avec un équilibre propre entre sucres, acides, maturité phénolique, précurseurs aromatiques et flore microbienne. Un fruit abîmé ou brûlé n’est pas la même matière qu’un fruit intact et frais.','Las bayas llegan con un equilibrio concreto de azúcar, ácidos, madurez fenólica, precursores aromáticos y carga microbiana. La fruta dañada o quemada no es la misma materia que la fruta intacta y fresca.'),decision:l('Picking date, hand or machine harvest, selection threshold and time between vineyard and cellar.','Lesetermin, Hand- oder Maschinenlese, Selektionsgrad und Zeit zwischen Weinberg und Keller.','Date de récolte, vendange manuelle ou mécanique, niveau de tri et délai entre vigne et cave.','Fecha de cosecha, vendimia manual o mecánica, nivel de selección y tiempo hasta la bodega.'),trace:l('Riper fruit can broaden fruit character and alcohol; earlier harvest can preserve acidity and herbal or floral notes. Neither is automatically better.','Reifere Frucht kann Fruchtfülle und Alkohol erhöhen; frühere Lese kann Säure sowie kräuterige oder florale Noten bewahren. Keines ist automatisch besser.','Un fruit plus mûr peut élargir le fruité et l’alcool; une récolte précoce peut préserver acidité et notes végétales ou florales. Aucun choix n’est supérieur en soi.','La fruta más madura puede ampliar el carácter frutal y el alcohol; la cosecha temprana puede conservar acidez y notas herbales o florales. Ninguna opción es superior por sí sola.'),evidence:l('Must sugar, pH, titratable acidity, berry taste, seed and skin condition.','Mostgewicht, pH, titrierbare Säure, Beerengeschmack sowie Kern- und Schalenreife.','Sucres du moût, pH, acidité titrable, goût des baies, état des pépins et pellicules.','Azúcar del mosto, pH, acidez titulable, sabor de la baya y estado de semillas y pieles.')},
  {title:l('Sorting & crushing','Sortieren & Mahlen','Tri & foulage','Selección y estrujado'),material:l('Breaking berries releases juice and brings enzymes, oxygen, skins, seeds and microbes into contact. Whole clusters preserve a different physical and microbial environment.','Das Öffnen der Beeren bringt Saft, Enzyme, Sauerstoff, Schalen, Kerne und Mikroorganismen zusammen. Ganze Trauben erhalten ein anderes physikalisches und mikrobielles Milieu.','L’éclatement des baies met en contact jus, enzymes, oxygène, pellicules, pépins et microbes. Les grappes entières conservent un autre environnement physique et microbien.','Romper las bayas pone en contacto mosto, enzimas, oxígeno, pieles, semillas y microbios. Los racimos enteros conservan otro entorno físico y microbiano.'),decision:l('Destemming, whole-cluster proportion, crushing intensity, sulfur addition and protection from oxygen.','Entrappen, Ganztraubenanteil, Mahlintensität, Schwefelgabe und Sauerstoffschutz.','Éraflage, proportion de grappes entières, intensité du foulage, ajout de soufre et protection contre l’oxygène.','Despalillado, proporción de racimo entero, intensidad de estrujado, adición de sulfuroso y protección del oxígeno.'),trace:l('Whole clusters can shift perfume, tannin shape and freshness; hard crushing may release more solids and seed-derived bitterness.','Ganztrauben können Duft, Tanninform und Frische verändern; starkes Mahlen kann mehr Feststoffe und kernbürtige Bitterkeit lösen.','Les grappes entières peuvent modifier parfum, forme des tanins et fraîcheur; un foulage appuyé libère davantage de solides et d’amertume des pépins.','El racimo entero puede cambiar perfume, forma del tanino y frescura; un estrujado intenso puede liberar más sólidos y amargor de las semillas.'),evidence:l('Juice colour, turbidity, temperature, intact-berry percentage and stem lignification.','Saftfarbe, Trübung, Temperatur, Anteil intakter Beeren und Verholzung der Rappen.','Couleur du jus, turbidité, température, pourcentage de baies intactes et lignification des rafles.','Color del mosto, turbidez, temperatura, porcentaje de bayas intactas y lignificación del raspón.')},
  {title:l('Pressing & extraction','Pressen & Extraktion','Pressurage & extraction','Prensado y extracción'),material:l('Pressure and contact time determine how much juice, phenolics, potassium, aroma compounds and suspended solids move from skins and pulp into the liquid.','Druck und Kontaktzeit bestimmen, wie viel Saft, Phenole, Kalium, Aromastoffe und Trub aus Schalen und Fruchtfleisch in die Flüssigkeit gelangen.','Pression et durée de contact déterminent la quantité de jus, phénols, potassium, composés aromatiques et bourbes transférée au liquide.','La presión y el tiempo de contacto determinan cuánto mosto, fenoles, potasio, compuestos aromáticos y sólidos pasan al líquido.'),decision:l('Direct press or maceration, press cycle, separation of free-run and press fractions, cap management.','Direktpressung oder Maischestandzeit, Pressprogramm, Trennung von Vorlauf und Pressfraktionen, Maischehutmanagement.','Pressurage direct ou macération, cycle de presse, séparation des jus de goutte et de presse, gestion du chapeau.','Prensado directo o maceración, ciclo de prensa, separación de mosto yema y prensa, gestión del sombrero.'),trace:l('Extraction shapes colour, tannin, bitterness and body. Rosé, red and skin-contact white diverge most clearly here.','Extraktion prägt Farbe, Tannin, Bitterkeit und Körper. Rosé, Rotwein und maischevergorener Weißwein trennen sich hier besonders deutlich.','L’extraction façonne couleur, tanins, amertume et corps. Rosé, rouge et blanc de macération divergent surtout ici.','La extracción define color, tanino, amargor y cuerpo. Rosado, tinto y blanco con maceración divergen aquí con claridad.'),evidence:l('Phenolic taste, colour density, press fraction, temperature and extraction curve over time.','Phenolischer Geschmack, Farbdichte, Pressfraktion, Temperatur und Extraktionsverlauf.','Goût phénolique, densité colorante, fraction de presse, température et courbe d’extraction.','Sabor fenólico, densidad de color, fracción de prensa, temperatura y curva de extracción.')},
  {title:l('Alcoholic fermentation','Alkoholische Gärung','Fermentation alcoolique','Fermentación alcohólica'),material:l('Yeast converts sugar mainly into ethanol and carbon dioxide while producing heat, glycerol and hundreds of aroma-active metabolites. Nutrient status and temperature change the route.','Hefen wandeln Zucker vor allem in Ethanol und Kohlendioxid um und erzeugen dabei Wärme, Glycerin und Hunderte aromawirksame Metaboliten. Nährstofflage und Temperatur verändern den Verlauf.','Les levures transforment surtout le sucre en éthanol et dioxyde de carbone, avec chaleur, glycérol et des centaines de métabolites aromatiques. Nutriments et température modifient la voie.','Las levaduras convierten el azúcar principalmente en etanol y dióxido de carbono, produciendo calor, glicerol y cientos de metabolitos aromáticos. Nutrientes y temperatura cambian la ruta.'),decision:l('Ambient or selected yeast, temperature, nutrient additions, oxygen early in fermentation and cap work for reds.','Spontane oder Reinzuchthefe, Temperatur, Nährstoffgaben, Sauerstoff zu Gärbeginn und Maischearbeit bei Rotwein.','Levures indigènes ou sélectionnées, température, nutriments, oxygène au début et travail du chapeau pour les rouges.','Levadura ambiente o seleccionada, temperatura, nutrientes, oxígeno al inicio y trabajo del sombrero en tintos.'),trace:l('Cool protected ferments can retain volatile fruit; warmer ferments change extraction and aroma formation. Stress can produce reduction or volatile acidity.','Kühle, geschützte Gärung kann flüchtige Frucht bewahren; wärmere Gärung verändert Extraktion und Aromabildung. Stress kann Reduktion oder flüchtige Säure fördern.','Une fermentation fraîche et protégée peut préserver le fruit volatil; plus chaude, elle modifie extraction et arômes. Le stress peut favoriser réduction ou acidité volatile.','Una fermentación fresca y protegida puede conservar fruta volátil; más cálida cambia extracción y aromas. El estrés puede favorecer reducción o acidez volátil.'),evidence:l('Density loss, temperature curve, residual sugar, yeast-assimilable nitrogen and sensory checks.','Dichteabnahme, Temperaturkurve, Restzucker, hefeverfügbarer Stickstoff und sensorische Kontrolle.','Baisse de densité, courbe de température, sucres résiduels, azote assimilable et contrôle sensoriel.','Caída de densidad, curva de temperatura, azúcar residual, nitrógeno asimilable y control sensorial.')},
  {title:l('Post-ferment texture','Textur nach der Gärung','Texture après fermentation','Textura posfermentativa'),material:l('Malolactic conversion can lower sharp malic acidity; lees release mannoproteins and other compounds that alter texture and bind aroma. Oxygen remains active even after sugar is dry.','Der biologische Säureabbau kann spitze Äpfelsäure reduzieren; Hefen setzen Mannoproteine und weitere Stoffe frei, die Textur und Aromabindung verändern. Sauerstoff wirkt auch nach der Gärung weiter.','La conversion malolactique peut réduire l’acide malique tranchant; les lies libèrent mannoprotéines et composés qui changent texture et arômes. L’oxygène reste actif après la fin des sucres.','La conversión maloláctica puede reducir el ácido málico punzante; las lías liberan manoproteínas y compuestos que cambian textura y aroma. El oxígeno sigue activo tras agotarse el azúcar.'),decision:l('Encourage or block malolactic conversion, time on fine lees, stirring frequency and early racking.','Biologischen Säureabbau fördern oder verhindern, Dauer auf der Feinhefe, Aufrührhäufigkeit und früher Abstich.','Favoriser ou bloquer la malo, durée sur lies fines, fréquence du bâtonnage et soutirage précoce.','Favorecer o bloquear la maloláctica, tiempo sobre lías finas, frecuencia de removido y trasiego temprano.'),trace:l('Possible creamier texture, lower malic bite and notes such as butter or yoghurt; lees can broaden mid-palate without adding sweetness.','Mögliche cremigere Textur, weniger Apfelsäurebiss und Noten wie Butter oder Joghurt; Hefelager kann den Mittelgaumen verbreitern, ohne Süße zuzufügen.','Texture potentiellement plus crémeuse, morsure malique réduite et notes beurrées ou lactées; les lies élargissent le milieu de bouche sans sucre.','Textura potencialmente más cremosa, menor mordiente málico y notas de mantequilla o yogur; las lías amplían el paso de boca sin añadir dulzor.'),evidence:l('Malic acid, turbidity, dissolved oxygen, microbial stability and repeated tasting.','Äpfelsäure, Trübung, gelöster Sauerstoff, mikrobielle Stabilität und wiederholte Verkostung.','Acide malique, turbidité, oxygène dissous, stabilité microbienne et dégustations répétées.','Ácido málico, turbidez, oxígeno disuelto, estabilidad microbiana y catas repetidas.')},
  {title:l('Maturation & blending','Reifung & Cuvée','Élevage & assemblage','Crianza y ensamblaje'),material:l('Wine exchanges oxygen at rates set by vessel and handling. Oak can contribute compounds; concrete, steel, clay and bottle create different thermal and oxygen environments. Blending changes proportions rather than inventing quality.','Wein nimmt je nach Gefäß und Handhabung unterschiedlich viel Sauerstoff auf. Holz kann Stoffe abgeben; Beton, Stahl, Ton und Flasche schaffen andere thermische und oxidative Milieus. Eine Cuvée verändert Anteile, nicht automatisch Qualität.','Le vin échange de l’oxygène selon le contenant et les manipulations. Le bois peut céder des composés; béton, acier, argile et bouteille créent d’autres milieux thermiques et oxydatifs. L’assemblage modifie les proportions, pas la qualité par magie.','El vino intercambia oxígeno según recipiente y manejo. La madera puede aportar compuestos; hormigón, acero, arcilla y botella crean otros entornos térmicos y oxidativos. El ensamblaje cambia proporciones, no inventa calidad.'),decision:l('Vessel, new-oak proportion, time, topping, racking, protective gas, blending components and fining.','Gefäß, Neuholzanteil, Dauer, Auffüllen, Abstiche, Schutzgas, Cuvéepartner und Schönung.','Contenant, proportion de bois neuf, durée, ouillage, soutirage, gaz protecteur, composants et collage.','Recipiente, proporción de madera nueva, tiempo, relleno, trasiegos, gas protector, componentes y clarificación.'),trace:l('Tannin can become less angular, primary fruit may recede, and spice, toast, savoury or oxidative notes can appear depending on the regime.','Tannin kann weniger kantig werden, Primärfrucht zurücktreten und je nach Regime Gewürz-, Röst-, würzige oder oxidative Noten entstehen.','Les tanins peuvent s’arrondir, le fruit primaire reculer et des notes épicées, grillées, savoureuses ou oxydatives apparaître selon le régime.','El tanino puede suavizarse, la fruta primaria retroceder y aparecer notas especiadas, tostadas, sabrosas u oxidativas según el régimen.'),evidence:l('Dissolved oxygen, free sulfur dioxide, topping losses, trial blends and sensory evolution.','Gelöster Sauerstoff, freie schweflige Säure, Schwund, Probecuvées und sensorische Entwicklung.','Oxygène dissous, SO₂ libre, pertes d’ouillage, essais d’assemblage et évolution sensorielle.','Oxígeno disuelto, SO₂ libre, mermas, pruebas de ensamblaje y evolución sensorial.')},
  {title:l('Bottling & development','Füllung & Entwicklung','Mise & évolution','Embotellado y evolución'),material:l('Filtration, dissolved gases, closure and headspace define the starting conditions of bottle ageing. Reactions continue slowly: aromas combine, pigments change and tannins polymerise.','Filtration, gelöste Gase, Verschluss und Kopfraum bestimmen die Ausgangslage der Flaschenreife. Reaktionen laufen langsam weiter: Aromen verbinden sich, Pigmente verändern sich und Tannine polymerisieren.','Filtration, gaz dissous, bouchage et espace de tête fixent les conditions du vieillissement. Les réactions continuent lentement: arômes, pigments et tanins évoluent.','Filtración, gases disueltos, cierre y espacio de cabeza fijan las condiciones de evolución. Las reacciones continúan lentamente: aromas, pigmentos y taninos cambian.'),decision:l('Stabilisation, filtration level, dissolved oxygen at filling, closure type, bottle format and release date.','Stabilisierung, Filtrationsgrad, Sauerstoff bei der Füllung, Verschluss, Flaschenformat und Freigabetermin.','Stabilisation, niveau de filtration, oxygène à la mise, type de bouchage, format et date de sortie.','Estabilización, nivel de filtración, oxígeno en el llenado, tipo de cierre, formato y fecha de salida.'),trace:l('Fresh fruit may evolve toward dried fruit, nuts, earth, tobacco or honey. Development depends on wine composition, oxygen exposure, temperature and time.','Frische Frucht kann sich zu Trockenfrucht, Nüssen, Erde, Tabak oder Honig entwickeln. Der Verlauf hängt von Weinzusammensetzung, Sauerstoff, Temperatur und Zeit ab.','Le fruit frais peut évoluer vers fruits secs, noix, terre, tabac ou miel. L’évolution dépend de la composition, de l’oxygène, de la température et du temps.','La fruta fresca puede evolucionar hacia fruta seca, frutos secos, tierra, tabaco o miel. Depende de composición, oxígeno, temperatura y tiempo.'),evidence:l('Bottling oxygen, closure specification, storage temperature, fill level and comparison across vintages.','Füllsauerstoff, Verschlussspezifikation, Lagertemperatur, Füllstand und Vergleich über Jahrgänge.','Oxygène à la mise, spécification du bouchage, température de stockage, niveau et comparaison de millésimes.','Oxígeno de embotellado, especificación del cierre, temperatura de guarda, nivel y comparación de añadas.')},
]

const transformations=[
  {title:l('Berry','Beere','Baie','Baya'),body:l('Water and sugar dominate the pulp; acids, minerals and aroma precursors are distributed unevenly. Skins carry colour, tannin and aroma compounds, while seeds add a different tannin profile.','Wasser und Zucker prägen das Fruchtfleisch; Säuren, Mineralstoffe und Aromavorstufen sind ungleich verteilt. Schalen tragen Farbe, Tannin und Aromastoffe, Kerne ein anderes Tanninprofil.','Eau et sucres dominent la pulpe; acides, minéraux et précurseurs sont répartis inégalement. Les pellicules portent couleur, tanins et arômes, les pépins un autre profil tannique.','Agua y azúcar dominan la pulpa; ácidos, minerales y precursores se distribuyen de forma desigual. Las pieles aportan color, tanino y aroma; las semillas, otro perfil tánico.')},
  {title:l('Must','Most','Moût','Mosto'),body:l('Once the berry is opened, enzymes, oxygen and microbes act on an unstable mixture. Clarification, skin contact and temperature determine which solids and compounds remain available to fermentation.','Nach dem Öffnen der Beere wirken Enzyme, Sauerstoff und Mikroorganismen auf eine instabile Mischung. Vorklärung, Schalenkontakt und Temperatur bestimmen, welche Feststoffe und Verbindungen für die Gärung verfügbar bleiben.','Une fois la baie ouverte, enzymes, oxygène et microbes agissent sur un mélange instable. Débourbage, contact pelliculaire et température décident des solides disponibles pour fermenter.','Al abrir la baya, enzimas, oxígeno y microbios actúan sobre una mezcla inestable. Desfangado, contacto con pieles y temperatura deciden qué sólidos quedan disponibles.')},
  {title:l('Young wine','Jungwein','Vin jeune','Vino joven'),body:l('Sugar has largely become ethanol and carbon dioxide, but the wine is not chemically finished. Acids, colloids, lees, phenolics, oxygen and microbes continue to reshape texture and aroma.','Zucker ist weitgehend zu Ethanol und Kohlendioxid geworden, doch chemisch ist der Wein nicht fertig. Säuren, Kolloide, Hefen, Phenole, Sauerstoff und Mikroorganismen prägen Textur und Aroma weiter.','Le sucre est largement devenu éthanol et CO₂, mais le vin n’est pas chimiquement achevé. Acides, colloïdes, lies, phénols, oxygène et microbes continuent de modifier texture et arômes.','El azúcar se ha convertido en gran parte en etanol y CO₂, pero el vino no está químicamente terminado. Ácidos, coloides, lías, fenoles, oxígeno y microbios siguen cambiando textura y aroma.')},
]

const pathways=[
  {title:l('White','Weißwein','Blanc','Blanco'),process:l('Usually pressed before fermentation; solids are managed to balance clarity, yeast nutrition and texture.','Meist vor der Gärung gepresst; Trub wird so gesteuert, dass Klarheit, Hefenährstoffe und Textur im Gleichgewicht bleiben.','Souvent pressé avant fermentation; les bourbes sont gérées entre limpidité, nutrition des levures et texture.','Suele prensarse antes de fermentar; los sólidos se gestionan entre limpidez, nutrición de levaduras y textura.'),structure:l('Low skin tannin, colour protection and acid retention often matter more than extraction.','Wenig Schalentannin; Farbschutz und Säureerhalt sind meist wichtiger als Extraktion.','Peu de tanins pelliculaires; protection de la couleur et conservation de l’acidité dominent souvent.','Poco tanino de piel; protección del color y conservación de acidez suelen importar más que extracción.'),glass:l('Citrus, orchard or tropical fruit, floral notes, acidity, lees texture and possible oak.','Zitrus-, Kern- oder Tropenfrucht, Blüten, Säure, Hefetextur und möglicher Holzeinfluss.','Agrumes, fruits à pépins ou tropicaux, fleurs, acidité, texture des lies et bois éventuel.','Cítricos, fruta de pepita o tropical, flores, acidez, textura de lías y posible madera.')},
  {title:l('Red','Rotwein','Rouge','Tinto'),process:l('Fermentation normally happens with skins; cap management and temperature regulate extraction before pressing.','Die Gärung findet meist mit Schalen statt; Maischearbeit und Temperatur steuern die Extraktion vor dem Pressen.','La fermentation se fait généralement avec les pellicules; chapeau et température règlent l’extraction avant pressurage.','La fermentación suele hacerse con pieles; sombrero y temperatura regulan la extracción antes del prensado.'),structure:l('Colour, skin and seed tannin, alcohol and acidity must be integrated rather than maximised.','Farbe, Schalen- und Kerntannin, Alkohol und Säure müssen integriert, nicht maximiert werden.','Couleur, tanins des pellicules et pépins, alcool et acidité doivent être intégrés, non maximisés.','Color, taninos de piel y semilla, alcohol y acidez deben integrarse, no maximizarse.'),glass:l('Fruit spectrum, tannin grain, acidity, savoury tones and maturation signatures.','Fruchtspektrum, Tanninkorn, Säure, würzige Noten und Reifesignaturen.','Spectre fruité, grain tannique, acidité, notes savoureuses et signatures d’élevage.','Espectro frutal, grano del tanino, acidez, notas sabrosas y señales de crianza.')},
  {title:l('Rosé','Rosé','Rosé','Rosado'),process:l('Brief contact or direct pressing extracts limited colour and phenolics; protection from oxygen is often central.','Kurzer Schalenkontakt oder Direktpressung lösen begrenzt Farbe und Phenole; Sauerstoffschutz ist oft zentral.','Contact bref ou pressurage direct extrait peu de couleur et phénols; la protection contre l’oxygène est souvent centrale.','Contacto breve o prensado directo extrae poco color y fenoles; la protección frente al oxígeno suele ser central.'),structure:l('A white-wine-like fermentation route with a deliberately small phenolic contribution from dark skins.','Ein weißweinähnlicher Gärweg mit bewusst kleinem Phenolbeitrag dunkler Schalen.','Une voie proche du blanc avec une contribution phénolique volontairement faible des pellicules noires.','Una vía parecida al blanco con contribución fenólica deliberadamente pequeña de pieles tintas.'),glass:l('Red berry, citrus or melon, bright acidity, subtle grip and fermentation-derived fruit.','Rote Beeren, Zitrus oder Melone, lebendige Säure, feiner Griff und gärungsgeprägte Frucht.','Baies rouges, agrumes ou melon, acidité vive, légère accroche et fruit fermentaire.','Fruta roja, cítricos o melón, acidez viva, ligero agarre y fruta fermentativa.')},
  {title:l('Sparkling','Schaumwein','Effervescent','Espumoso'),process:l('Carbon dioxide is retained through a second fermentation or captured before the first finishes; lees ageing changes texture and aroma.','Kohlendioxid wird durch zweite Gärung gebunden oder vor Ende der ersten Gärung bewahrt; Hefelager verändert Textur und Aroma.','Le CO₂ est retenu par seconde fermentation ou avant la fin de la première; l’élevage sur lies change texture et arômes.','El CO₂ se retiene mediante segunda fermentación o antes de terminar la primera; la crianza sobre lías cambia textura y aroma.'),structure:l('Base-wine acidity, pressure, dosage and lees-derived colloids shape balance and mousse.','Grundweinsäure, Druck, Dosage und hefebürtige Kolloide prägen Balance und Mousseux.','Acidité du vin de base, pression, dosage et colloïdes des lies façonnent équilibre et mousse.','Acidez del vino base, presión, dosaje y coloides de lías dan forma al equilibrio y la espuma.'),glass:l('Bubble texture, acidity, dosage balance, autolytic bread notes and fruit freshness.','Perlage, Säure, Dosagebalance, autolytische Brotnoten und Fruchtfrische.','Texture des bulles, acidité, équilibre du dosage, notes autolytiques et fraîcheur du fruit.','Textura de burbuja, acidez, equilibrio del dosaje, notas autolíticas y frescura frutal.')},
  {title:l('Skin-contact white','Maischevergorener Weißwein','Blanc de macération','Blanco con maceración'),process:l('White grapes ferment or macerate with skins, extending extraction beyond conventional white-wine practice.','Weiße Trauben gären oder mazerieren mit Schalen; die Extraktion geht über klassische Weißweinbereitung hinaus.','Les raisins blancs fermentent ou macèrent avec leurs pellicules, au-delà du schéma blanc conventionnel.','Las uvas blancas fermentan o maceran con pieles, más allá de la práctica convencional de blancos.'),structure:l('More phenolic grip, colour and oxidative tolerance may result, but duration and vessel create a broad range of styles.','Mehr phenolischer Griff, Farbe und oxidative Robustheit sind möglich; Dauer und Gefäß erzeugen jedoch viele Stile.','Davantage de prise phénolique, couleur et tolérance oxydative peuvent apparaître; durée et contenant élargissent les styles.','Puede haber más agarre fenólico, color y tolerancia oxidativa; duración y recipiente crean estilos muy diversos.'),glass:l('Tea-like grip, dried citrus, herbs, flowers, spice and sometimes deliberately oxidative tones.','Teeartiger Griff, getrocknete Zitrusfrucht, Kräuter, Blüten, Gewürze und teils bewusst oxidative Töne.','Prise rappelant le thé, agrumes secs, herbes, fleurs, épices et parfois des tons oxydatifs voulus.','Agarre de té, cítrico seco, hierbas, flores, especias y a veces tonos oxidativos buscados.')},
]

export function VineToGlassExperience({locale}:{locale:Locale}){
  const c=ui[locale]
  const [stageIndex,setStageIndex]=useState(0)
  const [transformIndex,setTransformIndex]=useState(0)
  const [pathIndex,setPathIndex]=useState(0)
  const stage=stages[stageIndex],transformation=transformations[transformIndex],pathway=pathways[pathIndex]
  return <div className="vine-glass-experience">
    <section className="vine-process-atlas">
      <header><span className="eyebrow">{c.eyebrow}</span><h2>{c.title}</h2></header>
      <figure><img src={processPlate} alt={c.processAlt}/></figure>
      <nav aria-label={c.title}>{stages.map((item,index)=><button key={item.title.en} className={stageIndex===index?'active':''} aria-pressed={stageIndex===index} onClick={()=>setStageIndex(index)}><span>{String(index+1).padStart(2,'0')}</span>{item.title[locale]}</button>)}</nav>
      <article className="vine-stage-detail" aria-live="polite"><div className="stage-number">{String(stageIndex+1).padStart(2,'0')}</div><div className="stage-copy"><h3>{stage.title[locale]}</h3><dl><div><dt><Grape/>{c.material}</dt><dd>{stage.material[locale]}</dd></div><div><dt><Beaker/>{c.decision}</dt><dd>{stage.decision[locale]}</dd></div><div><dt><Sparkles/>{c.trace}</dt><dd>{stage.trace[locale]}</dd></div><div><dt><Eye/>{c.evidence}</dt><dd>{stage.evidence[locale]}</dd></div></dl></div></article>
    </section>

    <section className="vine-transformation">
      <figure><img src={transformationPlate} alt={c.transformAlt}/></figure>
      <div><span className="eyebrow">{c.transformEyebrow}</span><h2>{c.transformTitle}</h2><nav>{transformations.map((item,index)=><button key={item.title.en} className={transformIndex===index?'active':''} aria-pressed={transformIndex===index} onClick={()=>setTransformIndex(index)}>{String(index+1).padStart(2,'0')} · {item.title[locale]}</button>)}</nav><article aria-live="polite"><h3>{transformation.title[locale]}</h3><p>{transformation.body[locale]}</p></article></div>
    </section>

    <section className="vine-pathways">
      <header><span className="eyebrow">{c.pathEyebrow}</span><h2>{c.pathTitle}</h2></header>
      <figure><img src={pathwaysPlate} alt={c.pathAlt}/></figure>
      <nav>{pathways.map((item,index)=><button key={item.title.en} className={pathIndex===index?'active':''} aria-pressed={pathIndex===index} onClick={()=>setPathIndex(index)}>{item.title[locale]}</button>)}</nav>
      <article aria-live="polite"><h3>{pathway.title[locale]}</h3><div><section><Beaker/><span>{c.process}</span><p>{pathway.process[locale]}</p></section><section><Droplets/><span>{c.structure}</span><p>{pathway.structure[locale]}</p></section><section><ThermometerSun/><span>{c.glass}</span><p>{pathway.glass[locale]}</p></section></div></article>
    </section>

    <section className="vine-table-experiment"><div><Clock3/><span className="eyebrow">{c.experiment}</span><h2>{c.experimentTitle}</h2></div><ol><li><span>01</span><p>{c.stepOne}</p></li><li><span>02</span><p>{c.stepTwo}</p></li><li><span>03</span><p>{c.stepThree}</p><ArrowRight/></li></ol></section>
  </div>
}
